Repository milvus-io/milvus-docs, pull requests merged in 2021-11, with the labels that each got.

#980 add home.md, modify link of sizing-tool
  site/en/home/home.md
  site/en/menuStructure/en.json
  site/zh-CN/home/home.md
  site/zh-CN/menuStructure/cn.json
Labels: size/L

#982 Update sizing tool link
  site/en/menuStructure/en.json
Labels: size/XS

#983 Update sizing tool link
  site/zh-CN/menuStructure/cn.json
Labels: size/XS

#984 Update sizing tool link
  site/en/menuStructure/en.json
Labels: size/XS

#985 Update sizing tool link
  site/zh-CN/menuStructure/cn.json
Labels: size/XS

#986 Update sizing tool link
  site/en/menuStructure/en.json
Labels: size/XS

#987 Update sizing tool link
  site/zh-CN/menuStructure/cn.json
Labels: size/XS

#988 Update CN home.md
  site/zh-CN/home/home.md
Labels: size/M

#989 Update EN home.md
  site/en/home/home.md
Labels: size/XS

#990 Update 1.1.1 home.md
  site/en/home/home.md
Labels: size/M

#991 Added icon images for homepage.
  assets/cpu_only.svg
  assets/gpu_enabled.svg
Labels: size/S

#969 [DO NOT MERGE] Doc Iteration - Get Started
  site/en/fragments/installation_guide.md
  site/en/fragments/installation_guide_cluster.md
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/install-node.md
  site/en/getstarted/install-pymilvus.md
  site/en/getstarted/install_offline-docker.md
  site/en/getstarted/install_offline-helm.md
  site/en/getstarted/prerequisite-docker.md
  site/en/getstarted/prerequisite-helm.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/menuStructure/en.json
  site/zh-CN/getstarted/install-node.md
  site/zh-CN/getstarted/install-pymilvus.md
  site/zh-CN/menuStructure/cn.json
Labels: size/XL

#993 Minor fix to 1.1.1 EN home.md
  site/en/home/home.md
Labels: size/XS

#992 Update 1.1.1 CN home.md
  site/zh-CN/home/home.md
Labels: size/M

#994 Update 1.1.0 EN home.md
  site/en/home/home.md
Labels: size/M

#995 Update 1.0.0 EN home.md
  site/en/home/home.md
Labels: size/M

#996 Update 1.1.0 CN home.md
  site/zh-CN/home/home.md
Labels: size/M

#997 Update 1.0.0 CN home.md
  site/zh-CN/home/home.md
Labels: size/M

#954 Rewrote alert.md
  site/en/adminGuide/alert.md
Labels: size/M

#999 Deleted extra space
  site/en/adminGuide/alert.md
Labels: size/XS

#971 Rewrote visualize.md
  site/en/adminGuide/visualize.md
Labels: size/M

#1001 Adjusted monitor file structure.
  site/en/adminGuide/monitor/alert.md
  site/en/adminGuide/monitor/monitor.md
  site/en/adminGuide/monitor/visualize.md
  site/zh-CN/adminGuide/monitor/monitor.md
Labels: size/XS

#1000 Fix Index Note
  site/en/reference/index/index.md
  site/zh-CN/reference/index/index.md
Labels: size/XS

#1002 Update en.json
  site/en/menuStructure/en.json
Labels: size/S

#1003 Added alert.md to CN site.
  site/zh-CN/adminGuide/monitor/alert.md
Labels: size/M

#1005 Added screenshots for alert.md
  assets/alert_notification.png
  assets/delete_alert.png
  assets/notification_message.png
Labels: size/XS

#1006 Added visualize.md to the CN site
  site/zh-CN/adminGuide/monitor/visualize.md
Labels: size/M

#1008 Update cn.json
  site/zh-CN/menuStructure/cn.json
Labels: size/M

#1009 Remove alert and visualize in monitor.md
  site/en/adminGuide/monitor/monitor.md
Labels: size/M

#1010 Update monitor.md
  site/zh-CN/adminGuide/monitor/monitor.md
Labels: size/M

#1011 Fix typo
  site/zh-CN/menuStructure/cn.json
Labels: size/XS

#952 add content to set_up_storage
  site/en/adminGuide/deploy_s3.md
Labels: size/M

#943 Update scaleout.md
  site/en/adminGuide/scaleout.md
Labels: size/L

#1013 Update CN scaleout.md with new EN content
  site/zh-CN/adminGuide/scaleout.md
Labels: size/L

#1015 rewrite aws.md
  site/en/adminGuide/clouds/aws/aws.md
Labels: size/XL

#1016 rewrite eks
  site/en/adminGuide/clouds/aws/eks.md
Labels: size/M

#925 DOC Translation example code to Dutch #911
  site/en/getstarted/example_code_NL.md
Labels: hacktoberfest, size/L

#1018 Minor fix to headings
  site/en/adminGuide/scaleout.md
Labels: size/XS

#1019 Minor fix to headings
  site/zh-CN/adminGuide/scaleout.md
Labels: size/XS

#1021 Fix Node API Link
  site/en/getstarted/install-node.md
Labels: size/XS

#1024 Fix title
  site/en/getstarted/prerequisite-helm.md
  site/en/menuStructure/en.json
Labels: size/XS

#1028 Fix upper cases
  site/en/getstarted/prerequisite-helm.md
Labels: size/XS

#1030 add commands
  site/en/userGuide/tools/cli_commands.md
Labels: size/L

#1033 Added icons to homepage.md
  assets/bootcamps.svg
  assets/cpu.svg
  assets/gpu.svg
  assets/standalone.svg
  assets/start.svg
Labels: size/M

#1034 Added icons to homepage
  assets/bootcamps.svg
  assets/cpu.svg
  assets/gpu.svg
  assets/standalone.svg
  assets/start.svg
Labels: size/M

#1035 Added icons to homepage
  assets/bootcamps.svg
  assets/cpu.svg
  assets/gpu.svg
  assets/standalone.svg
  assets/start.svg
Labels: size/M

#1036 Added icons to homepage
  assets/bootcamps.svg
  assets/cpu.svg
  assets/gpu.svg
  assets/standalone.svg
  assets/start.svg
Labels: size/M

#1020 [Do Not Merge] Rewrote monitor.md
  site/en/adminGuide/monitor/monitor.md
Labels: doc-improvement, size/M

#1023 [Do Not Merge] Removed m2h.md
  site/en/menuStructure/en.json
Labels: size/S

#1038 Removed h2m.md on CN site.
  site/zh-CN/menuStructure/cn.json
Labels: size/S

#1029 Added monitor_overview.md
  site/en/adminGuide/monitor/monitor_overview.md
Labels: size/S

#1040 Added monitor_overview.md to the CN site.
  site/zh-CN/adminGuide/monitor/monitor_overview.md
Labels: size/S

#1041 Added monitor_overview in EN menustructure
  site/en/menuStructure/en.json
Labels: size/S

#1032 rewrite gcp
  site/en/adminGuide/clouds/gcp.md
Labels: size/L

#1042 Added monitor_overview in CN menustructure
  site/zh-CN/menuStructure/cn.json
Labels: size/S

#1043 Updated the title of monitor_overview.md in menu
  site/en/menuStructure/en.json
Labels: size/XS

#1025 [Do Not Merge] Update h2m.md
  site/en/adminGuide/backup/h2m.md
Labels: size/M

#1045 Align CN monitor.md with EN
  site/zh-CN/adminGuide/monitor/monitor.md
Labels: size/M

#1046 Align CN h2m.md with EN
  site/zh-CN/adminGuide/backup/h2m.md
Labels: size/M

#1026 [Do Not Merge] Update f2m.md
  site/en/migrate/f2m.md
Labels: size/M

#1048 Align CN f2m.md with EN
  site/zh-CN/migrate/f2m.md
Labels: size/M

#1027 [Do Not Merge] Update m2m.md
  site/en/adminGuide/m2m.md
Labels: size/M

#1050 Align CN m2m.md with EN
  site/zh-CN/adminGuide/m2m.md
Labels: size/M

#1062 Update tab name for helm
  site/en/getstarted/cluster/install_cluster-helm.md
Labels: size/XS

#1063 Update tab name for docker compose
  site/en/getstarted/cluster/install_cluster-docker.md
Labels: size/XS

#1067 Fix API link on docs homepage
  site/en/home/home.md
Labels: size/XS

#1068 Fix API link on docs homepage.
  site/zh-CN/home/home.md
Labels: size/XS

#1070 RC8-releaase-Part 1
  site/en/Variables.json
  site/en/getstarted/install-pymilvus.md
  site/en/release_notes.md
  site/zh-CN/Variables.json
  site/zh-CN/getstarted/install-pymilvus.md
  site/zh-CN/release_notes.md
Labels: size/M

#1064 Added install Milvus cluster with Milvus Operator
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XL

#1073 RC8 release part2
  site/en/release_notes.md
Labels: size/L

#1074 Fix headings
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/S

#1075 Fix links in What's next
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/S

#1076 Added milvus operator to CN site
  site/zh-CN/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XL

#1077 Update tab name of helm installation
  site/zh-CN/getstarted/cluster/install_cluster-helm.md
Labels: size/XS

#1079 Update tab name
  site/zh-CN/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#1080 Update tab name
  site/zh-CN/getstarted/cluster/install_cluster-helm.md
Labels: size/XS

#1081 Update tab name
  site/zh-CN/getstarted/cluster/install_cluster-docker.md
Labels: size/XS

#1083 Revise adopter name.
  site/zh-CN/about/milvus_adopters.md
Labels: size/XS

#1084 replace # with html header
  site/en/userGuide/tools/cli_commands.md
Labels: size/L

#1086 zh_cli_update
  site/zh-CN/userGuide/tools/cli_commands.md
  site/zh-CN/userGuide/tools/cli_overview.md
  site/zh-CN/userGuide/tools/install_cli.md
Labels: size/XL

#1088 change header_zh
  site/zh-CN/userGuide/tools/cli_commands.md
Labels: size/L

#1089 CN- RC8
  site/zh-CN/release_notes.md
Labels: size/L

#1090 Fix image
  assets/new_roadmap.jpg
Labels: size/XS

#1091 Update rc8 API reference link on homepage
  site/en/home/home.md
Labels: size/XS

#1092 Update rc8 API reference link on homepage
  site/zh-CN/home/home.md
Labels: size/XS

#1095 replace rowId with primaryKey
  site/en/reference/architecture/data_processing.md
  site/en/reference/glossary.md
  site/zh-CN/reference/architecture/data_processing.md
  site/zh-CN/reference/glossary.md
Labels: size/S

#1096 update query example and add 0.1.8 support
  site/zh-CN/userGuide/tools/cli_commands.md
  site/zh-CN/userGuide/tools/cli_overview.md
  site/zh-CN/userGuide/tools/install_cli.md
Labels: size/M

#1097 update query example and add 0.1.8 support_en
  site/en/userGuide/tools/cli_commands.md
  site/en/userGuide/tools/cli_overview.md
Labels: size/M

#1098 update install procedure_zh
  site/zh-CN/userGuide/tools/install_cli.md
Labels: size/S

#1099 add dedup_limit_rc8
  site/en/release_notes.md
  site/zh-CN/release_notes.md
Labels: size/XS

#1100 Uploaded Milvus workflow image
  assets/milvus_workflow.jpeg
Labels: size/XS

#1101 Added workflow image to overview.md
  site/en/about/overview.md
Labels: size/XS

#1102 Added workflow image to CN overview.md
  site/zh-CN/about/overview.md
Labels: size/XS

#1104 Fix install command
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/zh-CN/getstarted/cluster/install_cluster-docker.md
  site/zh-CN/getstarted/standalone/install_standalone-docker.md
Labels: size/XS

#1106 Update Admin guide menustructure
  site/en/menuStructure/en.json
Labels: size/M

#1107 gcp_rearrange
  site/en/adminGuide/clouds/gcp.md
Labels: size/S

#1108 Udpated admin guide menustructure
  site/zh-CN/menuStructure/cn.json
Labels: size/M

#1103 Update allocate.md
  site/en/adminGuide/allocate.md
Labels: size/M

#1087 Update upgrade.md
  site/en/adminGuide/upgrade.md
Labels: size/L

#1105 Updated what's new in docs CN
  site/zh-CN/home/home.md
Labels: size/S

#1093 Update what's new in docs
  site/en/home/home.md
Labels: size/S

#1069 Doc iteration userguide
  site/en/Variables.json
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/getstarted/install-node.md
  site/en/getstarted/install-pymilvus.md
  site/en/getstarted/install_offline-docker.md
  site/en/getstarted/install_offline-helm.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/home/home.json
  site/en/home/home.md
  site/en/menuStructure/en.json
  site/en/reference/schema/collection_schema.md
  site/en/reference/schema/field_schema.md
  site/en/userGuide/build.md
  site/en/userGuide/connect.md
  site/en/userGuide/create.md
  site/en/userGuide/delete.md
  site/en/userGuide/drop.md
  site/en/userGuide/insert.md
  site/en/userGuide/manage_collection.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/manage_data.md
  site/en/userGuide/manage_index.md
  site/en/userGuide/manage_partition.md
  site/en/userGuide/query.md
  site/en/userGuide/search/expression.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/search/timetravel.md
  site/zh-CN/Variables.json
  site/zh-CN/getstarted/cluster/install_cluster-milvusoperator.md
  site/zh-CN/getstarted/install-node.md
  site/zh-CN/getstarted/install-pymilvus.md
  site/zh-CN/home/home.json
  site/zh-CN/home/home.md
  site/zh-CN/menuStructure/cn.json
  site/zh-CN/reference/schema/collection_schema.md
  site/zh-CN/reference/schema/field_schema.md
  site/zh-CN/userGuide/build.md
  site/zh-CN/userGuide/connect.md
  site/zh-CN/userGuide/create.md
  site/zh-CN/userGuide/delete.md
  site/zh-CN/userGuide/drop.md
  site/zh-CN/userGuide/insert.md
  site/zh-CN/userGuide/manage_collection.md
  site/zh-CN/userGuide/manage_connection.md
  site/zh-CN/userGuide/manage_data.md
  site/zh-CN/userGuide/manage_index.md
  site/zh-CN/userGuide/manage_partition.md
  site/zh-CN/userGuide/query.md
  site/zh-CN/userGuide/search/expression.md
  site/zh-CN/userGuide/search/hybridsearch.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
  site/zh-CN/userGuide/search/timetravel.md
Labels: size/XXL

#1109 Fix img
  site/en/developerTools/milvusdm.md
  site/zh-CN/developerTools/milvusdm.md
Labels: size/XS

#1110 Fix img
  site/en/developerTools/milvusdm.md
  site/zh-CN/developerTools/milvusdm.md
Labels: size/XS

#1111 Fix img
  site/en/developerTools/milvusdm.md
  site/zh-CN/developerTools/milvusdm.md
Labels: size/XS

#1112 Fix menu
  site/en/menuStructure/en.json
  site/zh-CN/menuStructure/cn.json
Labels: size/XS

#1082 rewrite azure
  site/en/adminGuide/clouds/azure.md
Labels: size/L

#1113 Fix multicode
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/zh-CN/userGuide/search/hybridsearch.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
Labels: size/S

#1114 Loco richard patch 1
  site/en/userGuide/manage_connection.md
  site/zh-CN/userGuide/manage_connection.md
Labels: size/S

#1115 Fix python code block
  site/en/getstarted/example_code.md
  site/en/getstarted/example_code_NL.md
  site/en/getstarted/example_code_bn.md
  site/en/getstarted/example_code_de.md
  site/en/getstarted/example_code_es.md
  site/en/getstarted/example_code_fr.md
  site/en/getstarted/example_code_id.md
  site/en/getstarted/example_code_it.md
  site/en/userGuide/manage_collection.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/manage_data.md
  site/en/userGuide/manage_index.md
  site/en/userGuide/manage_partition.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/search/timetravel.md
  site/zh-CN/getstarted/example_code.md
  site/zh-CN/userGuide/manage_collection.md
  site/zh-CN/userGuide/manage_connection.md
  site/zh-CN/userGuide/manage_data.md
  site/zh-CN/userGuide/manage_index.md
  site/zh-CN/userGuide/manage_partition.md
  site/zh-CN/userGuide/search/hybridsearch.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
  site/zh-CN/userGuide/search/timetravel.md
Labels: size/XXL

#1116 Minor fix
  site/en/userGuide/manage_collection.md
  site/zh-CN/userGuide/manage_collection.md
Labels: size/XS

#1117 Minor fix
  site/en/userGuide/manage_collection.md
Labels: size/XS

#1118 Align with new EN upgrade.md
  site/zh-CN/adminGuide/upgrade.md
Labels: size/L

#1120 Align with new EN allocate.md
  site/zh-CN/adminGuide/allocate.md
Labels: size/M

#1122 use_html_header
  site/en/release_notes.md
Labels: size/M

#1123 use_html_header_zh
  site/zh-CN/release_notes.md
Labels: size/M

#1124 gcp translation_zh
  site/zh-CN/adminGuide/clouds/gcp.md
Labels: size/L

#1126 Fix parameter bug
  site/en/faq/milvus_faq/performance_faq.md
Labels: size/XS

#1127 Fix parameter bug
  site/zh-CN/faq/milvus_faq/performance_faq.md
Labels: size/XS

#1128 Update performance_faq.md
  site/en/faq/milvus_faq/performance_faq.md
Labels: size/XS

#1129 Fix broken images in FAQ
  site/zh-CN/faq/milvus_faq/performance_faq.md
Labels: size/XS

#1130 Added CN translation for allocate.md
  site/zh-CN/adminGuide/allocate.md
Labels: size/M

#1131 Fix: dupe H1 and H2 in timetravel.md
  site/en/userGuide/search/timetravel.md
  site/zh-CN/userGuide/search/timetravel.md
Labels: size/XS

#1132 trans azure for zh website
  site/zh-CN/adminGuide/clouds/azure.md
Labels: size/L

#1133 fix typo
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#1134 Fix code format
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#1136 Fix wrong links in product FAQ
  site/en/faq/milvus_faq/product_faq.md
  site/zh-CN/faq/milvus_faq/product_faq.md
Labels: size/S

#1135 Added CN translation for install_cluster-milvusoperator.md
  site/zh-CN/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/L

#1137 V2.0.0 update FAQ (EN and CN)
  site/en/Variables.json
  site/en/about/limitations.md
  site/en/faq/milvus_faq/operational_faq.md
  site/en/faq/milvus_faq/performance_faq.md
  site/en/faq/milvus_faq/product_faq.md
  site/zh-CN/Variables.json
  site/zh-CN/about/limitations.md
  site/zh-CN/faq/milvus_faq/operational_faq.md
  site/zh-CN/faq/milvus_faq/performance_faq.md
  site/zh-CN/faq/milvus_faq/product_faq.md
Labels: size/M

#1138 v2.0.0 Product FAQ - Clarification on dedup
  site/en/faq/milvus_faq/product_faq.md
  site/zh-CN/faq/milvus_faq/product_faq.md
Labels: product-change, size/S

#1140 Revert "V2.0.0 update FAQ (EN and CN)"
  site/en/Variables.json
  site/en/about/limitations.md
  site/en/faq/milvus_faq/operational_faq.md
  site/en/faq/milvus_faq/performance_faq.md
  site/en/faq/milvus_faq/product_faq.md
  site/zh-CN/Variables.json
  site/zh-CN/about/limitations.md
  site/zh-CN/faq/milvus_faq/operational_faq.md
  site/zh-CN/faq/milvus_faq/performance_faq.md
  site/zh-CN/faq/milvus_faq/product_faq.md
Labels: size/M

#1141 V2.0.0 update faq
  site/en/Variables.json
  site/zh-CN/Variables.json
Labels: size/XS

#1143 Update Python3 requirement
  site/en/getstarted/install-pymilvus.md
Labels: size/XS

#1144 Update Python3 requirement
  site/zh-CN/getstarted/install-pymilvus.md
Labels: size/XS

#1145 translate ec2
  site/zh-CN/adminGuide/clouds/aws/aws.md
Labels: size/XL

#1146 Added time travel image
  assets/time_travel.png
Labels: size/XS

#1148 Added CN translation for upgrade.md
  site/zh-CN/adminGuide/upgrade.md
Labels: size/M

#1149 Update FAQ of installation on Windows
  site/en/faq/milvus_faq/operational_faq.md
Labels: size/XS

#1151 Fix typo
  site/en/adminGuide/backup/h2m.md
Labels: size/XS

#1152 Fix typo
  site/en/migrate/f2m.md
Labels: size/XS

#1150 Updated the FAQ of installation on Windows
  site/zh-CN/faq/milvus_faq/operational_faq.md
Labels: size/XS

#1153 Added translation for h2m.md
  site/zh-CN/adminGuide/backup/h2m.md
Labels: size/M

#1154 Fix typo
  site/en/migrate/f2m.md
Labels: size/XS

#1155 Added translation for f2m.md
  site/zh-CN/migrate/f2m.md
Labels: size/M

#1156 Added CN translation for m2m.md
  site/zh-CN/adminGuide/m2m.md
Labels: size/M

#1157 Update FAQ
  site/en/faq/milvus_faq/operational_faq.md
Labels: size/S

#1158 Align CN FAQ with EN
  site/zh-CN/faq/milvus_faq/operational_faq.md
Labels: size/S

#1159 translate eks
  site/zh-CN/adminGuide/clouds/aws/eks.md
Labels: size/M

#1160 Add Node.js code
  site/en/userGuide/search/timetravel.md
  site/zh-CN/userGuide/search/timetravel.md
Labels: size/L

#1163 Fix code bug
  site/en/adminGuide/monitor/monitor.md
Labels: size/XS
