Repository milvus-io/milvus-docs, pull requests merged in 2021-12, with the labels that each got.

#1195 add disconnect and import_remote
  site/en/userGuide/tools/cli_commands.md
Labels: size/M

#1196 add disconnect and import remote_zh
  site/zh-CN/userGuide/tools/cli_commands.md
Labels: size/M

#1198 Fix outdated info
  site/en/reference/schema/field_schema.md
  site/zh-CN/reference/schema/field_schema.md
Labels: size/XS

#1199 fix typo
  site/en/about/overview.md
Labels: size/XS

#1201 Fix link format error
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#1202 Fix link format error
  site/zh-CN/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#1204 fix_issue #1192
  site/en/about/limitations.md
  site/zh-CN/about/limitations.md
Labels: size/XS

#1203 Update milvus_adopters.md
  site/en/about/milvus_adopters.md
Labels: size/XS

#1206 Add Insight Docs
  assets/collection_schema.png
  assets/create_collection_dialog_box1.png
  assets/create_collection_dialog_box2.png
  assets/create_collection_dialog_box3.png
  assets/delete_collection.png
  assets/insight_overview_page.png
  assets/load_collection1.png
  assets/load_collection2.png
  assets/load_collection3.png
  assets/release_collection1.png
  assets/release_collection2.png
  site/en/about/comparison.md
  site/en/menuStructure/en.json
  site/en/userGuide/tools/insight.md
  site/en/userGuide/tools/insight_collection.md
  site/en/userGuide/tools/insight_data.md
  site/en/userGuide/tools/insight_faq.md
  site/en/userGuide/tools/insight_index.md
  site/en/userGuide/tools/insight_install-docker.md
  site/en/userGuide/tools/insight_install-helm.md
  site/en/userGuide/tools/insight_install.md
  site/en/userGuide/tools/insight_overview.md
  site/en/userGuide/tools/insight_partition.md
  site/en/userGuide/tools/insight_query.md
  site/en/userGuide/tools/insight_search.md
  site/en/userGuide/tools/insight_system.md
  site/zh-CN/menuStructure/cn.json
  site/zh-CN/userGuide/tools/insight.md
  site/zh-CN/userGuide/tools/insight_collection.md
  site/zh-CN/userGuide/tools/insight_data.md
  site/zh-CN/userGuide/tools/insight_faq.md
  site/zh-CN/userGuide/tools/insight_index.md
  site/zh-CN/userGuide/tools/insight_install-docker.md
  site/zh-CN/userGuide/tools/insight_install-helm.md
  site/zh-CN/userGuide/tools/insight_install.md
  site/zh-CN/userGuide/tools/insight_overview.md
  site/zh-CN/userGuide/tools/insight_partition.md
  site/zh-CN/userGuide/tools/insight_query.md
  site/zh-CN/userGuide/tools/insight_search.md
  site/zh-CN/userGuide/tools/insight_system.md
Labels: size/XXL

#1205 Add CLI to User Guide
  site/en/fragments/multiple_code.md
  site/en/userGuide/manage_collection.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/manage_data.md
  site/en/userGuide/manage_index.md
  site/en/userGuide/manage_partition.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/zh-CN/fragments/multiple_code.md
  site/zh-CN/userGuide/manage_collection.md
  site/zh-CN/userGuide/manage_connection.md
  site/zh-CN/userGuide/manage_data.md
  site/zh-CN/userGuide/manage_index.md
  site/zh-CN/userGuide/manage_partition.md
  site/zh-CN/userGuide/search/hybridsearch.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
Labels: size/XL

#1207 Add insight docs
  assets/insight_data1.png
  assets/insight_data2.png
  assets/insight_data3.png
  assets/insight_data4.png
  assets/insight_data5.png
  assets/insight_data6.png
  assets/insight_index1.png
  assets/insight_index2.png
  assets/insight_index3.png
  assets/insight_partition1.png
  assets/insight_partition2.png
  assets/insight_partition3.png
  assets/insight_query1.png
  assets/insight_query2.png
  assets/insight_query3.png
  assets/insight_query4.png
  assets/insight_search1.png
  assets/insight_search2.png
  assets/insight_search3.png
  assets/insight_search4.png
  assets/insight_search5.png
  assets/insight_search6.png
  assets/insight_system1.png
  assets/insight_system2.png
  assets/insight_system3.png
  assets/insight_system4.png
  site/en/userGuide/tools/insight_data.md
  site/en/userGuide/tools/insight_index.md
  site/en/userGuide/tools/insight_install-docker.md
  site/en/userGuide/tools/insight_install-helm.md
  site/en/userGuide/tools/insight_partition.md
  site/en/userGuide/tools/insight_query.md
  site/en/userGuide/tools/insight_search.md
  site/en/userGuide/tools/insight_system.md
  site/zh-CN/userGuide/tools/insight_data.md
  site/zh-CN/userGuide/tools/insight_index.md
  site/zh-CN/userGuide/tools/insight_install-docker.md
  site/zh-CN/userGuide/tools/insight_install-helm.md
  site/zh-CN/userGuide/tools/insight_partition.md
  site/zh-CN/userGuide/tools/insight_query.md
  site/zh-CN/userGuide/tools/insight_search.md
  site/zh-CN/userGuide/tools/insight_system.md
Labels: size/L

#1209 add exe installation method for milvus cli
  assets/milvus_cli_exe.png
  site/en/userGuide/tools/install_cli.md
Labels: size/S

#1210 Update insight_collection.md
  site/en/userGuide/tools/insight_collection.md
Labels: size/XS

#1211 Update glossary.md
  site/en/reference/glossary.md
Labels: size/S

#1212 review insight_faq_zh
  site/zh-CN/userGuide/tools/insight_faq.md
Labels: size/S

#1213 review insight_collection.md_zh
  site/zh-CN/userGuide/tools/insight_collection.md
Labels: size/M

#1215 Add CLI Table
  site/en/userGuide/manage_collection.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/manage_data.md
  site/en/userGuide/manage_index.md
  site/en/userGuide/manage_partition.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/zh-CN/userGuide/manage_collection.md
  site/zh-CN/userGuide/manage_connection.md
  site/zh-CN/userGuide/manage_data.md
  site/zh-CN/userGuide/manage_index.md
  site/zh-CN/userGuide/manage_partition.md
  site/zh-CN/userGuide/search/hybridsearch.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
Labels: size/XXL

#1216 Fix table
  site/en/userGuide/manage_collection.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/manage_data.md
  site/en/userGuide/manage_index.md
  site/en/userGuide/manage_partition.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/zh-CN/userGuide/manage_collection.md
  site/zh-CN/userGuide/manage_connection.md
  site/zh-CN/userGuide/manage_data.md
  site/zh-CN/userGuide/manage_index.md
  site/zh-CN/userGuide/manage_partition.md
  site/zh-CN/userGuide/search/hybridsearch.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
Labels: size/L

#1217 Loco richard patch 1
  site/en/userGuide/manage_collection.md
  site/zh-CN/userGuide/manage_collection.md
Labels: size/S

#1219 add milvus operator docs
  site/en/adminGuide/operator.md
  site/en/menuStructure/en.json
  site/zh-CN/adminGuide/operator.md
  site/zh-CN/menuStructure/cn.json
Labels: size/XL

#1220 review insight cn
  site/zh-CN/userGuide/tools/insight.md
  site/zh-CN/userGuide/tools/insight_index.md
  site/zh-CN/userGuide/tools/insight_install-docker.md
  site/zh-CN/userGuide/tools/insight_install-helm.md
  site/zh-CN/userGuide/tools/insight_overview.md
  site/zh-CN/userGuide/tools/insight_partition.md
  site/zh-CN/userGuide/tools/insight_query.md
  site/zh-CN/userGuide/tools/insight_search.md
  site/zh-CN/userGuide/tools/insight_system.md
Labels: size/L

#1221 Insight cn
  site/en/userGuide/tools/insight_data.md
  site/en/userGuide/tools/insight_partition.md
  site/en/userGuide/tools/insight_query.md
  site/zh-CN/userGuide/tools/insight.md
  site/zh-CN/userGuide/tools/insight_collection.md
  site/zh-CN/userGuide/tools/insight_data.md
  site/zh-CN/userGuide/tools/insight_faq.md
  site/zh-CN/userGuide/tools/insight_index.md
  site/zh-CN/userGuide/tools/insight_install-docker.md
  site/zh-CN/userGuide/tools/insight_install-helm.md
  site/zh-CN/userGuide/tools/insight_overview.md
  site/zh-CN/userGuide/tools/insight_partition.md
  site/zh-CN/userGuide/tools/insight_query.md
  site/zh-CN/userGuide/tools/insight_search.md
  site/zh-CN/userGuide/tools/insight_system.md
Labels: size/XL

#1223 Update glossary.md for zh
  site/zh-CN/reference/glossary.md
Labels: size/M

#1225 Remake UserGuide Step 1 Separate Page, Add Details
  site/en/fragments/multiple_code.md
  site/en/home/home.json
  site/en/home/home.md
  site/en/menuStructure/en.json
  site/en/reference/schema/collection_schema.md
  site/en/reference/schema/field_schema.md
  site/en/release_notes.md
  site/en/userGuide/build_index.md
  site/en/userGuide/check_collection.md
  site/en/userGuide/check_partition.md
  site/en/userGuide/collection_alias.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/create_partition.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_collection.md
  site/en/userGuide/drop_index.md
  site/en/userGuide/drop_partition.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/manage_collection.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/manage_data.md
  site/en/userGuide/manage_index.md
  site/en/userGuide/manage_partition.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/zh-CN/fragments/multiple_code.md
  site/zh-CN/home/home.json
  site/zh-CN/home/home.md
  site/zh-CN/menuStructure/cn.json
  site/zh-CN/reference/schema/collection_schema.md
  site/zh-CN/reference/schema/field_schema.md
  site/zh-CN/release_notes.md
  site/zh-CN/userGuide/build_index.md
  site/zh-CN/userGuide/check_collection.md
  site/zh-CN/userGuide/check_partition.md
  site/zh-CN/userGuide/collection_alias.md
  site/zh-CN/userGuide/create_collection.md
  site/zh-CN/userGuide/create_partition.md
  site/zh-CN/userGuide/delete_data.md
  site/zh-CN/userGuide/drop_collection.md
  site/zh-CN/userGuide/drop_index.md
  site/zh-CN/userGuide/drop_partition.md
  site/zh-CN/userGuide/insert_data.md
  site/zh-CN/userGuide/load_collection.md
  site/zh-CN/userGuide/manage_collection.md
  site/zh-CN/userGuide/manage_connection.md
  site/zh-CN/userGuide/manage_data.md
  site/zh-CN/userGuide/manage_index.md
  site/zh-CN/userGuide/manage_partition.md
  site/zh-CN/userGuide/search/hybridsearch.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
Labels: size/XXL

#1228 Add load and Fix Menu
  site/en/menuStructure/en.json
  site/zh-CN/menuStructure/cn.json
Labels: size/S

#1229 Fix menu
  site/zh-CN/menuStructure/cn.json
Labels: size/XS

#1230 add raises
  site/en/userGuide/manage_connection.md
Labels: size/S

#1231 overwrite with new ones
  site/en/userGuide/.DS_Store
  site/en/userGuide/tools/.DS_Store
  site/en/userGuide/tools/cli_commands.md
  site/en/userGuide/tools/cli_overview.md
  site/en/userGuide/tools/install_cli.md
Labels: size/XL

#1235 overwrite with new ones_zh
  .DS_Store
  site/.DS_Store
  site/en/userGuide/.DS_Store
  site/en/userGuide/tools/.DS_Store
  site/zh-CN/.DS_Store
  site/zh-CN/userGuide/.DS_Store
  site/zh-CN/userGuide/tools/.DS_Store
  site/zh-CN/userGuide/tools/cli_commands.md
  site/zh-CN/userGuide/tools/cli_overview.md
  site/zh-CN/userGuide/tools/install_cli.md
Labels: size/XL

#1236 Fix sharding anchor
  site/en/userGuide/create_collection.md
  site/zh-CN/userGuide/create_collection.md
Labels: size/XS

#1237 add raises and returns for manage_connections.md
  site/en/userGuide/manage_connection.md
Labels: size/S

#1239 add returns and exceptions
  site/en/userGuide/check_collection.md
Labels: size/M

#1240 add connection limits
  site/en/userGuide/manage_connection.md
Labels: size/XS

#1243 add limits
  site/en/userGuide/create_collection.md
Labels: size/XS

#1244 add limits
  site/en/userGuide/collection_alias.md
Labels: size/XS

#1245 add limits
  site/en/userGuide/create_partition.md
Labels: size/XS

#1247 add limits
  site/en/userGuide/insert_data.md
Labels: size/XS

#1246 Update overview.md
  site/en/about/overview.md
Labels: size/XS

#1248 add limits
  site/en/userGuide/search/search.md
Labels: size/S

#1250 Update home.md
  site/zh-CN/home/home.md
Labels: size/XS

#1251 Fix Code in Insert
  site/en/userGuide/insert_data.md
  site/zh-CN/userGuide/insert_data.md
Labels: size/XS

#1252 global replace
  site/en/userGuide/build_index.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_index.md
  site/zh-CN/userGuide/build_index.md
  site/zh-CN/userGuide/delete_data.md
  site/zh-CN/userGuide/drop_index.md
Labels: size/S

#1253 Modify delete
  site/en/userGuide/delete_data.md
  site/zh-CN/userGuide/delete_data.md
Labels: size/L

#1254 Update time travel
  site/en/userGuide/search/timetravel.md
  site/zh-CN/userGuide/search/timetravel.md
Labels: size/L

#1255 Pre GA Release
  site/en/Variables.json
  site/en/release_notes.md
  site/zh-CN/Variables.json
  site/zh-CN/release_notes.md
Labels: size/L

#1256 PreGA update
  site/en/reference/sys_config/configuration_cluster-advanced.md
  site/en/reference/sys_config/configuration_standalone-advanced.md
  site/en/userGuide/collection_alias.md
  site/zh-CN/reference/sys_config/configuration_cluster-advanced.md
  site/zh-CN/reference/sys_config/configuration_standalone-advanced.md
  site/zh-CN/userGuide/collection_alias.md
Labels: size/M
