Repository milvus-io/milvus-docs, pull requests merged in 2021-09, with the labels that each got.

#694 replace blockquote with div
  site/en/userGuide/build.md
  site/en/userGuide/connect.md
  site/en/userGuide/create.md
  site/en/userGuide/delete.md
  site/en/userGuide/insert.md
  site/en/userGuide/query.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/search.md
Labels: size/M

#698 Fixed the broken link in boolean.md
  site/en/reference/boolean.md
  site/zh-CN/Variables.json
Labels: size/XS

#702 V1.1.1 fix broken image
  site/en/reference/monitor/monitor.md
  site/zh-CN/reference/monitor/monitor.md
Labels: size/XS

#703 fix broken image link
  site/en/reference/monitor/monitor.md
  site/zh-CN/reference/monitor/monitor.md
Labels: size/XS

#704 fix broken image link
  site/en/reference/monitor/monitor.md
  site/zh-CN/reference/monitor/monitor.md
Labels: size/XS

#705 Fix 2.0 home
  site/en/home/home.json
  site/zh-CN/home/home.json
Labels: size/XS

#706 Home 1.0.0
  site/en/home/home.json
  site/zh-CN/home/home.json
Labels: size/XS

#707 1.1.0 home
  site/en/home/home.json
  site/zh-CN/home/home.json
Labels: size/XS

#708 1.1.1 home
  site/en/home/home.json
  site/zh-CN/home/home.json
Labels: size/S

#710 Fix grammar and spelling in CONTRIBUTING.md : Hacktoberfest
  CONTRIBUTING.md
Labels: hacktoberfest, doc-bug, size/S

#712 Fix blog link
  site/en/home/home.json
  site/zh-CN/home/home.json
Labels: size/XS

#717 Updated EN FAQ to close issue #716.
  site/en/faq/operational_faq.md
  site/en/fragments/faq_assign_gpu.md
  site/en/quick_start/install_milvus/milvus_docker-gpu.md
Labels: size/M

#718 Add a line break to overview.md
  site/en/about/overview.md
Labels: size/XS

#719 Updated 1.1.0 EN Faq to close issue #716
  site/en/faq/operational_faq.md
  site/en/fragments/faq_assign_gpu.md
  site/en/quick_start/install_milvus/milvus_docker-gpu.md
Labels: size/S

#720 Udpated 1.0.0 EN FAQ to close issue #716
  site/en/faq/operational_faq.md
  site/en/fragments/faq_assign_gpu.md
  site/en/quick_start/install_milvus/milvus_docker-gpu.md
Labels: size/S

#721 add faq_assign_gpu_zh_v1.1.1
  site/zh-CN/faq/operational_faq.md
  site/zh-CN/fragments/faq_assign_gpu.md
  site/zh-CN/quick_start/install_milvus/milvus_docker-gpu.md
Labels: size/M

#722 Fix placeholder
  site/en/home/home.json
  site/zh-CN/home/home.json
Labels: size/XS

#723 add faq_assign_gpu_zh_v1.0.0
  site/zh-CN/faq/operational_faq.md
  site/zh-CN/fragments/faq_assign_gpu.md
  site/zh-CN/quick_start/install_milvus/milvus_docker-gpu.md
Labels: size/M

#724 Added note in creating index.
  site/en/quick_start/get_started/create_drop_index_python.md
  site/zh-CN/quick_start/get_started/create_drop_index_python.md
Labels: size/XS

#725 Added note to index building in 1.0.0
  site/en/quick_start/get_started/create_drop_index_python.md
  site/zh-CN/quick_start/get_started/create_drop_index_python.md
Labels: size/XS

#726 Added note to index building in v1.1.0.
  site/en/quick_start/get_started/create_drop_index_python.md
  site/zh-CN/quick_start/get_started/create_drop_index_python.md
Labels: size/XS

#732 Fixed broken link in boolean.md to close issue #689
  site/en/reference/boolean.md
Labels: size/XS

#733 Debold table head
  CONTRIBUTING.md
  site/en/about/limitations.md
  site/en/about/milvus_adopters.md
  site/en/about/roadmap.md
  site/en/getstarted/develop_macos.md
  site/en/getstarted/prerequisite-docker.md
  site/en/release_notes.md
  site/zh-CN/about/limitations.md
  site/zh-CN/about/milvus_adopters.md
  site/zh-CN/about/roadmap.md
  site/zh-CN/getstarted/install_macos.md
  site/zh-CN/getstarted/prerequisite-docker.md
  site/zh-CN/release_notes.md
Labels: size/M
