Repository milvus-io/milvus-docs, pull requests merged in 2022-08, with the labels that each got.

#1685 Remove autoscaling from scaleout.md
  site/en/adminGuide/scaleout.md
Labels: size/S

#1684 update milvus cli docs
  site/en/userGuide/tools/cli_commands.md
  site/en/userGuide/tools/cli_overview.md
Labels: size/L

#1686 Remove migrate docs
  site/en/menuStructure/en.json
  site/en/migrate/migrate_overview.md
Labels: size/M

#1687 Remove migrate docs in 2.0.x
  site/en/menuStructure/en.json
  site/en/migrate/migrate_overview.md
Labels: size/M

#1688 updated tls.md
  site/en/adminGuide/tls.md
Labels: size/S

#1690 Added string expression to boolean.md
  site/en/reference/boolean.md
Labels: size/M

#1691 Minor grammatical fix.
  site/en/userGuide/create_collection.md
Labels: size/XS

#1692 Revert the revert to metrics dashboard.md
  site/en/adminGuide/monitor/metrics_dashboard.md
Labels: size/L

#1693 Revert the revert to index.md
  site/en/reference/index.md
Labels: size/M

#1694 Revert the revert to example code node.md
  site/en/getstarted/example_code_node.md
Labels: size/XS

#1695 recover pr # 1572 curl commands
  site/en/fragments/multiple_code.md
  site/en/userGuide/build_index.md
  site/en/userGuide/calculate_distance.md
  site/en/userGuide/check_collection.md
  site/en/userGuide/check_partition.md
  site/en/userGuide/collection_alias.md
  site/en/userGuide/compact_data.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/create_partition.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_collection.md
  site/en/userGuide/drop_index.md
  site/en/userGuide/drop_partition.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/load_partition.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/release_collection.md
  site/en/userGuide/release_partition.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/search/timetravel.md
Labels: size/XXL

#1689 Update load_collection.md
  site/en/userGuide/load_collection.md
Labels: size/XS

#1697 updated outputs in RESTful API docs
  site/en/userGuide/drop_collection.md
Labels: doc-improvement, size/XS

#1698 updated the outputs in RESTful API
  site/en/userGuide/calculate_distance.md
  site/en/userGuide/check_collection.md
  site/en/userGuide/check_partition.md
  site/en/userGuide/collection_alias.md
  site/en/userGuide/compact_data.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/release_collection.md
Labels: doc-improvement

#1700 updated compact_data.md
  site/en/userGuide/compact_data.md
Labels: size/S

#1701 updated compact_data.md
  site/en/userGuide/compact_data.md
Labels: size/S

#1702 changed the outputs in REST API docs to json format
  site/en/userGuide/calculate_distance.md
  site/en/userGuide/check_collection.md
  site/en/userGuide/compact_data.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_collection.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/release_collection.md
Labels: size/L

#1704 updated code in milvusoperator.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: doc-improvement, size/S

#1706 updated code in milvusoperator.md in 2.0.x
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: doc-improvement, size/S

#1711 Update configure-docker.md
  site/en/adminGuide/configure-docker.md
Labels: size/XS

#1715 updated milvusoperator.md in 2.1.x
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#1717 fix check links
  check-link.js
Labels: size/XS

#1712 Update configure_operator.md
  site/en/adminGuide/configure_operator.md
Labels: size/XS

#1714 Update the what's next section in configure Milvus dependencies
  site/en/adminGuide/deploy_etcd.md
  site/en/adminGuide/deploy_pulsar.md
  site/en/adminGuide/deploy_s3.md
  site/en/adminGuide/message_storage_operator.md
  site/en/adminGuide/meta_storage_operator.md
  site/en/adminGuide/object_storage_operator.md
Labels: size/M

#1718 fixed a link in 2.1.x
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#1719 fixed a link in 2.0.x
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#1720 updated install_standalone-helm.md in 2.0.x
  site/en/getstarted/standalone/install_standalone-helm.md
Labels: size/S

#1723 Updated the prerequisites of Pymilvus installation.
  site/en/getstarted/install_SDKs/install-pymilvus.md
Labels: size/XS

#1724 Update install Milvus
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/standalone/install_standalone-docker.md
Labels: size/M

#1725 changed REST API tab name to curl
  site/en/fragments/multiple_code.md
Labels: doc-improvement, size/XS

#1726 Update parameter name
  site/en/userGuide/create_collection.md
Labels: doc-bug

#1727 Update the deployment of Milvus cluster in EC2.
  site/en/adminGuide/clouds/aws/aws.md
Labels: size/L

#1729 Minor fix
  site/en/adminGuide/monitor/metrics_dashboard.md
Labels: size/XS

#1728 updated What's new in docs in 2.1.x
  site/en/adminGuide/message_storage_operator.md
  site/en/home/home.md
Labels: size/S

#1731 Added enabling authentication using Helm.
  site/en/adminGuide/authenticate.md
Labels: size/M

#1732 added 2.1 benchmark test.
  assets/2.1_qps.png
  assets/2.1_rt.png
  site/en/menuStructure/en.json
  site/en/reference/benchmark.md
Labels: size/XXL

#1733 Update what's new in docs.
  site/en/home/home.md
Labels: size/XS

#1734 Fix broken images.
  site/en/reference/benchmark.md
Labels: size/XS

#1735 Added embedded Milvus in release notes
  site/en/release_notes.md
Labels: size/XS

#1736 Update install_embedded_milvus.md
  site/en/getstarted/install_embedded_milvus.md
Labels: size/XS

#1737 Updated what's new in docs
  site/en/home/home.md
Labels: size/XS

#1738 Update Embedded Milvus document
  site/en/getstarted/install_embedded_milvus.md
Labels: size/L

#1740 2.1.1 release notes
  site/en/Variables.json
  site/en/home/home.md
  site/en/release_notes.md
Labels: size/M

#1741 Fix typo in NodeJS Insert Documentation
  site/en/userGuide/insert_data.md
Labels: size/XS

#1742 Minor fix to capitalization
  site/en/release_notes.md
Labels: size/XS

#1743 Update install_embedded_milvus.md
  site/en/getstarted/install_embedded_milvus.md
Labels: size/M

#1744 Minor fix
  site/en/getstarted/install_embedded_milvus.md
Labels: size/XS

#1746 Update hello Milvus with 2.1.1 version.
  site/en/getstarted/example_code.md
Labels: size/XS

#1745 Fix embedded Milvus folder name
  site/en/getstarted/install_embedded_milvus.md
Labels: size/XS

#1747 Update pyMilvus version in hello milvus
  site/en/getstarted/example_code.md
Labels: size/XS

#1748 Update install_embedded_milvus.md
  site/en/getstarted/install_embedded_milvus.md
Labels: size/XS

#1749 Update the recommended reads on docs homepage.
  site/en/home/home.md
Labels: size/XS

#1750 Adjust the menu structure.
  site/en/menuStructure/en.json
Labels: size/XS

#1751 updated Manage Milvus Connection
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/userGuide/manage_connection.md
Labels: doc-improvement, size/S

#1752 Update install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/userGuide/manage_connection.md
Labels: doc-improvement, size/S

#1753 Added the example output of get replica info.
  site/en/userGuide/load_collection.md
Labels: size/XS

#1754 Update benchmark.md
  site/en/reference/benchmark.md
Labels: size/XS

#1755 Remove unsupported index types
  site/en/reference/index.md
Labels: size/M

#1756 Update the code in create a collection.
  site/en/userGuide/create_collection.md
Labels: size/XS

#1757 Optimize index reference.
  site/en/reference/index.md
Labels: size/M

#1758 Fix the layout of tabs and tables in index.md
  site/en/reference/index.md
Labels: size/S

#1759 Uploaded images for consistency.md
  assets/Consistency-Bounded.png
  assets/Consistency-Eventual.png
  assets/Consistency-Session.png
  assets/Consistency-Strong.png
Labels: size/XS

#1761 Delete Consistency-Bounded.png
  assets/Consistency_Bounded.png
  assets/Consistency_Eventual.png
  assets/Consistency_Session.png
  assets/Consistency_Strong.png
Labels: size/XS

#1762 Update consistency.md
  site/en/menuStructure/en.json
  site/en/reference/consistency.md
Labels: size/S

#1763 Update create_collection.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
Labels: size/XS

#1764 Update consistency.md
  site/en/reference/consistency.md
Labels: size/XS

#1765 Update instructions on tuning consistency level
  site/en/userGuide/create_collection.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
Labels: size/XS

#1767 Update replica.md
  assets/replica_availability.jpg
  assets/replica_group.png
  site/en/menuStructure/en.json
  site/en/reference/replica.md
Labels: size/L

#1766 Update image in performance.md
  assets/accuracy_nlist_nprobe.png
  assets/performance_nlist_nprobe.png
Labels: size/XS

#1768 Update replica.md
  site/en/reference/replica.md
Labels: size/XS

#1771 Update the Slack link in product_faq.md
  site/en/faq/product_faq.md
Labels: size/XS

#1773 Update consistency.md
  site/en/reference/consistency.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
Labels: size/S

#1772 Fix description of MatchOp
  site/en/reference/boolean.md
Labels: size/XS

#1774 Update Time Travel Reference
  site/en/reference/timetravel_ref.md
Labels: size/M

#1776 Update Java SDK version.
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/XS

#1777 Fix typo in benchmarks.
  site/en/reference/benchmark.md
Labels: size/XS

#1778 Fix missing link in time travel reference
  site/en/reference/timetravel_ref.md
Labels: size/XS

#1779 Minor fix
  site/en/reference/architecture/main_components.md
Labels: size/XS

#1780 Added Java SDK in About Milvus doc.
  site/en/about/overview.md
Labels: size/XS

#1781 Minor fix to release notes
  site/en/release_notes.md
Labels: size/XS
