Repository milvus-io/milvus-docs, pull requests merged in 2022-11, with the labels that each got.

#1827 docs: typo fixed
  site/en/adminGuide/deploy_pulsar.md
Labels: size/XS

#1588 Update create_collection.md
  site/zh-CN/userGuide/create_collection.md
Labels: size/L

#1828 Fix broken links in 2.1.x docs
  site/en/adminGuide/deploy_etcd.md
  site/en/adminGuide/deploy_pulsar.md
  site/en/adminGuide/deploy_s3.md
  site/en/adminGuide/message_storage_operator.md
  site/en/adminGuide/meta_storage_operator.md
  site/en/adminGuide/object_storage_operator.md
  site/en/fragments/api_reference.md
  site/en/getstarted/install_SDKs/install-java.md
  site/en/reference/benchmark.md
Labels: size/S

#1830 resolve issues reported in 20543
  site/en/getstarted/cluster/install_cluster-ansible.md
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/menuStructure/en.json
  site/en/reference/schema.md
Labels: size/S

#1833 Update eks.md
  site/en/adminGuide/clouds/aws/eks.md
Labels: size/M

#1832 [WIP] Add 2.2 docs for new features
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/en/adminGuide/configure_operator.md
  site/en/adminGuide/monitor/metrics_dashboard.md
  site/en/adminGuide/upgrade_milvus_cluster.md
  site/en/adminGuide/upgrade_milvus_embedded.md
  site/en/adminGuide/upgrade_milvus_standalone.md
  site/en/faq/product_faq.md
  site/en/getstarted/cluster/install_cluster-ansible.md
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/menuStructure/en.json
  site/en/reference/disk_index.md
  site/en/reference/index.md
  site/en/reference/schema.md
  site/en/reference/sys_config/configure_quota_limits.md
  site/en/reference/sys_config/system_configuration.md
  site/en/userGuide/build_index.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
Labels: size/XXL, do-not-merge/work-in-progress

#1831 [Do not merge] 2.2 new docs _ Angela
  assets/users_and_roles.png
  site/en/adminGuide/clouds/aws/eks.md
  site/en/adminGuide/rbac.md
  site/en/reference/sys_config/configure_rootcoord.md
  site/en/reference/users_and_roles.md
  site/en/release_notes.md
  site/en/userGuide/bulk_load.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/modify_collection.md
Labels: size/XL

#1839 minor fix
  site/en/getstarted/example_code.md
  site/en/release_notes.md
Labels: size/XS

#1840 Update index.md
  site/en/reference/index.md
Labels: size/XS

#1841 Adjust upgrade structure
  site/en/menuStructure/en.json
Labels: size/S

#1842 Change rpm and deb package version variables
  site/en/Variables.json
Labels: size/XS

#1844 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1845 Fix broken links in Milvus 2.2 docs
  site/en/about/milvus_adopters.md
  site/en/adminGuide/clouds/azure.md
Labels: size/XS

#1846 Fix broken links in Milvus 2.1 docs
  site/en/about/milvus_adopters.md
  site/en/adminGuide/clouds/azure.md
Labels: size/XS

#1847 Fix broken links in Milvus 2.0.x docs
  site/en/about/milvus_adopters.md
  site/en/adminGuide/clouds/azure.md
  site/en/adminGuide/operator.md
Labels: size/XS

#1843 Update migrate guide
  site/en/adminGuide/upgrade_milvus_cluster.md
  site/en/adminGuide/upgrade_milvus_standalone.md
Labels: size/L

#1849 Update the upgrade guide
  site/en/adminGuide/upgrade_milvus_cluster.md
  site/en/adminGuide/upgrade_milvus_standalone.md
  site/en/menuStructure/en.json
Labels: size/L

#1848 Fix broken links in Milvus 2.0.0 docs
  site/en/about/milvus_adopters.md
  site/en/adminGuide/clouds/aws/aws.md
  site/en/adminGuide/clouds/azure.md
  site/en/adminGuide/operator.md
  site/en/faq/operational_faq.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/tutorials/image_similarity_search.md
Labels: size/S

#1851 Add docker compose upgrade guide and reorganize the structure
  site/en/adminGuide/upgrade_milvus_cluster-docker.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-docker.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/home/home.md
  site/en/menuStructure/en.json
  site/en/release_notes.md
Labels: size/L

#1852 Added upgrade guide using Milvus Operator
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/menuStructure/en.json
Labels: size/M

#1854 minor fix to upgrade_milvus_cluster-docker.md
  site/en/adminGuide/upgrade_milvus_cluster-docker.md
Labels: size/XS

#1855 Fix broken links in Milvus 1.1.0 docs
  site/en/contribute/milvus_community_charters.md
  site/en/developerTools/dt_overview.md
  site/en/faq/product_faq.md
  site/en/fragments/faq_install_from_source.md
  site/en/quick_start/install_milvus/milvus_docker-cpu.md
  site/en/quick_start/install_milvus/milvus_docker-gpu.md
  site/en/release_notes.md
Labels: size/S

#1857 Added the link to the migration script
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
Labels: size/XS

#1856 Fix broken links in 1.0.0
  site/en/contribute/milvus_community_charters.md
  site/en/developerTools/dt_overview.md
  site/en/faq/product_faq.md
  site/en/fragments/faq_install_from_source.md
  site/en/release_notes.md
Labels: size/S

#1853 Fix broken links in master
  site/en/about/milvus_adopters.md
Labels: size/XS

#1858 Fix broken links in 2.2 docs
  site/en/adminGuide/deploy_etcd.md
  site/en/adminGuide/deploy_pulsar.md
  site/en/adminGuide/deploy_s3.md
  site/en/adminGuide/message_storage_operator.md
  site/en/adminGuide/meta_storage_operator.md
  site/en/adminGuide/object_storage_operator.md
  site/en/fragments/api_reference.md
  site/en/getstarted/install_SDKs/install-java.md
  site/en/reference/benchmark.md
  site/en/reference/disk_index.md
Labels: size/S

#1859 Update install-java.md
  site/en/getstarted/install_SDKs/install-java.md
Labels: size/XS

#1861 Minor fix to the order list in eks.md
  site/en/adminGuide/clouds/aws/eks.md
Labels: size/XS

#1862 Update eks.md
  site/en/adminGuide/clouds/aws/eks.md
Labels: size/XS

#1863 Added one step to Milvus Operator upgrade guide
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
Labels: size/S

#1864 Update attu_install-helm.md
  site/en/userGuide/tools/attu_install-helm.md
Labels: size/XS

#1865 Update bulk_load.md
  site/en/userGuide/bulk_load.md
Labels: size/XS

#1866 Update the download link of Attu macOS package
  site/en/userGuide/tools/attu_install-package.md
Labels: size/XS

#1867 Fix broken images in 2.2.x bitset.md
  site/en/reference/bitset.md
Labels: size/XS

#1868 Fix broken image in 2.1.x bitset.md
  site/en/reference/bitset.md
Labels: size/XS

#1869 Fix broken images in 2.0.0 performance FAQ
  site/en/faq/performance_faq.md
Labels: size/XS

#1870 Update Variables.json
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/XS

#1871 Adjust the note format in installation guide.
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#1872 Rectify the error reported in issue #20777
  site/en/userGuide/build_index.md
Labels: size/S

#1873 Change meta migration image tag
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
Labels: size/XS

#1874 Fix broken links in 2.2.x docs_1124
  site/en/adminGuide/clouds/aws/aws.md
  site/en/adminGuide/clouds/aws/eks.md
  site/en/adminGuide/clouds/azure.md
  site/en/adminGuide/clouds/gcp.md
  site/en/reference/bitset.md
Labels: size/M

#1875 Fix 2.1.x broken links
  site/en/adminGuide/clouds/aws/aws.md
  site/en/adminGuide/clouds/aws/eks.md
  site/en/adminGuide/clouds/gcp.md
  site/en/reference/bitset.md
Labels: size/S

#1876 Fix broken links in 2.0.x docs
  site/en/about/overview.md
  site/en/adminGuide/clouds/aws/aws.md
  site/en/adminGuide/clouds/aws/eks.md
  site/en/adminGuide/clouds/azure.md
  site/en/adminGuide/clouds/gcp.md
  site/en/adminGuide/deploy_s3.md
Labels: size/M

#1877 Create 1.1.1 branch
  site/en/Variables.json
Labels: size/S

#1879 rectify the offset setting in the pymilvus example
  site/en/userGuide/search/search.md
Labels: size/XS

#1881 Update upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
Labels: size/XS

#1882 Update links in example applications
  site/en/tutorials/audio_similarity_search.md
  site/en/tutorials/dna_sequence_classification.md
  site/en/tutorials/image_similarity_search.md
  site/en/tutorials/molecular_similarity_search.md
  site/en/tutorials/question_answering_system.md
  site/en/tutorials/recommendation_system.md
  site/en/tutorials/text_search_engine.md
  site/en/tutorials/video_similarity_search.md
Labels: size/M

#1884 Fix the max ShardsNum
  site/en/userGuide/create_collection.md
Labels: size/XS
