Repository milvus-io/milvus-docs, pull requests merged in 2022-02, with the labels that each got.

#1340 Fix home.md
  site/en/home/home.md
Labels: size/XS

#1343 Supplement Index and Minor Fixes
  site/en/reference/index/index_selection.md
  site/en/reference/metric.md
  site/en/reference/sys_config/configure_common.md
  site/en/reference/sys_config/configure_datacoord.md
  site/en/reference/sys_config/configure_datanode.md
  site/en/reference/sys_config/configure_etcd.md
  site/en/reference/sys_config/configure_indexcoord.md
  site/en/reference/sys_config/configure_indexnode.md
  site/en/reference/sys_config/configure_knowhere.md
  site/en/reference/sys_config/configure_localstorage.md
  site/en/reference/sys_config/configure_log.md
  site/en/reference/sys_config/configure_messagechannel.md
  site/en/reference/sys_config/configure_minio.md
  site/en/reference/sys_config/configure_proxy.md
  site/en/reference/sys_config/configure_pulsar.md
  site/en/reference/sys_config/configure_querycoord.md
  site/en/reference/sys_config/configure_querynode.md
  site/en/reference/sys_config/configure_rocksmq.md
  site/en/reference/sys_config/configure_rootcoord.md
  site/en/reference/sys_config/system_configuration.md
  site/zh-CN/reference/index/index_selection.md
  site/zh-CN/reference/metric.md
  site/zh-CN/reference/sys_config/configure_common.md
  site/zh-CN/reference/sys_config/configure_datacoord.md
  site/zh-CN/reference/sys_config/configure_datanode.md
  site/zh-CN/reference/sys_config/configure_etcd.md
  site/zh-CN/reference/sys_config/configure_indexcoord.md
  site/zh-CN/reference/sys_config/configure_indexnode.md
  site/zh-CN/reference/sys_config/configure_knowhere.md
  site/zh-CN/reference/sys_config/configure_localstorage.md
  site/zh-CN/reference/sys_config/configure_log.md
  site/zh-CN/reference/sys_config/configure_messagechannel.md
  site/zh-CN/reference/sys_config/configure_minio.md
  site/zh-CN/reference/sys_config/configure_proxy.md
  site/zh-CN/reference/sys_config/configure_pulsar.md
  site/zh-CN/reference/sys_config/configure_querycoord.md
  site/zh-CN/reference/sys_config/configure_querynode.md
  site/zh-CN/reference/sys_config/configure_rocksmq.md
  site/zh-CN/reference/sys_config/configure_rootcoord.md
  site/zh-CN/reference/sys_config/system_configuration.md
Labels: size/L

#1344 Add version info in Hello Milvus
  site/en/getstarted/example_code.md
  site/zh-CN/getstarted/example_code.md
Labels: size/XS

#1345 Add Compaction and LoadBalance
  site/en/menuStructure/en.json
  site/en/userGuide/compact_data.md
  site/en/userGuide/load_balance.md
  site/zh-CN/menuStructure/cn.json
  site/zh-CN/userGuide/compact_data.md
  site/zh-CN/userGuide/load_balance.md
Labels: size/XL

#1346 Fix CLI Param Table Invisible
  site/en/userGuide/build_index.md
  site/en/userGuide/check_collection.md
  site/en/userGuide/check_partition.md
  site/en/userGuide/collection_alias.md
  site/en/userGuide/compact_data.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/create_partition.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_collection.md
  site/en/userGuide/drop_index.md
  site/en/userGuide/drop_partition.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_balance.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/release_collection.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/zh-CN/userGuide/build_index.md
  site/zh-CN/userGuide/check_collection.md
  site/zh-CN/userGuide/check_partition.md
  site/zh-CN/userGuide/collection_alias.md
  site/zh-CN/userGuide/compact_data.md
  site/zh-CN/userGuide/create_collection.md
  site/zh-CN/userGuide/create_partition.md
  site/zh-CN/userGuide/delete_data.md
  site/zh-CN/userGuide/drop_collection.md
  site/zh-CN/userGuide/drop_index.md
  site/zh-CN/userGuide/drop_partition.md
  site/zh-CN/userGuide/insert_data.md
  site/zh-CN/userGuide/load_balance.md
  site/zh-CN/userGuide/load_collection.md
  site/zh-CN/userGuide/manage_connection.md
  site/zh-CN/userGuide/release_collection.md
  site/zh-CN/userGuide/search/hybridsearch.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
Labels: size/M

#1347 Add Query in GO
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
Labels: size/M

#1348 Fix Load Threshold
  site/en/userGuide/load_collection.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/zh-CN/userGuide/load_collection.md
  site/zh-CN/userGuide/search/hybridsearch.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
Labels: size/M

#1350 Minor Fix
  site/en/reference/sys_config/configure_datacoord.md
  site/en/reference/sys_config/configure_log.md
  site/zh-CN/reference/sys_config/configure_datacoord.md
  site/zh-CN/reference/sys_config/configure_log.md
Labels: size/S

#1335 Make stop and delete commands into code blocks
  site/en/getstarted/standalone/install_standalone-docker.md
Labels: size/S

#1329 Update milvus_adopters.md
  site/zh-CN/about/milvus_adopters.md
Labels: size/XS

#1339 translate tutorials directory to CN
  site/zh-CN/tutorials/audio_similarity_search.md
  site/zh-CN/tutorials/image_similarity_search.md
  site/zh-CN/tutorials/molecular_similarity_search.md
  site/zh-CN/tutorials/question_answering_system.md
  site/zh-CN/tutorials/recommendation_system.md
  site/zh-CN/tutorials/text_search_engine.md
  site/zh-CN/tutorials/video_similarity_search.md
Labels: translation, size/L

#1351 Update operational_faq.md
  site/en/faq/operational_faq.md
  site/zh-CN/faq/operational_faq.md
Labels: size/XS

#1354 fix duplicate order
  site/en/menuStructure/en.json
Labels: size/XS

#1353 Add Java Table in Load Balance
  site/en/userGuide/load_balance.md
  site/zh-CN/userGuide/load_balance.md
Labels: size/M

#1349 Update example_code.md
  site/zh-CN/getstarted/example_code.md
Labels: translation, size/M

#1306 Update manage_connection.md
  site/zh-CN/userGuide/manage_connection.md
Labels: translation, size/L

#1358 Update manage_connection.md
  site/zh-CN/userGuide/manage_connection.md
Labels: size/S

#1359 Minor fix
  site/en/reference/index/index.md
  site/zh-CN/reference/index/index.md
Labels: size/XS

#1360 Update overview.md
  site/zh-CN/about/overview.md
Labels: size/XS

#1361 Update Readme and Contributing
  CONTRIBUTING.md
  README.md
Labels: size/M

#1363 Revise Index
  site/en/about/overview.md
  site/en/faq/product_faq.md
  site/en/home/home.md
  site/en/menuStructure/en.json
  site/en/reference/glossary.md
  site/en/reference/index.md
  site/en/reference/index/index.md
  site/en/userGuide/build_index.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/search.md
  site/zh-CN/about/overview.md
  site/zh-CN/faq/product_faq.md
  site/zh-CN/home/home.md
  site/zh-CN/menuStructure/cn.json
  site/zh-CN/reference/index.md
  site/zh-CN/reference/index/index.md
  site/zh-CN/userGuide/build_index.md
  site/zh-CN/userGuide/search/hybridsearch.md
  site/zh-CN/userGuide/search/search.md
Labels: size/L

#1364 Revise attu helm
  site/en/userGuide/tools/attu_install-helm.md
  site/zh-CN/userGuide/tools/attu_install-helm.md
Labels: size/M

#1365 Minor Fix
  site/zh-CN/userGuide/tools/attu_install-helm.md
Labels: size/XS

#1366 Update home
  site/en/home/home.md
  site/zh-CN/home/home.md
Labels: size/M

#1367 Update install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/zh-CN/getstarted/cluster/install_cluster-helm.md
Labels: size/XS

#1371 Update drop_index.md
  site/zh-CN/userGuide/drop_index.md
Labels: size/M

#1373 Update attu_install-package.md
  site/zh-CN/userGuide/tools/attu_install-package.md
Labels: size/XS

#1375 Upgrade Configure Milvus
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/zh-CN/adminGuide/configure-docker.md
  site/zh-CN/adminGuide/configure-helm.md
Labels: size/L

#1376 Update check_collection.md
  site/en/userGuide/check_collection.md
Labels: size/M

#1374 Update attu_install-package.md
  site/en/userGuide/tools/attu_install-package.md
Labels: size/XS

#1379 Fixes typo in Milvus Introduction (overview.md)
  site/en/about/overview.md
Labels: size/XS

#1382 Add Setting Consistency Level
  site/en/userGuide/create_collection.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/zh-CN/userGuide/create_collection.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
Labels: size/M

#1383 Minor Fix
  site/en/userGuide/create_collection.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/zh-CN/userGuide/create_collection.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
Labels: size/S

#1384 Reconfirm Download Paths
  site/en/getstarted/example_code.md
  site/en/getstarted/example_code_multi_lang/example_code_NL.md
  site/en/getstarted/example_code_multi_lang/example_code_bn.md
  site/en/getstarted/example_code_multi_lang/example_code_de.md
  site/en/getstarted/example_code_multi_lang/example_code_es.md
  site/en/getstarted/example_code_multi_lang/example_code_fr.md
  site/en/getstarted/example_code_multi_lang/example_code_id.md
  site/en/getstarted/example_code_multi_lang/example_code_it.md
  site/en/userGuide/create_collection.md
  site/zh-CN/getstarted/example_code.md
  site/zh-CN/userGuide/create_collection.md
Labels: size/M

#1385 format code for user guide
  site/en/userGuide/build_index.md
  site/en/userGuide/check_collection.md
  site/en/userGuide/check_partition.md
  site/en/userGuide/collection_alias.md
  site/en/userGuide/compact_data.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/create_partition.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_collection.md
  site/en/userGuide/drop_index.md
  site/en/userGuide/drop_partition.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_balance.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/load_partition.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/release_collection.md
  site/en/userGuide/release_partition.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/search/timetravel.md
Labels: size/XL

#1377 Update search.md
  site/zh-CN/userGuide/search/search.md
Labels: size/L

#1387 Update comparison.md
  site/zh-CN/about/comparison.md
Labels: size/XS

#1388 2.0.1 Release
  site/en/Variables.json
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/release_notes.md
  site/zh-CN/Variables.json
  site/zh-CN/getstarted/standalone/install_standalone-aptyum.md
  site/zh-CN/release_notes.md
Labels: size/L

#1390 Update comparison.md
  site/en/about/comparison.md
Labels: size/XS

#1391 Update comparison
  site/zh-CN/menuStructure/cn.json
Labels: size/XS

#1392 Update create_collection.md
  site/zh-CN/userGuide/create_collection.md
Labels: size/XS

#1380 Add binlog to glossary.
  site/en/reference/glossary.md
Labels: size/XS

#1393 Update load_balance.md
  site/zh-CN/userGuide/load_balance.md
Labels: size/L

#1394 Update version.json
  version.json
Labels: size/XS

#1396 Add details in Delete
  site/en/userGuide/delete_data.md
  site/zh-CN/userGuide/delete_data.md
Labels: size/S

#1397 Update install-pymilvus.md
  site/zh-CN/getstarted/install_SDKs/install-pymilvus.md
Labels: size/M

#1398 Update install-node.md
  site/zh-CN/getstarted/install_SDKs/install-node.md
Labels: size/M

#1399 Update install-go.md
  site/zh-CN/getstarted/install_SDKs/install-go.md
Labels: size/S

#1400 Update install-java.md
  site/zh-CN/getstarted/install_SDKs/install-java.md
Labels: size/M

#1405 Update glossary.md
  site/zh-CN/reference/glossary.md
Labels: size/XS
