Repository milvus-io/milvus-docs, pull requests merged in 2022-06, with the labels that each got.

#1507 [DO NOT MERGE] Release 2.1.x Doc
  site/en/about/comparison.md
  site/en/about/limitations.md
  site/en/adminGuide/authenticate.md
  site/en/faq/product_faq.md
  site/en/menuStructure/en.json
  site/en/reference/schema.md
  site/en/userGuide/build_index.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/import_data.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/load_partition.md
  site/template/conceptual-doc-template.md
  site/template/how-to-doc-template.md
  site/template/reference-doc-template.md
  site/template/tutorial-doc-template.md
  site/zh-CN/about/comparison.md
  site/zh-CN/about/limitations.md
  site/zh-CN/adminGuide/authenticate.md
  site/zh-CN/faq/product_faq.md
  site/zh-CN/menuStructure/cn.json
  site/zh-CN/reference/schema.md
  site/zh-CN/userGuide/build_index.md
  site/zh-CN/userGuide/create_collection.md
  site/zh-CN/userGuide/import_data.md
  site/zh-CN/userGuide/insert_data.md
  site/zh-CN/userGuide/load_collection.md
  site/zh-CN/userGuide/load_partition.md
Labels: size/XL

#1516 [DO NOT MERGE] Configure Milvus
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/deploy_etcd.md
  site/en/adminGuide/deploy_pulsar.md
  site/en/adminGuide/deploy_s3.md
  site/en/adminGuide/message_storage_operator.md
  site/en/adminGuide/meta_storage_operator.md
  site/en/adminGuide/monitor/visualize.md
  site/en/adminGuide/object_storage_operator.md
  site/en/adminGuide/operator.md
  site/en/faq/troubleshooting.md
  site/en/getstarted/cluster/install_cluster-ansible.md
  site/en/getstarted/install_embedded_milvus.md
  site/en/reference/replica.md
  site/en/userGuide/check_partition.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/create_partition.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/tune_consistency.md
  site/zh-CN/adminGuide/operator.md
  site/zh-CN/faq/troubleshooting.md
  site/zh-CN/userGuide/check_collection.md
Labels: size/XXL

#1540 Create metrics_dashboard.md
  site/en/adminGuide/monitor/metrics_dashboard.md
  site/en/menuStructure/en.json
Labels: size/L

#1543 Removes roadmap.md
  site/en/about/roadmap.md
  site/en/faq/performance_faq.md
  site/en/fragments/api_reference.md
  site/en/getstarted/install_SDKs/install-pymilvus.md
  site/zh-CN/about/roadmap.md
  site/zh-CN/fragments/api_reference.md
Labels: size/L

#1551 Remove bulk load doc from menu
  site/en/menuStructure/en.json
  site/zh-CN/menuStructure/cn.json
Labels: size/S

#1552 Update eks.md
  site/en/adminGuide/clouds/aws/eks.md
Labels: size/S

#1548 Reorganize monitor docs
  site/en/adminGuide/monitor/metrics_dashboard.md
  site/en/adminGuide/monitor/monitor_overview.md
Labels: size/M

#1553 Update eks.md
  site/en/adminGuide/clouds/aws/eks.md
Labels: size/S

#1556 Delete roadmap.md
  site/en/about/roadmap.md
Labels: size/L

#1558 Update install_cluster-ansible.md
  site/en/getstarted/cluster/install_cluster-ansible.md
Labels: size/XS

#1557 Add missing Helm value for GCP install guide
  site/en/adminGuide/clouds/gcp.md
Labels: size/XS

#1564 Fixed broken links in 2.0.x
  site/en/about/milvus_adopters.md
  site/en/adminGuide/clouds/aws/aws.md
  site/en/adminGuide/deploy_s3.md
  site/en/adminGuide/operator.md
  site/en/faq/operational_faq.md
  site/en/faq/troubleshooting.md
  site/en/fragments/api_reference.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/getstarted/install_SDKs/install-node.md
  site/en/reference/boolean.md
  site/en/tutorials/molecular_similarity_search.md
  site/en/tutorials/question_answering_system.md
  site/en/userGuide/tools/attu_install-package.md
Labels: doc-bug, size/M

#1565 Fixed broken links in 2.1.x
  site/en/about/milvus_adopters.md
  site/en/adminGuide/clouds/aws/aws.md
  site/en/adminGuide/deploy_s3.md
  site/en/adminGuide/operator.md
  site/en/faq/operational_faq.md
  site/en/faq/troubleshooting.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/getstarted/install_SDKs/install-node.md
  site/en/reference/boolean.md
  site/en/tutorials/molecular_similarity_search.md
  site/en/tutorials/question_answering_system.md
  site/en/userGuide/tools/attu_install-package.md
Labels: doc-bug, size/M

#1567 Delete comparison.md
  site/en/about/comparison.md
  site/en/menuStructure/en.json
Labels: size/L

#1569 Changes to consistency level format
  site/en/userGuide/create_collection.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/tune_consistency.md
Labels: size/S

#1570 Update create_collection.md
  site/en/release_notes.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
Labels: size/S

#1571 Add the best practice of tuning consistency
  site/en/userGuide/create_collection.md
Labels: size/XS

#1573 Update supported datatype for primary key field
  site/en/reference/schema.md
Labels: size/XS

#1575 About Milvus index page
  site/en/about/about_Milvus.md
  site/en/menuStructure/en.json
Labels: doc-improvement, size/M

#1576 issue#1574
  site/en/getstarted/cluster/install_cluster-docker.md
Labels: size/XS

#1577 Update install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-docker.md
Labels: size/XS

#1579 update Milvus index page
  site/en/menuStructure/en.json
Labels: size/S

#1582 Roll back menustructure
  site/en/menuStructure/en.json
Labels: size/S

#1583 Fix broken links
  site/en/adminGuide/deploy_s3.md
  site/en/faq/troubleshooting.md
  site/en/menuStructure/en.json
  site/en/reference/boolean.md
Labels: size/S
