Repository milvus-io/milvus-docs, pull requests merged in 2022-04, with the labels that each got.

#1470 Update configure-docker.md
  site/zh-CN/adminGuide/configure-docker.md
Labels: size/M

#1474 Update schema.md
  site/zh-CN/reference/schema.md
Labels: size/XS

#1476 Update glossary.md
  site/en/reference/glossary.md
Labels: size/S

#1479 Update search.md
  site/zh-CN/userGuide/search/search.md
Labels: size/XS

#1480 Update create_partition.md
  site/zh-CN/userGuide/create_partition.md
Labels: size/M

#1485 Add Install Cluster Ansible
  site/en/getstarted/cluster/install_cluster-ansible.md
  site/zh-CN/getstarted/cluster/install_cluster-ansible.md
Labels: size/XL, On hold

#1486 Minor Fix
  site/en/getstarted/cluster/install_cluster-ansible.md
  site/zh-CN/getstarted/cluster/install_cluster-ansible.md
Labels: size/XS

#1488 Update Node release
  site/en/Variables.json
  site/zh-CN/Variables.json
Labels: size/XS

#1490 What's new in doc
  site/en/home/home.md
  site/zh-CN/home/home.md
Labels: size/S

#1491 update vector index
  site/en/reference/index.md
Labels: size/M

#1495 Update offline
  site/en/getstarted/offline/install_offline-helm.md
  site/zh-CN/getstarted/offline/install_offline-helm.md
Labels: size/M
