Repository milvus-io/milvus-docs, pull requests merged in 2022-05, with the labels that each got.

#1499 Fix table display in check_collection.md
  site/zh-CN/userGuide/check_collection.md
Labels: size/XS

#1502 Fix code display error in create_collection.md
  site/zh-CN/userGuide/create_collection.md
Labels: size/XS

#1503 Fix go example code
  site/en/userGuide/check_collection.md
  site/zh-CN/userGuide/check_collection.md
Labels: size/XS

#1506 Delete broken API links
  site/en/userGuide/build_index.md
  site/en/userGuide/calculate_distance.md
  site/en/userGuide/check_collection.md
  site/en/userGuide/check_partition.md
  site/en/userGuide/collection_alias.md
  site/en/userGuide/compact_data.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/create_partition.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_collection.md
  site/en/userGuide/drop_index.md
  site/en/userGuide/drop_partition.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_balance.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/load_partition.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/release_collection.md
  site/en/userGuide/release_partition.md
Labels: size/M

#1510 Fix typo in title_create a partition
  site/en/userGuide/create_partition.md
Labels: size/XS

#1511 Add etcd issues to troubleshooting
  site/en/faq/troubleshooting.md
Labels: size/M

#1515 Fix broken links to Deploy Milvus Operator
  site/en/adminGuide/operator.md
  site/zh-CN/adminGuide/operator.md
Labels: size/XS

#1517 Update check_partition.md
  site/en/userGuide/check_partition.md
  site/zh-CN/userGuide/check_partition.md
Labels: size/XS

#1518 Fix broken API reference links
  site/en/fragments/api_reference.md
  site/en/getstarted/cluster/install_cluster-ansible.md
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/getstarted/install_SDKs/install-go.md
  site/en/getstarted/install_SDKs/install-java.md
  site/en/getstarted/install_SDKs/install-node.md
  site/en/getstarted/install_SDKs/install-pymilvus.md
  site/en/getstarted/offline/install_offline-docker.md
  site/en/getstarted/offline/install_offline-helm.md
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/reference/boolean.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/search/timetravel.md
  site/zh-CN/getstarted/cluster/install_cluster-ansible.md
  site/zh-CN/getstarted/standalone/install_standalone-aptyum.md
  site/zh-CN/userGuide/build_index.md
  site/zh-CN/userGuide/calculate_distance.md
Labels: size/L

#1521 Minor fix
  site/en/getstarted/cluster/install_cluster-ansible.md
Labels: size/XS

#1524 Update metric.md
  site/en/reference/metric.md
Labels: size/XS

#1525 Menu updates: removes dupe Attu overview page
  site/en/menuStructure/en.json
Labels: size/M

#1526 Corrects wrong link to schema.md
  site/en/userGuide/create_collection.md
Labels: size/XS

#1527 Update visualize.md
  site/en/adminGuide/monitor/visualize.md
Labels: size/XS

#1528 Update Milvus workflow diagram
  assets/milvus_workflow.jpeg
Labels: size/XS
