Repository milvus-io/milvus-docs, pull requests merged in 2022-12, with the labels that each got.

#1885 Added the example application of text to image search
  assets/text_to_image_workflow.png
  site/en/menuStructure/en.json
  site/en/tutorials/text_image_search.md
Labels: size/M

#1886 Added the tutorial of image deduplication system
  assets/image_deduplication.png
  site/en/menuStructure/en.json
  site/en/tutorials/image_deduplication_system.md
Labels: size/M

#1888 update deploy_pulsar with kafka configs
  site/en/adminGuide/deploy_pulsar.md
Labels: size/S

#1889 Rename bulk_load to bulk_insert
  site/en/home/home.md
  site/en/menuStructure/en.json
  site/en/release_notes.md
  site/en/userGuide/bulk_insert.md
Labels: size/XS

#1887 Update flush in hello_milvus
  site/en/getstarted/example_code.md
Labels: size/XS

#1891 [SEO] Fix duplicate meta description in 2.0.x docs
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/en/getstarted/prerequisite-docker.md
  site/en/getstarted/prerequisite-helm.md
  site/en/reference/sys_config/configure_knowhere.md
  site/en/userGuide/tools/attu_collection.md
  site/en/userGuide/tools/attu_data.md
  site/en/userGuide/tools/attu_faq.md
  site/en/userGuide/tools/attu_index.md
  site/en/userGuide/tools/attu_partition.md
  site/en/userGuide/tools/attu_query.md
  site/en/userGuide/tools/attu_search.md
  site/en/userGuide/tools/attu_system.md
Labels: size/S

#1893 [SEO] Rewrite Attu meta description in 2.2.x docs
  site/en/userGuide/tools/attu_collection.md
  site/en/userGuide/tools/attu_data.md
  site/en/userGuide/tools/attu_faq.md
  site/en/userGuide/tools/attu_index.md
  site/en/userGuide/tools/attu_partition.md
  site/en/userGuide/tools/attu_query.md
  site/en/userGuide/tools/attu_search.md
  site/en/userGuide/tools/attu_system.md
Labels: size/S

#1892 [SEO] Update Attu related meta description in 2.1.x.
  site/en/userGuide/tools/attu_collection.md
  site/en/userGuide/tools/attu_data.md
  site/en/userGuide/tools/attu_faq.md
  site/en/userGuide/tools/attu_index.md
  site/en/userGuide/tools/attu_partition.md
  site/en/userGuide/tools/attu_query.md
  site/en/userGuide/tools/attu_search.md
  site/en/userGuide/tools/attu_system.md
Labels: size/S

#1894 [SEO] Fix duplicate meta description in 1.1.1 docs
  site/en/about_milvus/milvus_distributions-cpu.md
  site/en/about_milvus/milvus_distributions-gpu.md
  site/en/quick_start/install_milvus/milvus_docker-cpu.md
  site/en/quick_start/install_milvus/milvus_docker-gpu.md
Labels: size/XS

#1895 [SEO] Fix duplicate meta description in 1.1.0 docs
  site/en/about_milvus/milvus_distributions-cpu.md
  site/en/about_milvus/milvus_distributions-gpu.md
  site/en/quick_start/install_milvus/milvus_docker-cpu.md
  site/en/quick_start/install_milvus/milvus_docker-gpu.md
Labels: size/XS

#1896 [SEO] Fix duplicate meta description in 1.0.0 docs
  site/en/about_milvus/milvus_distributions-cpu.md
  site/en/about_milvus/milvus_distributions-gpu.md
  site/en/quick_start/install_milvus/milvus_docker-cpu.md
  site/en/quick_start/install_milvus/milvus_docker-gpu.md
Labels: size/XS

#1897 [SEO] Fix duplicate meta description in 2.2.x docs
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/en/getstarted/prerequisite-docker.md
  site/en/getstarted/prerequisite-helm.md
  site/en/reference/sys_config/configure_knowhere.md
Labels: size/S

#1899 [SEO] Fix duplicate meta description of upgrade guides
  site/en/adminGuide/upgrade_milvus_cluster-docker.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-docker.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
Labels: size/S

#1900 [SEO] Rectify duplicate titles
  site/en/getstarted/prerequisites.md
Labels: size/XS

#1902 remove redundant
  site/en/adminGuide/configure-docker.md
Labels: size/XS

#1903 remove redundant
  site/en/adminGuide/configure-helm.md
Labels: size/XS

#1904 [SEO] Rectify duplicate titles
  site/en/getstarted/install-sdks.md
  site/en/getstarted/offline/install_offline-docker.md
  site/en/getstarted/prerequisite-docker.md
  site/en/getstarted/prerequisite-helm.md
  site/en/getstarted/prerequisites.md
  site/en/menuStructure/en.json
Labels: size/M

#1905 [SEO] rectify duplicate titles
  site/en/getstarted/prerequisite-docker.md
  site/en/getstarted/prerequisite-helm.md
  site/en/menuStructure/en.json
Labels: size/S

#1906 Update the benchmark
  assets/cluster_search_performance_210_vs_220.png
  assets/search_performance_by_querynode_cpu_cores.png
  assets/search_performance_by_querynode_replicas.png
  assets/standalone_search_performance_210_vs_220.png
  site/en/reference/benchmark.md
Labels: size/L

#1907 rectify some typos in benchmark
  site/en/getstarted/install_SDKs/install-go.md
  site/en/getstarted/install_SDKs/install-java.md
  site/en/getstarted/install_SDKs/install-node.md
  site/en/getstarted/offline/install_offline-docker.md
  site/en/getstarted/offline/install_offline-helm.md
  site/en/reference/benchmark.md
Labels: size/S

#1908 Fix broken links reported in issue #21018
  site/en/tutorials/text_search_engine.md
Labels: size/XS

#1909 Update bootcamp links in 2.1.x docs
  site/en/tutorials/audio_similarity_search.md
  site/en/tutorials/dna_sequence_classification.md
  site/en/tutorials/image_similarity_search.md
  site/en/tutorials/molecular_similarity_search.md
  site/en/tutorials/question_answering_system.md
  site/en/tutorials/recommendation_system.md
  site/en/tutorials/text_search_engine.md
  site/en/tutorials/video_similarity_search.md
Labels: size/M

#1911 [SEO] Rectify reported duplicate titles
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/en/getstarted/install_SDKs/install-go.md
  site/en/getstarted/install_SDKs/install-java.md
  site/en/getstarted/install_SDKs/install-node.md
  site/en/getstarted/install_SDKs/install-pymilvus.md
  site/en/getstarted/offline/install_offline-docker.md
  site/en/getstarted/offline/install_offline-helm.md
  site/en/getstarted/prerequisite-docker.md
  site/en/getstarted/prerequisite-helm.md
  site/en/menuStructure/en.json
Labels: size/L

#1912 Modify benchmark description
  site/en/reference/benchmark.md
Labels: size/XS

#1913 [SEO] Rectify reported duplicate titles
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/en/getstarted/install_SDKs/install-go.md
  site/en/getstarted/install_SDKs/install-java.md
  site/en/getstarted/install_SDKs/install-node.md
  site/en/getstarted/install_SDKs/install-pymilvus.md
  site/en/getstarted/offline/install_offline-docker.md
  site/en/getstarted/offline/install_offline-helm.md
  site/en/getstarted/prerequisite-docker.md
  site/en/getstarted/prerequisite-helm.md
  site/en/menuStructure/en.json
  site/en/userGuide/collection_alias.md
  site/en/userGuide/tools/attu_install-docker.md
  site/en/userGuide/tools/attu_install-helm.md
  site/en/userGuide/tools/attu_install-package.md
Labels: size/L

#1914 [SEO] Rectify reported duplicate titles
  site/en/about_milvus/milvus_distributions-cpu.md
  site/en/about_milvus/milvus_distributions-gpu.md
  site/en/about_milvus/milvus_distributions.md
  site/en/menuStructure/en.json
  site/en/quick_start/install_milvus/milvus_docker-cpu.md
  site/en/quick_start/install_milvus/milvus_docker-gpu.md
Labels: size/M

#1916 [SEO] Rectify duplicate titles
  site/en/about_milvus/milvus_distributions.md
  site/en/menuStructure/en.json
Labels: size/S

#1919 [SEO] Rectify reported duplicate titles
  site/en/about_milvus/milvus_distributions-cpu.md
  site/en/about_milvus/milvus_distributions-gpu.md
  site/en/about_milvus/milvus_distributions.md
  site/en/menuStructure/en.json
Labels: size/M

#1920 [SEO] Rectify duplicate titles
  site/en/about_milvus/milvus_distributions-cpu.md
  site/en/about_milvus/milvus_distributions-gpu.md
  site/en/about_milvus/milvus_distributions.md
  site/en/menuStructure/en.json
Labels: size/M

#1921 [SEO] Rectify duplicate titles
  site/en/about_milvus/milvus_distributions-cpu.md
  site/en/about_milvus/milvus_distributions-gpu.md
  site/en/about_milvus/milvus_distributions.md
  site/en/menuStructure/en.json
Labels: size/M

#1922 [SEO] Rectify duplicate titles
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/en/adminGuide/configure_operator.md
Labels: size/XS

#1923 [SEO] Rectify duplicate titles
  site/en/menuStructure/en.json
Labels: size/XS

#1924 [SEO] Rectify duplicate titles
  site/en/menuStructure/en.json
Labels: size/XS

#1925 [SEO] Rectify duplicate titles
  site/en/menuStructure/en.json
Labels: size/XS

#1927 Update create_collection.md
  site/en/userGuide/create_collection.md
Labels: size/XS

#1929 Update search.md
  site/en/userGuide/search/search.md
Labels: size/XS

#1930 Update create_collection.md
  site/en/userGuide/create_collection.md
Labels: size/XS

#1931 Update index.md
  site/en/reference/index.md
Labels: size/S

#1928 Update install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-helm.md
Labels: size/XS

#1932 Rearrange tab order of standalone installation and remove APT/YUM
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/menuStructure/en.json
Labels: size/L

#1933 Fix link in notes in install Cluster with operator
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#1934 Create install_standalone-operator.md
  site/en/getstarted/standalone/install_standalone-operator.md
Labels: size/L

#1935 Rearrange tab order
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-operator.md
Labels: size/XS

#1936 Rectify new tab name
  site/en/getstarted/standalone/install_standalone-operator.md
Labels: size/XS

#1937 V2.2.x anthony
  site/en/release_notes.md
Labels: size/M

#1938 Add release notes for Milvus 2.2.1
  site/en/release_notes.md
Labels: size/XS

#1939 Add release notes for Milvus 2.2.1
  site/en/Variables.json
Labels: size/S

#1940 Update install_standalone-operator.md
  site/en/getstarted/standalone/install_standalone-operator.md
Labels: size/S

#1941 Add release notes for Milvus 2.2.1
  site/en/release_notes.md
Labels: size/XS

#1942 Update pymilvus version
  site/en/getstarted/example_code.md
  site/en/release_notes.md
Labels: size/XS

#1943 Update pymilvus version
  site/en/getstarted/example_code.md
Labels: size/XS

#1944 Update limitations.md
  site/en/about/limitations.md
Labels: size/XS

#1945 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1946 update search and query example code
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
Labels: size/XS

#1947 Add release notes for milvus v2.2.2
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/S

#1949 Update install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-helm.md
Labels: size/XS

#1950 V2.2.x
  site/en/Variables.json
Labels: size/XS

#1951 update the milvus version in variables
  site/en/Variables.json
Labels: size/XS

#1953 Update Variables.json
  site/en/Variables.json
Labels: size/XS

#1954 Update modify_collection.md
  site/en/userGuide/modify_collection.md
Labels: size/XS

#1955 Added the default value of ttl in modify_collection.md
  site/en/userGuide/modify_collection.md
Labels: size/XS

#1956 Added collection.ttl.seconds in check_collection.md
  site/en/userGuide/check_collection.md
Labels: size/S

#1958 Update check_collection.md
  site/en/userGuide/check_collection.md
Labels: size/S

#1959 Minor fix
  site/en/release_notes.md
Labels: size/XS

#1960 [Issue resolved] Issues reported in #21413 has been resolved.
  site/en/adminGuide/authenticate.md
Labels: size/XS, lgtm

#1961 [Issue resolved] Issues reported in #21413 has been resolved.
  site/en/adminGuide/authenticate.md
Labels: size/XS
