Repository milvus-io/milvus-docs, pull requests merged in 2022-03, with the labels that each got.

#1402 Update example_code_node.md
  site/zh-CN/getstarted/example_code_node.md
Labels: size/M

#1401 Update example_code.md
  site/zh-CN/getstarted/example_code.md
Labels: size/XS

#1407 Add Calculate Distance (Python Only)
  site/en/menuStructure/en.json
  site/en/userGuide/calculate_distance.md
  site/zh-CN/menuStructure/cn.json
  site/zh-CN/userGuide/calculate_distance.md
Labels: size/L

#1408 Minor Fix
  site/zh-CN/userGuide/calculate_distance.md
Labels: size/XS

#1410 Minor Fix
  site/zh-CN/userGuide/release_partition.md
Labels: size/XS

#1413 Update check_collection.md
  site/zh-CN/userGuide/check_collection.md
Labels: size/L

#1415 Update drop_collection.md
  site/zh-CN/userGuide/drop_collection.md
Labels: size/M

#1417 Update load_collection.md
  site/zh-CN/userGuide/load_collection.md
Labels: size/M

#1416 Update collection_alias.md
  site/zh-CN/userGuide/collection_alias.md
Labels: size/L

#1418 Update release_collection.md
  site/zh-CN/userGuide/release_collection.md
Labels: size/M

#1419 Update four_layers.md
  site/zh-CN/reference/architecture/four_layers.md
Labels: size/XS

#1421 Update four_layers.md
  site/zh-CN/reference/architecture/four_layers.md
Labels: size/XS

#1420 Update data_processing.md
  site/zh-CN/reference/architecture/data_processing.md
Labels: size/S

#1422 Update configure_etcd.md
  site/zh-CN/reference/sys_config/configure_etcd.md
Labels: size/M

#1424 Update prerequisite-docker.md
  site/zh-CN/getstarted/prerequisite-docker.md
Labels: size/M

#1425 Update prerequisite-helm.md
  site/zh-CN/getstarted/prerequisite-helm.md
Labels: size/M

#1428 Add Benchmark Report
  assets/ecall_rt_g_f.png
  assets/index_node_time.png
  assets/nb_rt.png
  assets/nq_rt_1_1.png
  assets/nq_rt_50_4.png
  assets/nq_rt_50_8.png
  assets/nq_vps_1_1.png
  assets/nq_vps_50_4.png
  assets/nq_vps_50_8.png
  assets/qn_rt_qps.png
  assets/recall_rt_s.png
  assets/recall_rt_s_f.png
  assets/recall_rt_s_h.png
  assets/recall_rt_s_s.png
  assets/rt_qps.png
  site/en/menuStructure/en.json
  site/en/reference/benchmark.md
  site/zh-CN/menuStructure/cn.json
  site/zh-CN/reference/benchmark.md
Labels: size/XXL

#1429 Fix Image Path
  site/en/reference/benchmark.md
  site/zh-CN/reference/benchmark.md
Labels: size/M

#1430 Fix Code Block
  site/en/reference/benchmark.md
  site/zh-CN/reference/benchmark.md
Labels: size/L

#1431 Minor FIx
  site/en/reference/benchmark.md
  site/zh-CN/reference/benchmark.md
Labels: size/XS

#1432 Fix code
  site/en/reference/benchmark.md
  site/zh-CN/reference/benchmark.md
Labels: size/S

#1433 Fix Image
  assets/recall_rt_g_f.png
Labels: size/XS

#1434 Add Dynamic illustrations
  site/en/reference/benchmark.md
  site/zh-CN/reference/benchmark.md
Labels: size/XXL

#1427 Update hybridsearch.md
  site/zh-CN/userGuide/search/hybridsearch.md
Labels: size/L

#1435 MinorFix
  site/zh-CN/reference/benchmark.md
Labels: size/XS

#1436 Fix Js Format
  site/en/reference/benchmark.md
  site/zh-CN/reference/benchmark.md
Labels: size/L

#1438 Update query.md
  site/zh-CN/userGuide/search/query.md
Labels: size/XS

#1439 Fix Strong
  site/en/userGuide/create_collection.md
  site/en/userGuide/search/search.md
  site/zh-CN/userGuide/create_collection.md
  site/zh-CN/userGuide/search/search.md
Labels: size/S

#1442 Update image_similarity_search.md
  site/zh-CN/tutorials/image_similarity_search.md
Labels: size/XS

#1443 Update install-pymilvus.md
  site/zh-CN/getstarted/install_SDKs/install-pymilvus.md
Labels: size/XS

#1447 Fix: Complete documentation `about/comparison.md`
  site/en/about/comparison.md
  site/zh-CN/about/comparison.md
Labels: size/S

#1452 Update Home
  site/en/home/home.md
  site/zh-CN/home/home.md
Labels: size/M

#1446 Chore update ignore list, cleanup repo (#1445)
  .DS_Store
  .gitignore
  site/.DS_Store
  site/en/userGuide/.DS_Store
  site/en/userGuide/tools/.DS_Store
  site/zh-CN/.DS_Store
  site/zh-CN/userGuide/.DS_Store
  site/zh-CN/userGuide/tools/.DS_Store
Labels: size/S

#1453 Minor Fix
  site/en/reference/schema.md
  site/zh-CN/home/home.md
  site/zh-CN/reference/schema.md
Labels: size/S

#1454 Update query.md
  site/zh-CN/userGuide/search/query.md
Labels: size/M

#1455 Update search.md
  site/zh-CN/userGuide/search/search.md
Labels: size/S

#1457 Update prerequisite-helm.md
  site/zh-CN/getstarted/prerequisite-helm.md
Labels: size/XS

#1458 Update timetravel.md
  site/zh-CN/userGuide/search/timetravel.md
Labels: size/M

#1459 Minor Fix
  site/zh-CN/userGuide/drop_index.md
Labels: size/XS

#1462 Update insert_data.md
  site/zh-CN/userGuide/insert_data.md
Labels: size/M

#1460 Minor Fix
  site/zh-CN/userGuide/drop_index.md
Labels: size/XS

#1463 Minor code fix
  site/zh-CN/userGuide/check_partition.md
Labels: size/XS

#1464 Remake Boolean
  site/en/reference/boolean.md
  site/zh-CN/reference/boolean.md
Labels: size/L

#1465 Delete MilMil
  site/en/home/home.md
  site/zh-CN/home/home.md
Labels: size/S

#1466 Remove loadbalance
  site/en/home/home.md
  site/en/menuStructure/en.json
  site/zh-CN/home/home.md
  site/zh-CN/menuStructure/cn.json
Labels: size/S

#1467 Update issue template
  .github/ISSUE_TEMPLATE/--general-question.yaml
Labels: size/XS
