Repository milvus-io/milvus-docs, pull requests merged in 2022-07, with the labels that each got.

#1587 Update search.md
  site/zh-CN/userGuide/search/search.md
Labels: size/XS

#1595 Update metrics_dashboard.md
  site/en/adminGuide/monitor/metrics_dashboard.md
Labels: size/S

#1598 Update prerequisite-docker.md
  site/en/getstarted/prerequisite-docker.md
Labels: size/XS

#1599 Update example_code.md
  site/en/getstarted/example_code.md
Labels: size/XS

#1591 Add note on disk requirements for etcd (#1589)
  site/en/getstarted/prerequisite-docker.md
  site/en/getstarted/prerequisite-helm.md
Labels: size/M

#1600 Fix header reference in prerequisite docs
  site/en/getstarted/prerequisite-docker.md
  site/en/getstarted/prerequisite-helm.md
Labels: size/XS

#1601 Update boolean.md
  site/en/reference/boolean.md
Labels: size/S

#1602 Update metrics_dashboard.md
  site/en/adminGuide/monitor/metrics_dashboard.md
Labels: size/L

#1603 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1604 Update Variables.json
  site/en/Variables.json
Labels: size/XS

#1605 Update example_code_node.md
  site/en/getstarted/example_code_node.md
Labels: size/XS

#1609 Update Delete_data
  site/en/userGuide/delete_data.md
Labels: doc-improvement

#1531 Translate load_partition.md to Chinese
  site/zh-CN/userGuide/load_partition.md
Labels: size/M

#1532 translate check_partition.md to Chinese
  site/zh-CN/userGuide/check_partition.md
Labels: size/M

#1615 Update boolean.md
  site/en/reference/boolean.md
Labels: size/XS

#1617 Update index.md
  site/en/reference/index.md
Labels: size/M

#1618 Update index.md
  site/en/reference/index.md
Labels: size/M

#1572 Added curl commands to User Guide
  site/en/fragments/multiple_code.md
  site/en/userGuide/build_index.md
  site/en/userGuide/calculate_distance.md
  site/en/userGuide/check_collection.md
  site/en/userGuide/check_partition.md
  site/en/userGuide/collection_alias.md
  site/en/userGuide/compact_data.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/create_partition.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_collection.md
  site/en/userGuide/drop_index.md
  site/en/userGuide/drop_partition.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/load_partition.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/release_collection.md
  site/en/userGuide/release_partition.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/search/timetravel.md
Labels: doc-improvement, size/XXL

#1620 Align the expression of floating-point
  site/en/about/overview.md
  site/en/userGuide/create_collection.md
Labels: size/XS

#1621 Align the expression of floating-point in 2.1
  site/en/about/overview.md
  site/en/userGuide/create_collection.md
Labels: size/XS

#1622 Update prerequisite-helm.md
  site/en/getstarted/prerequisite-helm.md
Labels: size/XS

#1625 Update attu_install-helm.md
  site/en/userGuide/tools/attu_install-helm.md
Labels: size/L

#1626 Update metrics_dashboard.md
  site/en/adminGuide/monitor/metrics_dashboard.md
Labels: size/XS

#1627 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1628 Update 2.1.x README
  README.md
Labels: size/XS

#1629 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1631 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1634 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1635 Added a Milvus Operator version
  site/en/Variables.json
Labels: size/XS

#1636 Update release_notes.md
  site/en/release_notes.md
Labels: size/M

#1637 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1638 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1639 Update Variables.json
  site/en/Variables.json
Labels: size/S

#1640 Update Variables.json
  site/en/Variables.json
Labels: size/XS

#1623 Attu change
  assets/attu/create_collection_dialog_box1.png
  assets/attu/create_collection_dialog_box2.png
  assets/attu/insight_install.png
  assets/attu/insight_install_user_pwd.png
  assets/attu/insight_system1.png
  assets/attu/insight_system4.png
  assets/attu/view_cluster_statistics.png
  site/en/userGuide/tools/attu.md
  site/en/userGuide/tools/attu_install-docker.md
  site/en/userGuide/tools/attu_system.md
Labels: size/S

#1641 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1624 Update Install Milvus Cluster
  site/en/faq/troubleshooting.md
  site/en/fragments/installation_guide_cluster.md
  site/en/getstarted/cluster/install_cluster-ansible.md
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/release_notes.md
Labels: size/L

#1642 Updated labels in Install Milvus Cluster
  site/en/getstarted/cluster/install_cluster-ansible.md
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: doc-improvement, size/XS

#1633 Improve clarity and fix inconsistencies in install Milvus standalone docs
  site/en/fragments/installation_guide.md
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-helm.md
Labels: size/L

#1644 Update H1 with install methods in install Milvus standalone
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-helm.md
Labels: size/XS

#1645 Merge pull request #1644 from songxianj/v2.0.x
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-helm.md
Labels: size/XS

#1643 Update Install Milvus Cluster in 2.1.x
  site/en/faq/troubleshooting.md
  site/en/getstarted/cluster/install_cluster-ansible.md
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: doc-improvement, size/L

#1648 updated helm.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/standalone/install_standalone-helm.md
Labels: size/S

#1649 Added Install minikube to helm.md and milvusoperator.md
  site/en/fragments/create_a_k8s_cluster_using_minikube.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/getstarted/standalone/install_standalone-helm.md
Labels: size/M

#1650 cherry-picked pr #1649 to 2.1.x
  site/en/fragments/create_a_k8s_cluster_using_minikube.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/getstarted/standalone/install_standalone-helm.md
Labels: doc-improvement

#1651 Delete unnecessary installation fragments.
  site/en/fragments/installation_guide.md
  site/en/fragments/installation_guide_cluster.md
Labels: size/S

#1652 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1653 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1654 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#1655 Release 2.1.0 doc
  version.json
Labels: size/XS

#1656 Update README.md
  README.md
Labels: size/XS

#1657 improve the format of metrics.md
  site/en/adminGuide/monitor/metrics_dashboard.md
Labels: size/S

#1658 Fix the format of metrics.md
  site/en/adminGuide/monitor/metrics_dashboard.md
Labels: size/XS

#1660 Remove embedded Milvus related content.
  site/en/getstarted/example_code.md
  site/en/getstarted/install_embedded_milvus.md
Labels: size/S

#1661 deleted repeated sentences in install_standalone-helm in 2.1.x
  site/en/getstarted/standalone/install_standalone-helm.md
Labels: size/XS

#1662 deleted repeated sentences in install_standalone-helm in 2.0.x
  site/en/getstarted/standalone/install_standalone-helm.md
Labels: size/XS

#1665 Update configure docs
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/en/adminGuide/configure_operator.md
  site/en/adminGuide/deploy_etcd.md
  site/en/adminGuide/meta_storage_operator.md
  site/en/adminGuide/object_storage_operator.md
  site/en/menuStructure/en.json
Labels: size/L

#1666 Update CPU requirements
  site/en/getstarted/prerequisite-docker.md
  site/en/getstarted/prerequisite-helm.md
Labels: size/S

#1667 fixed punctuation errors
  site/en/reference/glossary.md
  site/en/userGuide/create_collection.md
Labels: doc-improvement

#1669 Update Milvus deb and rpm variables
  site/en/Variables.json
Labels: size/XS

#1670 updated configure-docker.md
  site/en/adminGuide/configure-docker.md
  site/en/reference/sys_config/configure_etcd.md
Labels: doc-improvement

#1671 Use variables in metrics.md code
  site/en/adminGuide/monitor/visualize.md
Labels: size/XS

#1672 Remove 2.0 benchmarks from 2.1 doc.
  site/en/menuStructure/en.json
Labels: size/XS

#1674 updated Configure Milvus docs
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/en/adminGuide/configure_operator.md
  site/en/adminGuide/deploy_etcd.md
  site/en/adminGuide/deploy_pulsar.md
  site/en/adminGuide/deploy_s3.md
  site/en/adminGuide/meta_storage_operator.md
  site/en/adminGuide/object_storage_operator.md
Labels: size/L

#1673 Revise all 2.0 related information in 2.1 docs.
  site/en/Variables.json
  site/en/about/overview.md
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/en/adminGuide/configure_operator.md
  site/en/adminGuide/monitor/monitor.md
  site/en/adminGuide/monitor/visualize.md
  site/en/adminGuide/scaleout.md
  site/en/faq/operational_faq.md
  site/en/faq/product_faq.md
  site/en/reference/architecture/data_processing.md
  site/en/reference/architecture/four_layers.md
  site/en/reference/glossary.md
  site/en/reference/schema.md
  site/en/userGuide/tools/cli_overview.md
Labels: size/M

#1675 Make all verbs following 'data' in plural form in 2.1.x
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/deploy_etcd.md
  site/en/faq/product_faq.md
  site/en/reference/metric.md
  site/en/reference/sys_config/configure_localstorage.md
  site/en/userGuide/tools/cli_commands.md
Labels: size/S

#1676 Use the 2.1.0 example in upgrade.md
  site/en/adminGuide/upgrade.md
Labels: size/M

#1677 Update product_faq.md
  site/en/faq/product_faq.md
Labels: size/XS

#1678 fixed broken links in Manage Dependencies with Milvus Operator
  site/en/adminGuide/message_storage_operator.md
  site/en/adminGuide/meta_storage_operator.md
  site/en/adminGuide/object_storage_operator.md
Labels: doc-bug, size/XS

#1680 Updated menu.
  site/en/adminGuide/deploy_etcd.md
  site/en/adminGuide/deploy_pulsar.md
  site/en/adminGuide/deploy_s3.md
  site/en/menuStructure/en.json
Labels: size/S

#1681 changed all verbs following 'data' to plural form in 2.0.x
  site/en/adminGuide/configure-docker.md
  site/en/faq/product_faq.md
  site/en/reference/metric.md
  site/en/reference/sys_config/configure_etcd.md
  site/en/reference/sys_config/configure_localstorage.md
  site/en/release_notes.md
  site/en/userGuide/tools/cli_commands.md
  site/zh-CN/reference/sys_config/configure_localstorage.md
  site/zh-CN/release_notes.md
Labels: size/S

#1682 Added a note to Euclidean distance
  site/en/reference/metric.md
Labels: size/XS

#1683 Added a note to Euclidean distance
  site/en/reference/metric.md
Labels: size/XS
