Repository milvus-io/milvus-docs, pull requests merged in 2022-01, with the labels that each got.

#1257 Fix typos in overview.md
  site/en/about/overview.md
Labels: size/XS

#1258 publish v2 preGa_zh
  site/zh-CN/release_notes.md
Labels: size/M

#1259 update rc9
  site/en/userGuide/tools/cli_commands.md
  site/en/userGuide/tools/cli_overview.md
  site/en/userGuide/tools/install_cli.md
  site/zh-CN/userGuide/tools/cli_commands.md
  site/zh-CN/userGuide/tools/cli_overview.md
  site/zh-CN/userGuide/tools/install_cli.md
Labels: size/L

#1261 update home.md for new milvus.io
  assets/MilMil.svg
  site/en/home/home.md
  site/zh-CN/home/home.md
Labels: size/M

#1186 Update Hello Milvus
  site/en/getstarted/example_code.md
  site/zh-CN/getstarted/example_code.md
Labels: size/L

#1262 Update What's new
  site/en/home/home.md
  site/zh-CN/home/home.md
Labels: size/M

#1266 Fix typo in attu_install-docker.md
  site/en/userGuide/tools/attu_install-docker.md
Labels: size/XS

#1268 Update release notes
  site/en/release_notes.md
  site/zh-CN/release_notes.md
Labels: size/S

#1267 Remake Get Started - Part I
  site/en/Variables.json
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/example_code_multi_lang/example_code_NL.md
  site/en/getstarted/example_code_multi_lang/example_code_bn.md
  site/en/getstarted/example_code_multi_lang/example_code_de.md
  site/en/getstarted/example_code_multi_lang/example_code_es.md
  site/en/getstarted/example_code_multi_lang/example_code_fr.md
  site/en/getstarted/example_code_multi_lang/example_code_id.md
  site/en/getstarted/example_code_multi_lang/example_code_it.md
  site/en/getstarted/install_SDKs/install-node.md
  site/en/getstarted/install_SDKs/install-pymilvus.md
  site/en/getstarted/offline/install_offline-docker.md
  site/en/getstarted/offline/install_offline-helm.md
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/reference/sys_config/configuration_cluster-advanced.md
  site/en/reference/sys_config/configuration_standalone-advanced.md
  site/zh-CN/Variables.json
  site/zh-CN/getstarted/cluster/install_cluster-docker.md
  site/zh-CN/getstarted/install_SDKs/install-node.md
  site/zh-CN/getstarted/install_SDKs/install-pymilvus.md
  site/zh-CN/getstarted/offline/install_offline-docker.md
  site/zh-CN/getstarted/offline/install_offline-helm.md
  site/zh-CN/getstarted/standalone/install_standalone-aptyum.md
  site/zh-CN/getstarted/standalone/install_standalone-docker.md
  site/zh-CN/reference/sys_config/configuration_cluster-advanced.md
  site/zh-CN/reference/sys_config/configuration_standalone-advanced.md
Labels: size/L

#1269 add home v3 md
  assets/MilMil.svg
  site/en/home/home_v3.md
  site/zh-CN/home/home_v3.md
Labels: size/L

#1270 Add CLI in Time Travel
  site/en/userGuide/search/timetravel.md
  site/zh-CN/userGuide/search/timetravel.md
Labels: size/L

#1273 Update home.md icon images
  bootcamps.svg
  standalone.svg
  start.svg
Labels: size/XS

#1274 Fix APT YUM link
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/zh-CN/getstarted/standalone/install_standalone-aptyum.md
Labels: size/XS

#1276 Fix Yum Install
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/zh-CN/getstarted/standalone/install_standalone-aptyum.md
Labels: size/M

#1280 Fix Python3
  site/en/getstarted/install_SDKs/install-pymilvus.md
  site/zh-CN/getstarted/install_SDKs/install-pymilvus.md
Labels: size/XS

#1281 Add translation needed note
  site/zh-CN/adminGuide/monitor/alert.md
  site/zh-CN/adminGuide/monitor/monitor.md
  site/zh-CN/adminGuide/monitor/monitor_overview.md
  site/zh-CN/adminGuide/monitor/visualize.md
  site/zh-CN/adminGuide/operator.md
  site/zh-CN/adminGuide/scaleout.md
  site/zh-CN/fragments/translation_needed.md
  site/zh-CN/getstarted/example_code.md
  site/zh-CN/getstarted/example_code_node.md
  site/zh-CN/getstarted/install_SDKs/install-node.md
  site/zh-CN/getstarted/install_SDKs/install-pymilvus.md
  site/zh-CN/getstarted/standalone/install_standalone-aptyum.md
  site/zh-CN/reference/timetravel_ref.md
  site/zh-CN/tutorials/audio_similarity_search.md
  site/zh-CN/tutorials/image_similarity_search.md
  site/zh-CN/tutorials/molecular_similarity_search.md
  site/zh-CN/tutorials/question_answering_system.md
  site/zh-CN/tutorials/recommendation_system.md
  site/zh-CN/tutorials/text_search_engine.md
  site/zh-CN/tutorials/video_similarity_search.md
  site/zh-CN/userGuide/build_index.md
  site/zh-CN/userGuide/check_collection.md
  site/zh-CN/userGuide/check_partition.md
  site/zh-CN/userGuide/collection_alias.md
  site/zh-CN/userGuide/create_collection.md
  site/zh-CN/userGuide/create_partition.md
  site/zh-CN/userGuide/delete_data.md
  site/zh-CN/userGuide/drop_collection.md
  site/zh-CN/userGuide/drop_index.md
  site/zh-CN/userGuide/drop_partition.md
  site/zh-CN/userGuide/insert_data.md
  site/zh-CN/userGuide/load_collection.md
  site/zh-CN/userGuide/manage_connection.md
  site/zh-CN/userGuide/search/hybridsearch.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
  site/zh-CN/userGuide/search/timetravel.md
Labels: size/M

#1283 fix note
  site/zh-CN/fragments/translation_needed.md
Labels: size/XS

#1289 Fix Hello Milvus Result
  site/en/getstarted/example_code.md
  site/zh-CN/getstarted/example_code.md
Labels: size/L

#1291 Add consistency detail in delete_data.md
  site/en/userGuide/delete_data.md
  site/zh-CN/userGuide/delete_data.md
Labels: size/XS

#1293 Fix CLI Code
  site/en/userGuide/tools/cli_commands.md
  site/zh-CN/userGuide/tools/cli_commands.md
Labels: size/L

#1294 Add new CLI Installation
  site/en/userGuide/tools/install_cli.md
  site/zh-CN/userGuide/tools/install_cli.md
Labels: size/M

#1297 Align code comment
  site/en/userGuide/check_collection.md
  site/zh-CN/userGuide/check_collection.md
Labels: size/M

#1298 Update Drop Collection method
  site/en/userGuide/drop_collection.md
  site/zh-CN/userGuide/drop_collection.md
Labels: size/M

#1299 Delete redundant content
  site/en/getstarted/install_SDKs/install-pymilvus.md
  site/zh-CN/getstarted/install_SDKs/install-pymilvus.md
Labels: size/XS

#1300 Update overview.md
  site/zh-CN/about/overview.md
Labels: size/XS

#1302 Update Group
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/getstarted/example_code.md
  site/en/getstarted/example_code_node.md
  site/en/getstarted/install_SDKs/install-node.md
  site/en/getstarted/install_SDKs/install-pymilvus.md
  site/en/getstarted/offline/install_offline-docker.md
  site/en/getstarted/offline/install_offline-helm.md
  site/en/getstarted/prerequisite-docker.md
  site/en/getstarted/prerequisite-helm.md
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/reference/sys_config/configuration_cluster-advanced.md
  site/en/reference/sys_config/configuration_cluster-basic.md
  site/en/reference/sys_config/configuration_standalone-advanced.md
  site/en/reference/sys_config/configuration_standalone-basic.md
  site/en/userGuide/tools/attu_install-docker.md
  site/en/userGuide/tools/attu_install-helm.md
  site/zh-CN/getstarted/cluster/install_cluster-docker.md
  site/zh-CN/getstarted/cluster/install_cluster-helm.md
  site/zh-CN/getstarted/cluster/install_cluster-milvusoperator.md
  site/zh-CN/getstarted/example_code.md
  site/zh-CN/getstarted/example_code_node.md
  site/zh-CN/getstarted/install_SDKs/install-node.md
  site/zh-CN/getstarted/install_SDKs/install-pymilvus.md
  site/zh-CN/getstarted/offline/install_offline-docker.md
  site/zh-CN/getstarted/offline/install_offline-helm.md
  site/zh-CN/getstarted/prerequisite-docker.md
  site/zh-CN/getstarted/prerequisite-helm.md
  site/zh-CN/getstarted/standalone/install_standalone-aptyum.md
  site/zh-CN/getstarted/standalone/install_standalone-docker.md
  site/zh-CN/getstarted/standalone/install_standalone-helm.md
  site/zh-CN/reference/sys_config/configuration_cluster-advanced.md
  site/zh-CN/reference/sys_config/configuration_cluster-basic.md
  site/zh-CN/reference/sys_config/configuration_standalone-advanced.md
  site/zh-CN/reference/sys_config/configuration_standalone-basic.md
  site/zh-CN/userGuide/tools/attu_install-docker.md
  site/zh-CN/userGuide/tools/attu_install-helm.md
Labels: size/L

#1304 Align usage of bitset.
  site/en/reference/timetravel_ref.md
  site/zh-CN/reference/timetravel_ref.md
Labels: size/S

#1309 Make Milvus roadmap an external link.
  site/en/menuStructure/en.json
Labels: size/XS

#1310 External link to Milvus roadmap (CN)
  site/zh-CN/menuStructure/cn.json
Labels: size/XS

#1312 Fix home remove loadbalance
  site/en/home/home.md
  site/zh-CN/home/home.md
Labels: size/XS

#1313 Fix note and nq
  site/en/about/limitations.md
  site/zh-CN/about/limitations.md
Labels: size/S

#1314 Fix monitor
  site/en/adminGuide/monitor/monitor.md
  site/zh-CN/adminGuide/monitor/monitor.md
Labels: size/M

#1311 Add Configure Milvus
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/en/adminGuide/monitor/visualize.md
  site/en/menuStructure/en.json
  site/en/reference/sys_config/configure_common.md
  site/en/reference/sys_config/configure_datacoord.md
  site/en/reference/sys_config/configure_datanode.md
  site/en/reference/sys_config/configure_etcd.md
  site/en/reference/sys_config/configure_indexcoord.md
  site/en/reference/sys_config/configure_indexnode.md
  site/en/reference/sys_config/configure_knowhere.md
  site/en/reference/sys_config/configure_localstorage.md
  site/en/reference/sys_config/configure_log.md
  site/en/reference/sys_config/configure_messagechannel.md
  site/en/reference/sys_config/configure_minio.md
  site/en/reference/sys_config/configure_proxy.md
  site/en/reference/sys_config/configure_pulsar.md
  site/en/reference/sys_config/configure_querycoord.md
  site/en/reference/sys_config/configure_querynode.md
  site/en/reference/sys_config/configure_rocksmq.md
  site/en/reference/sys_config/configure_rootcoord.md
  site/zh-CN/adminGuide/configure-docker.md
  site/zh-CN/adminGuide/configure-helm.md
  site/zh-CN/menuStructure/cn.json
  site/zh-CN/reference/sys_config/configure_common.md
  site/zh-CN/reference/sys_config/configure_datacoord.md
  site/zh-CN/reference/sys_config/configure_datanode.md
  site/zh-CN/reference/sys_config/configure_etcd.md
  site/zh-CN/reference/sys_config/configure_indexcoord.md
  site/zh-CN/reference/sys_config/configure_indexnode.md
  site/zh-CN/reference/sys_config/configure_knowhere.md
  site/zh-CN/reference/sys_config/configure_localstorage.md
  site/zh-CN/reference/sys_config/configure_log.md
  site/zh-CN/reference/sys_config/configure_messagechannel.md
  site/zh-CN/reference/sys_config/configure_minio.md
  site/zh-CN/reference/sys_config/configure_proxy.md
  site/zh-CN/reference/sys_config/configure_pulsar.md
  site/zh-CN/reference/sys_config/configure_querycoord.md
  site/zh-CN/reference/sys_config/configure_querynode.md
  site/zh-CN/reference/sys_config/configure_rocksmq.md
  site/zh-CN/reference/sys_config/configure_rootcoord.md
Labels: size/XXL

#1319 Add need help note
  site/zh-CN/userGuide/delete_data.md
Labels: size/XS

#1320 Add Package Installation for Attu
  site/en/userGuide/tools/attu_install-package.md
  site/zh-CN/userGuide/tools/attu_install-package.md
Labels: size/M

#1321 Fix attu table
  site/en/userGuide/tools/attu_install-package.md
  site/zh-CN/userGuide/tools/attu_install-package.md
Labels: size/S

#1322 Try multiple variables
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/zh-CN/getstarted/standalone/install_standalone-aptyum.md
Labels: size/XS

#1323 merge v3 into home.md
  site/en/home/home.md
  site/en/home/home_v3.md
  site/zh-CN/home/home.md
  site/zh-CN/home/home_v3.md
Labels: size/L

#1324 GA release
  site/en/Variables.json
  site/en/about/limitations.md
  site/en/fragments/multiple_code.md
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/install_SDKs/install-go.md
  site/en/getstarted/install_SDKs/install-java.md
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/reference/sys_config/configure_minio.md
  site/en/release_notes.md
  site/zh-CN/Variables.json
  site/zh-CN/about/limitations.md
  site/zh-CN/fragments/multiple_code.md
  site/zh-CN/getstarted/install_SDKs/install-go.md
  site/zh-CN/getstarted/install_SDKs/install-java.md
  site/zh-CN/getstarted/standalone/install_standalone-aptyum.md
  site/zh-CN/reference/sys_config/configure_minio.md
  site/zh-CN/release_notes.md
Labels: size/L

#1308 Update overview.md
  site/zh-CN/about/overview.md
Labels: size/XS

#1325 Attu-related changes
  site/en/about/comparison.md
  site/en/about/overview.md
  site/en/about/roadmap.md
  site/en/home/home.md
  site/en/menuStructure/en.json
  site/en/userGuide/tools/attu.md
  site/zh-CN/about/comparison.md
  site/zh-CN/about/overview.md
  site/zh-CN/about/roadmap.md
  site/zh-CN/home/home.md
  site/zh-CN/menuStructure/cn.json
  site/zh-CN/userGuide/tools/attu.md
Labels: size/S

#1326 Update home
  site/en/home/home.md
  site/zh-CN/home/home.md
Labels: size/M

#1328 Update and release hardware requirement
  site/en/getstarted/prerequisite-helm.md
  site/zh-CN/getstarted/prerequisite-docker.md
  site/zh-CN/getstarted/prerequisite-helm.md
Labels: size/L

#1330 Update overview.md
  site/zh-CN/about/overview.md
Labels: size/XS

#1332 Fix Code Display
  site/en/fragments/multiple_code.md
  site/en/userGuide/build_index.md
  site/en/userGuide/check_collection.md
  site/en/userGuide/check_partition.md
  site/en/userGuide/collection_alias.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/create_partition.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_collection.md
  site/en/userGuide/drop_index.md
  site/en/userGuide/drop_partition.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/release_collection.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/search/timetravel.md
  site/zh-CN/fragments/multiple_code.md
  site/zh-CN/userGuide/build_index.md
  site/zh-CN/userGuide/check_collection.md
  site/zh-CN/userGuide/check_partition.md
  site/zh-CN/userGuide/collection_alias.md
  site/zh-CN/userGuide/create_collection.md
  site/zh-CN/userGuide/create_partition.md
  site/zh-CN/userGuide/delete_data.md
  site/zh-CN/userGuide/drop_collection.md
  site/zh-CN/userGuide/drop_index.md
  site/zh-CN/userGuide/drop_partition.md
  site/zh-CN/userGuide/insert_data.md
  site/zh-CN/userGuide/load_collection.md
  site/zh-CN/userGuide/manage_connection.md
  site/zh-CN/userGuide/release_collection.md
  site/zh-CN/userGuide/search/hybridsearch.md
  site/zh-CN/userGuide/search/query.md
  site/zh-CN/userGuide/search/search.md
  site/zh-CN/userGuide/search/timetravel.md
Labels: size/L

#1334 Remove outdated system configuration
  site/en/adminGuide/deploy_s3.md
  site/en/adminGuide/operator.md
  site/en/faq/performance_faq.md
  site/en/getstarted/prerequisite-docker.md
  site/en/getstarted/prerequisite-helm.md
  site/en/home/home.md
  site/en/reference/index/index.md
  site/en/reference/sys_config/configuration_cluster-advanced.md
  site/en/reference/sys_config/configuration_cluster-basic.md
  site/en/reference/sys_config/configuration_standalone-advanced.md
  site/en/reference/sys_config/configuration_standalone-basic.md
  site/en/userGuide/build_index.md
  site/zh-CN/adminGuide/deploy_s3.md
  site/zh-CN/adminGuide/operator.md
  site/zh-CN/faq/performance_faq.md
  site/zh-CN/getstarted/prerequisite-docker.md
  site/zh-CN/getstarted/prerequisite-helm.md
  site/zh-CN/home/home.md
  site/zh-CN/reference/index/index.md
  site/zh-CN/reference/sys_config/configuration_cluster-advanced.md
  site/zh-CN/reference/sys_config/configuration_cluster-basic.md
  site/zh-CN/reference/sys_config/configuration_standalone-advanced.md
  site/zh-CN/reference/sys_config/configuration_standalone-basic.md
  site/zh-CN/userGuide/build_index.md
Labels: size/XXL

#1336 bump java sdk version
  site/en/Variables.json
  site/zh-CN/Variables.json
Labels: size/XS

#1337 Add load and release constraints
  site/en/userGuide/load_collection.md
  site/en/userGuide/release_collection.md
Labels: size/S
