Repository milvus-io/milvus-docs, pull requests merged in 2022-09, with the labels that each got.

#1782 Fix broken link in azure.md
  site/en/adminGuide/clouds/azure.md
Labels: size/XS

#1784 Fix broken link in 2.0 azure.md
  site/en/adminGuide/clouds/azure.md
Labels: size/XS

#1775 [DO NOT MERGE] 2.1 menu structure overhaul
  site/en/about/about_milvus.md
  site/en/adminGuide/administration_guide.md
  site/en/adminGuide/clouds/deploy_on_clouds.md
  site/en/adminGuide/configure_milvus.md
  site/en/adminGuide/manage_dependencies.md
  site/en/adminGuide/monitor/monitor_and_alert.md
  site/en/adminGuide/security.md
  site/en/api.md
  site/en/faq/faq.md
  site/en/getstarted/get_started.md
  site/en/getstarted/install_milvus.md
  site/en/reference/architecture/architecture.md
  site/en/reference/references.md
  site/en/tutorials/example_applications.md
  site/en/userGuide/manage_collections.md
  site/en/userGuide/manage_data.md
  site/en/userGuide/manage_indexes.md
  site/en/userGuide/manage_partitions.md
  site/en/userGuide/search/search_and_query.md
  site/en/userGuide/tools/tools.md
  site/en/userGuide/user_guide.md
Labels: size/L

#1783 [DO NOT MERGE] Milvus 2.0 menu structure overhaul
  site/en/about/about_milvus.md
  site/en/adminGuide/administration_guide.md
  site/en/adminGuide/clouds/deploy_on_clouds.md
  site/en/adminGuide/monitor/monitor_and_alert.md
  site/en/api.md
  site/en/faq/faq.md
  site/en/getstarted/get_started.md
  site/en/getstarted/install_milvus.md
  site/en/reference/architecture/architecture.md
  site/en/reference/references.md
  site/en/tutorials/example_applications.md
  site/en/userGuide/manage_collections.md
  site/en/userGuide/manage_data.md
  site/en/userGuide/manage_indexes.md
  site/en/userGuide/manage_partitions.md
  site/en/userGuide/search/search_and_query.md
  site/en/userGuide/search/searchandquery.md
  site/en/userGuide/tools/tools.md
  site/en/userGuide/user_guide.md
Labels: size/L

#1785 Add missing html tags in 1.1.0 docs homepage.
  site/en/home/home.md
  site/zh-CN/home/home.md
Labels: size/XS

#1786 Add missing html tags in 1.0.0 docs homepage.
  site/en/home/home.md
  site/zh-CN/home/home.md
Labels: size/XS

#1788 Add bitset reference docs
  assets/bitset_0.svg
  assets/bitset_1.jpg
  assets/bitset_2.jpg
  assets/bitset_3.jpg
  site/en/menuStructure/en.json
  site/en/reference/bitset.md
  site/en/reference/glossary.md
Labels: size/L

#1789 Consistent on-page design
  site/en/reference/architecture/architecture_overview.md
  site/en/reference/architecture/data_processing.md
  site/en/reference/architecture/four_layers.md
  site/en/reference/architecture/main_components.md
  site/en/reference/boolean.md
  site/en/reference/consistency.md
  site/en/reference/index.md
  site/en/reference/metric.md
  site/en/reference/replica.md
  site/en/reference/schema.md
Labels: size/M

#1791 added knowhere reference
  site/en/menuStructure/en.json
  site/en/reference/consistency.md
  site/en/reference/knowhere.md
Labels: size/L

#1787 Update 2.1.x docs home.md
  site/en/home/home.md
Labels: size/XS

#1792 missing parameter in `reset_password` utility
  site/en/adminGuide/authenticate.md
Labels: size/XS

#1796 Remove consistency from create a collection
  site/en/reference/consistency.md
  site/en/userGuide/create_collection.md
Labels: size/M

#1798 Update the definition and PromQL of some Milvus metrics
  site/en/adminGuide/monitor/metrics_dashboard.md
Labels: size/M

#1799 Update naming rules in limitation.md
  site/en/about/limitations.md
Labels: size/XS

#1800 Update glossary.md
  site/en/reference/glossary.md
Labels: size/XS

#1802 Update en.json menu structure
  site/en/menuStructure/en.json
Labels: size/S

#1803 Create time_sync.md
  assets/TSO_Timestamp.png
  assets/msgstream.png
  assets/time_synchronization.png
  assets/timesync_proxy_insert_msg.png
  assets/timetick.png
  site/en/menuStructure/en.json
  site/en/reference/time_sync.md
Labels: size/L

#1804 Update visualize.md
  site/en/adminGuide/monitor/visualize.md
Labels: size/XS

#1770 Updates for Milvus 2.1.2
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#1807 Update Variables.json
  site/en/Variables.json
Labels: size/XS

#1809 Update node SDK version
  site/en/Variables.json
Labels: size/XS

#1810 update attu ande node sdk version
  site/en/Variables.json
  site/en/userGuide/tools/attu_install-docker.md
  site/en/userGuide/tools/attu_install-package.md
Labels: size/S

#1811 Updates for Milvus 2.1.3
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#1812 Update Hello Milvus to 2.1.3 release
  site/en/getstarted/example_code.md
Labels: size/XS
