Repository milvus-io/milvus-docs, pull requests merged in 2023-06, with the labels that each got.

#2203 Add the usage of the rbac with database
  site/en/userGuide/manage_databases.md
Labels: size/M

#2198 Update insert_data.md
  site/en/userGuide/insert_data.md
Labels: size/XS

#2185 Update configure_datacoord.md
  site/en/reference/sys_config/configure_datacoord.md
Labels: size/XS

#2202 Fix grammar in example
  site/en/userGuide/search/search.md
Labels: size/XS

#2193 update: minio access credentials docs
  site/en/reference/sys_config/configure_minio.md
Labels: size/XS

#2190 Update index.md
  site/en/reference/index.md
Labels: size/XS

#2186 Update monitor.md
  site/en/adminGuide/monitor/monitor.md
Labels: size/S

#2184 The page says SSE42. I think it's supposed to be SSE4.2.
  site/en/quick_start/install_milvus/milvus_docker-cpu.md
Labels: size/XS

#2204 Release docs for 2.2.10
  site/en/Variables.json
  site/en/adminGuide/administration_guide.md
  site/en/adminGuide/allocate.md
  site/en/adminGuide/monitor/monitor.md
  site/en/adminGuide/monitor/visualize.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/getstarted/offline/install_offline-helm.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/getstarted/standalone/install_standalone-operator.md
  site/en/menuStructure/en.json
  site/en/reference/dynamic_schema.md
  site/en/reference/index.md
  site/en/reference/json_data_type.md
  site/en/reference/schema.md
  site/en/reference/users_and_roles.md
  site/en/release_notes.md
  site/en/userGuide/build_scalar_index.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/manage_databases.md
  site/en/userGuide/search/search.md
Labels: size/L

#2209 Doc release for v2.2.11
  site/en/Variables.json
  site/en/release_notes.md
  site/en/userGuide/tools/attu_install-docker.md
  site/en/userGuide/tools/milvus_backup_overview.md
Labels: size/M
