Repository milvus-io/milvus-docs, pull requests merged in 2023-01, with the labels that each got.

#1962 Update authenticate.md
  site/en/adminGuide/authenticate.md
Labels: size/XS

#1963 Update install_cluster-milvusoperator.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#1964 [Doc update] Lifts benchmark.md to the topmost level
  site/en/menuStructure/en.json
Labels: size/M

#1965 [Doc update] Lifts benchmark.md to the topmost level
  site/en/menuStructure/en.json
Labels: size/S

#1966 improve milvus_cli docs
  site/en/userGuide/tools/cli_commands.md
  site/en/userGuide/tools/cli_overview.md
Labels: size/M

#1967 Update object_storage_operator.md
  site/en/adminGuide/object_storage_operator.md
Labels: size/M

#1969 replace bulk insert doc
  site/en/userGuide/bulk_insert.bak.md
  site/en/userGuide/bulk_insert.md
Labels: size/XL

#1971 Update gcp doc
  assets/gcp-networking.png
  site/en/adminGuide/clouds/gcp.bak.md
  site/en/adminGuide/clouds/gcp.md
Labels: size/L

#1977 Update upgrade_milvus_standalone-docker.md
  site/en/adminGuide/upgrade_milvus_standalone-docker.md
Labels: size/XS
