Repository milvus-io/milvus-docs, pull requests merged in 2023-12, with the labels that each got.

#2376 Update eks.md
  site/en/adminGuide/clouds/aws/eks.md
Labels: size/XS

#2381 update metrics.md
  assets/substructure.png
  assets/superstructure.png
  site/en/reference/metric.md
Labels: size/S

#2386 update docs
  site/en/menuStructure/en.json
  site/en/release_notes.md
Labels: size/S

#2385 update with_iterators.md
  site/en/userGuide/search/with_iterators.md
Labels: size/M

#2378 Update limitations.md
  site/en/about/limitations.md
Labels: size/XS

#2377 Update limitations.md
  site/en/about/limitations.md
Labels: size/XS

#2369 add missing golang code examples
  site/en/userGuide/collection_alias.md
  site/en/userGuide/compact_data.md
  site/en/userGuide/delete_data.md
Labels: size/M

#2384 Typo: Corrected kubernetes spelling - Update four_layers.md
  site/en/reference/architecture/four_layers.md
Labels: size/XS

#2379 Corrects minio access key environment variable
  site/en/reference/sys_config/configure_minio.md
Labels: size/XS

#2383 add mmap docs
  site/en/adminGuide/scale-dependencies.md
  site/en/menuStructure/en.json
  site/en/reference/mmap.md
  site/en/release_notes.md
Labels: size/L

#2391 add azure ingress
  site/en/adminGuide/clouds/azure/ingress.md
  site/en/menuStructure/en.json
Labels: size/L
