Repository milvus-io/milvus-docs, pull requests merged in 2023-10, with the labels that each got.

#2316 Fix bug in example_code.md
  site/en/getstarted/example_code.md
Labels: size/XS

#2298 Update install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-docker.md
Labels: size/XS

#2321 Update install-csharp.md
  site/en/getstarted/install_SDKs/install-csharp.md
Labels: size/XS

#2325 Update upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
Labels: size/XS

#2329 Fixed milvus.io docs links in readme.md & contributing.md
  CONTRIBUTING.md
  README.md
Labels: size/XS

#2322 update doc for 2.3.2
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-gpu-docker.md
  site/en/getstarted/standalone/install_standalone-gpu-helm.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/getstarted/standalone/install_standalone-operator.md
  site/en/reference/array_data_type.md
  site/en/reference/boolean.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_index.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/search/with_iterators.md
Labels: size/XL

#2324 update insert_data
  site/en/userGuide/insert_data.md
Labels: size/XS

#2334 Bump up to 2.3.2
  site/en/Variables.json
  site/en/adminGuide/resource_group.md
  site/en/getstarted/example_code.md
  site/en/menuStructure/en.json
  site/en/reference/partition_key.md
  site/en/release_notes.md
Labels: size/L

#2336 Bump up operator and helm charts
  site/en/Variables.json
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
Labels: size/M
