Repository milvus-io/milvus-docs, pull requests merged in 2023-11, with the labels that each got.

#2339 Update benchmark.md
  site/en/reference/benchmark.md
Labels: size/XS

#2332 Update configure-docker.md
  site/en/adminGuide/configure-docker.md
Labels: size/XS

#2335 Update rbac.md
  site/en/adminGuide/rbac.md
Labels: size/XS

#2341 update within_range.md
  site/en/userGuide/search/within_range.md
Labels: size/L

#2345 update manage_connection.md
  site/en/userGuide/manage_connection.md
Labels: size/S

#2346 add gcs example
  site/en/adminGuide/clouds/gcp/gcp.md
Labels: size/M

#2347 update release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2348 Update search.md
  site/en/userGuide/search/search.md
Labels: size/XS

#2351 update docs
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2354 Update message_storage_operator.md
  site/en/adminGuide/message_storage_operator.md
Labels: size/S

#2353 Update install-csharp.md
  site/en/getstarted/install_SDKs/install-csharp.md
Labels: size/XS

#2356 add gcs
  assets/access_key.jpg
  site/en/adminGuide/clouds/gcp/gcp.md
  site/en/adminGuide/clouds/gcp/gcs.md
  site/en/menuStructure/en.json
Labels: size/L

#2357 fix-gcs-permission
  site/en/adminGuide/clouds/gcp/gcs.md
Labels: size/XS

#2358 fix png
  assets/gcp.png
Labels: size/XS

#2359 Update the privilege list
  site/en/reference/users_and_roles.md
Labels: size/XS

#2363 add azure blob storage with IAM
  site/en/adminGuide/clouds/azure/abs.md
  site/en/adminGuide/clouds/azure/azure.md
  site/en/adminGuide/clouds/gcp/gcs.md
  site/en/menuStructure/en.json
Labels: size/L

#2364 Update monitor.md
  site/en/adminGuide/monitor/monitor.md
Labels: size/XS

#2366 Update monitor.md
  site/en/adminGuide/monitor/monitor.md
Labels: size/XS

#2365 optimize azure
  site/en/adminGuide/clouds/azure/abs.md
Labels: size/S

#2375 udpate docs
  site/en/adminGuide/clouds/aws/eks.md
Labels: size/XL

#2374 fix azure storage
  site/en/adminGuide/clouds/azure/abs.md
  site/en/menuStructure/en.json
Labels: size/S
