Repository milvus-io/milvus-docs, pull requests merged in 2023-09, with the labels that each got.

#2290 Cherry pick cli
  site/en/userGuide/tools/cli_commands.md
  site/en/userGuide/tools/cli_overview.md
Labels: size/L

#2291 Fix model for OpenAI embeddings
  site/en/integrations/integrate_with_langchain.md
Labels: size/XS

#2287 Fixed typo in MILVUS_PORT
  site/en/integrations/integrate_with_hugging-face.md
Labels: size/XS

#2281 Fix typos
  site/en/faq/product_faq.md
  site/en/integrations/integrate_with_cohere.md
  site/en/integrations/integrate_with_hugging-face.md
  site/en/integrations/integrate_with_langchain.md
  site/en/integrations/integrate_with_sentencetransformers.md
Labels: size/S

#2283 Update install_standalone-helm.md
  site/en/getstarted/standalone/install_standalone-helm.md
Labels: size/XS

#2294 add csharp snippets
  site/en/fragments/sdk_restful.md
  site/en/getstarted/install_SDKs/install-csharp.md
  site/en/menuStructure/en.json
  site/en/userGuide/build_index.md
  site/en/userGuide/build_scalar_index.md
  site/en/userGuide/check_collection.md
  site/en/userGuide/check_partition.md
  site/en/userGuide/collection_alias.md
  site/en/userGuide/compact_data.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/create_partition.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_collection.md
  site/en/userGuide/drop_index.md
  site/en/userGuide/drop_partition.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/load_partition.md
  site/en/userGuide/manage_collections.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/manage_data.md
  site/en/userGuide/manage_indexes.md
  site/en/userGuide/manage_partitions.md
  site/en/userGuide/modify_collection.md
  site/en/userGuide/release_partition.md
  site/en/userGuide/rename_collection.md
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
Labels: size/XXL

#2299 correct broken links
  site/en/adminGuide/dynamic_config.md
  site/en/userGuide/create_collection.md
Labels: size/XS

#2296 [Fixup] Remove NATS from default mq priority
  site/en/adminGuide/message_storage_operator.md
Labels: size/XS

#2300 update configure-docker.md
  site/en/adminGuide/configure-docker.md
Labels: size/S

#2306 update limit and offset description
  site/en/faq/product_faq.md
  site/en/userGuide/bulk_insert.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/upsert_entities.md
Labels: size/M

#2307 add release notes for v2.3.1
  site/en/release_notes.md
Labels: size/M

#2305 fix issue: #2304
  site/en/userGuide/create_collection.md
  site/en/userGuide/create_partition.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/load_partition.md
  site/en/userGuide/release_partition.md
Labels: size/S

#2302 Typo in install_cluster-milvusoperator.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#2309 update scann index
  site/en/reference/index.md
Labels: size/S
