Repository milvus-io/milvus-docs, pull requests merged in 2023-02, with the labels that each got.

#1978 Add a new GCP doc page
  assets/gcp-networking.png
  site/en/adminGuide/clouds/gcp.md
  site/en/adminGuide/clouds/gcp/gcp.md
  site/en/adminGuide/clouds/gcp/gcp_layer7.md
  site/en/menuStructure/en.json
Labels: size/XL

#1979 Update install_cluster-milvusoperator.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
Labels: size/XS

#1980 Update limitations.md
  site/en/about/limitations.md
Labels: size/XS

#1981 Update configure_proxy.md
  site/en/reference/sys_config/configure_proxy.md
Labels: size/XS

#1982 Update configure_datacoord.md
  site/en/reference/sys_config/configure_datacoord.md
Labels: size/XS

#1983 Update deploy_etcd.md
  site/en/adminGuide/deploy_etcd.md
Labels: size/XS

#1984 Preview
  site/en/adminGuide/resource_group.md
  site/en/menuStructure/en.json
Labels: size/L

#1985 Preview
  site/en/adminGuide/resource_group.md
Labels: size/S

#1988 Update users_and_roles.md
  site/en/reference/users_and_roles.md
Labels: size/XS

#1989 Update configure-helm.md
  site/en/adminGuide/configure-helm.md
Labels: size/S

#1990 Add 2.2.3 release notes
  site/en/release_notes.md
Labels: size/L

#1991 Add 2.2.3 release notes
  site/en/release_notes.md
Labels: size/XS

#1992 Add 2.2.3 release notes
  site/en/Variables.json
Labels: size/XS

#1996 Adjust the order of tabs
  site/en/adminGuide/upgrade_milvus_cluster-docker.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/getstarted/standalone/install_standalone-operator.md
Labels: size/S

#1997 Adjust the order of tabs
  site/en/menuStructure/en.json
Labels: size/XS

#1995 Update overview.md
  site/en/about/overview.md
Labels: size/XS

#1999 Update release_notes.md
  site/en/release_notes.md
Labels: size/XS

#2000 Add docs on scalar field indexing
  assets/scalar_index.png
  site/en/menuStructure/en.json
  site/en/reference/scalar_index.md
  site/en/userGuide/build_index.md
  site/en/userGuide/build_scalar_index.md
Labels: size/L

#2001 Update Variables.json
  site/en/Variables.json
Labels: size/XS

#2002 Add docs on scalar field indexing
  site/en/menuStructure/en.json
Labels: size/XS

#2009 add docs on rolling upgrade
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-operator.md
  site/en/reference/sys_config/configure_datacoord.md
Labels: size/M

#2008 Update Variables.json
  site/en/Variables.json
Labels: size/XS

#2012 release docs for scalar field indexing
  assets/scalar_index.png
  site/en/menuStructure/en.json
  site/en/reference/scalar_index.md
  site/en/userGuide/build_scalar_index.md
Labels: size/L

#2016 add docs on rolling upgrade
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-operator.md
Labels: size/S
