Repository milvus-io/milvus-docs, pull requests merged in 2023-08, with the labels that each got.

#2255 Add more details for the All privilege in the Global object
  site/en/reference/users_and_roles.md
Labels: size/XS

#2258 doc release for v2.2.13
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2262 Update the connect code in the usage of rbac & database
  site/en/userGuide/manage_databases.md
Labels: size/XS

#2263 remove redundant files and update helm repo
  site/en/Variables.json
  site/en/about/about_milvus.md
  site/en/adminGuide/clouds/aws/eks.md
  site/en/adminGuide/clouds/azure.md
  site/en/adminGuide/clouds/deploy_on_clouds.md
  site/en/adminGuide/clouds/gcp/gcp.md
  site/en/adminGuide/monitor/monitor_and_alert.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/api.md
  site/en/faq/faq.md
  site/en/getstarted/cluster/install_cluster-ansible.md
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/example_code_multi_lang/example_code_NL.md
  site/en/getstarted/example_code_multi_lang/example_code_bn.md
  site/en/getstarted/example_code_multi_lang/example_code_de.md
  site/en/getstarted/example_code_multi_lang/example_code_es.md
  site/en/getstarted/example_code_multi_lang/example_code_fr.md
  site/en/getstarted/example_code_multi_lang/example_code_id.md
  site/en/getstarted/example_code_multi_lang/example_code_it.md
  site/en/getstarted/example_code_node.md
  site/en/getstarted/get_started.md
  site/en/getstarted/install_milvus.md
  site/en/getstarted/offline/install_offline-docker.md
  site/en/getstarted/offline/install_offline-helm.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/reference/disk_index.md
  site/en/reference/references.md
  site/en/tutorials/example_applications.md
  site/en/userGuide/search/search_and_query.md
  site/en/userGuide/tools/attu_install-helm.md
  site/en/userGuide/tools/attu_install-package.md
  site/en/userGuide/tools/attu_overview.md
  site/en/userGuide/tools/tools.md
Labels: size/XXL

#2259 fix typo and add missing info
  site/en/getstarted/prerequisite-docker.md
  site/en/reference/schema.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/drop_index.md
  site/en/userGuide/load_partition.md
Labels: size/S

#2250 Bold the param to classify description
  site/en/userGuide/bulk_insert.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/drop_partition.md
Labels: size/M

#2260 Update example_code.md
  site/en/getstarted/example_code.md
Labels: size/XS

#2265 update release notes
  site/en/Variables.json
  site/en/reference/disk_index.md
  site/en/release_notes.md
Labels: size/M

#2254 update docs for 2.3.0
  site/en/reference/schema.md
  site/en/userGuide/bulk_insert.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_partition.md
  site/en/userGuide/manage_data.md
  site/en/userGuide/release_partition.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/search/search_and_query.md
  site/en/userGuide/search/with_iterators.md
  site/en/userGuide/search/within_range.md
  site/en/userGuide/upsert_entities.md
Labels: size/XL

#2272 V2.3.x anthony
  site/en/menuStructure/en.json
  site/en/userGuide/search/query.md
  site/en/userGuide/search/with_iterators.md
  site/en/userGuide/search/within_range.md
Labels: size/M

#2279 V2.3.x anthony
  site/en/adminGuide/configure_milvus.md
  site/en/adminGuide/dynamic_config.md
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-operator.md
  site/en/menuStructure/en.json
  site/en/reference/sys_config/configure_minio.md
  site/en/userGuide/tools/birdwatcher_usage_guides.md
Labels: size/L

#2275 update cli docs
  site/en/userGuide/tools/cli_commands.md
  site/en/userGuide/tools/cli_overview.md
Labels: size/L
