Repository milvus-io/milvus-docs, pull requests merged in 2023-05, with the labels that each got.

#2170 Add MilvusClient documentation
  site/en/userGuide/user_guide.md
  site/en/userGuide/using_milvusclient.md
Labels: size/L

#2160 Update manage_connection.md
  site/en/userGuide/manage_connection.md
Labels: size/XS

#2171 Add use milvusclient
  site/en/menuStructure/en.json
  site/en/userGuide/user_guide.md
  site/en/userGuide/using_milvusclient.md
Labels: size/L

#2164 Update attu_install-docker.md
  site/en/userGuide/tools/attu_install-docker.md
Labels: size/M

#2169 Fix variable name in example_code.md
  site/en/getstarted/example_code.md
Labels: size/XS

#2176 Fixes #2175
  site/en/getstarted/example_code_node.md
Labels: size/XS
