Repository milvus-io/milvus-docs, pull requests merged in 2023-07, with the labels that each got.

#2227 update search docs
  site/en/userGuide/search/hybridsearch.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
Labels: size/S

#2228 V2.2.11
  site/en/menuStructure/en.json
  site/en/reference/partition_key.md
  site/en/userGuide/search/search.md
Labels: size/L

#2230 Update search
  site/en/userGuide/search/search.md
Labels: size/XS

#2232 Docs: Fix typo which will cause 'database not found' error
  site/en/userGuide/manage_databases.md
Labels: size/XS

#2181 Fix #2110
  site/en/userGuide/insert_data.md
Labels: size/XS

#2183 Fix #2182
  site/en/userGuide/search/search.md
Labels: size/XS

#2225 removed non-quote chars with double quotes for java example in search.md
  site/en/userGuide/search/search.md
Labels: size/XS

#2224 Update recommendation_system.md
  site/en/tutorials/recommendation_system.md
Labels: size/XS

#2222 Update configure_rocksmq.md
  site/en/reference/sys_config/configure_rocksmq.md
Labels: size/M

#2221 Update configure_pulsar.md
  site/en/reference/sys_config/configure_pulsar.md
Labels: size/S

#2220 Create configure_kafka
  site/en/reference/sys_config/configure_kafka
Labels: size/L

#2215 Update attu_data.md
  site/en/userGuide/tools/attu_data.md
Labels: size/XS

#2212 Update create_collection.md
  site/en/userGuide/create_collection.md
Labels: size/XS

#2206 Modify the format of release notes.md
  site/en/release_notes.md
Labels: size/XS

#2233 update dynamic_schema and json_data_type
  site/en/reference/dynamic_schema.md
  site/en/reference/json_data_type.md
  site/en/reference/sys_config/configure_kafka.md
  site/en/reference/sys_config/system_configuration.md
Labels: size/M

#2211 Update integrate_with_llama.md
  site/en/integrations/integrate_with_llama.md
Labels: size/XS

#2243 add release notes for v2.2.12
  site/en/fragments/multiple_sdk.md
  site/en/fragments/sdk_restful.md
  site/en/menuStructure/en.json
  site/en/release_notes.md
  site/en/userGuide/build_index.md
  site/en/userGuide/check_collection.md
  site/en/userGuide/check_partition.md
  site/en/userGuide/collection_alias.md
  site/en/userGuide/compact_data.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/create_partition.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_collection.md
  site/en/userGuide/drop_index.md
  site/en/userGuide/drop_partition.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/load_partition.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/release_collection.md
  site/en/userGuide/release_partition.md
  site/en/userGuide/search/query.md
  site/en/userGuide/search/search.md
  site/en/userGuide/search/timetravel.md
Labels: size/XL

#2246 update version
  site/en/Variables.json
Labels: size/XS

#2249 update docs
  site/en/adminGuide/message_storage_operator.md
  site/en/adminGuide/meta_storage_operator.md
  site/en/adminGuide/object_storage_operator.md
  site/en/reference/disk_index.md
  site/en/reference/users_and_roles.md
Labels: size/L

#2241 fix: "_refresh" boolean parameter value typos in python
  site/en/userGuide/bulk_insert.md
Labels: size/XS

#2238 fix: ignore_growing param typo in python
  site/en/userGuide/search/search.md
Labels: size/XS
