Repository milvus-io/milvus-docs, pull requests merged in 2023-03, with the labels that each got.

#2038 Update release_partition.md
  site/en/userGuide/release_partition.md
Labels: size/XS

#2031 refactor: create collection syntax error in nodejs
  site/en/userGuide/create_collection.md
Labels: size/XS

#2049 Preview
  site/en/reference/benchmark.md
Labels: size/S

#2030 Adding flush() to insert docs
  site/en/userGuide/insert_data.md
Labels: size/XS

#2057 Milvus v2.2.4 release
  site/en/Variables.json
  site/en/adminGuide/resource_group.md
  site/en/menuStructure/en.json
  site/en/release_notes.md
  site/en/userGuide/rename_collection.md
Labels: size/L

#2062 Add new bug fixes
  site/en/release_notes.md
Labels: size/XS

#2073 Update attu_install-docker.md
  site/en/userGuide/tools/attu_install-docker.md
Labels: size/S

#2087 Update docs related to GPU support
  site/en/adminGuide/configure-docker.md
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/offline/install_offline-docker.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/release_notes.md
Labels: size/M

#2083 add resource group rbac
  site/en/adminGuide/resource_group.md
  site/en/reference/users_and_roles.md
Labels: size/M

#2090 add resource group rbac
  site/en/adminGuide/resource_group.md
  site/en/reference/users_and_roles.md
Labels: size/M

#2094 Added release notes for v2.2.5
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2105 update upgrade docs
  site/en/adminGuide/upgrade_milvus_cluster-docker.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-docker.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-operator.md
Labels: size/XL
