Repository milvus-io/milvus-docs, pull requests merged in 2023-04, with the labels that each got.

#2075 Update attu install helm.md#install attu while installing milvus
  site/en/userGuide/tools/attu_install-helm.md
Labels: size/XS

#2074 Update install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-helm.md
Labels: size/XS

#2106 example_code.md: fix minimum Python version
  site/en/getstarted/example_code.md
Labels: size/XS

#2084 Update admin guide
  site/en/adminGuide/deploy_etcd.md
  site/en/adminGuide/deploy_pulsar.md
  site/en/adminGuide/deploy_s3.md
Labels: size/M, lgtm

#2118 Update tls.md
  site/en/adminGuide/tls.md
Labels: size/XS

#2117 Incorrect field name for Node.js collection spec.
  site/en/userGuide/create_collection.md
Labels: size/S

#2139 Python version 3.71 --> 3.7.1
  site/en/getstarted/example_code.md
Labels: size/XS

#2135 Update manage_connection.md
  site/en/userGuide/manage_connection.md
Labels: size/XS

#2143 Show user how to connect to Authenticated server
  site/en/userGuide/manage_connection.md
Labels: size/S

#2153 Add cuda version limit
  site/en/getstarted/cluster/install_cluster-docker.md
  site/en/getstarted/offline/install_offline-docker.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/release_notes.md
Labels: size/XS

#2156 Update install cluster
  site/en/getstarted/cluster/install_cluster-ansible.md
  site/en/getstarted/cluster/install_cluster-docker.md
Labels: size/XS

#2157 Doc release for v2.2.7
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M
