Repository milvus-io/milvus-docs, pull requests merged in 2024-07, with the labels that each got.

#2686 update metric type options for range search
  site/en/userGuide/search-query-get/single-vector-search.md
Labels: size/XS, lgtm

#2688 fix doc bug
  site/en/adminGuide/chunk_cache.md
Labels: size/XS

#2691 fix 404
  site/en/reference/sys_config/configure_knowhere.md
  site/en/reference/sys_config/system_configuration.md
  site/en/tutorials/audio_similarity_search.md
  site/en/tutorials/dna_sequence_classification.md
  site/en/tutorials/recommendation_system.md
Labels: size/XS

#2696 update install cmd
  site/en/embeddings/embeddings.md
Labels: size/XS

#2697 update docs
  site/en/integrations/integrate_with_bentoml.md
  site/en/integrations/integrate_with_fastgpt.md
  site/en/integrations/integrate_with_haystack.md
  site/en/integrations/integrate_with_hugging-face.md
  site/en/integrations/integrate_with_jina.md
  site/en/integrations/integrate_with_langchain.md
  site/en/integrations/integrate_with_llamaindex.md
  site/en/integrations/integrate_with_memgpt.md
  site/en/integrations/integrate_with_openai.md
  site/en/integrations/integrate_with_ragas.md
  site/en/integrations/integrate_with_vanna.md
  site/en/integrations/integrate_with_voyageai.md
  site/en/tutorials/build-rag-with-milvus.md
  site/en/tutorials/image_similarity_search.md
Labels: size/XL

#2699 add custom config
  site/en/getstarted/run-milvus-docker/install_standalone-docker.md
Labels: size/XS

#2690 add migration from 2.3.x
  site/en/menuStructure/en.json
  site/en/migrate/from-m2x.md
  site/en/migrate/migrate_overview.md
Labels: size/L

#2705 update faq based on chatbot insights
  site/en/faq/operational_faq.md
  site/en/faq/performance_faq.md
Labels: size/M

#2710 update milvus adopters
  site/en/about/milvus_adopters.md
Labels: size/XS

#2713 update release notes for 2.3.19
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2714 update insert-update-delete
  site/en/userGuide/insert-update-delete.md
Labels: size/XS

#2715 Optimize document structure for cloud
  site/en/adminGuide/clouds/aws/eks.md
  site/en/adminGuide/clouds/azure/azure.md
  site/en/adminGuide/clouds/gcp/gcp.md
  site/en/menuStructure/en.json
Labels: size/L

#2716 update radius & range_filter param description
  site/en/userGuide/search-query-get/single-vector-search.md
Labels: size/XS

#2717 update release notes for 2.4.6
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2718 update operator version
  site/en/Variables.json
Labels: size/XS

#2719 update docs
  site/en/home/home.md
  site/en/menuStructure/en.json
Labels: size/L

#2712 Update configure_querynode.md
  site/en/reference/sys_config/configure_querynode.md
Labels: size/XS

#2721 update tutorials
  site/en/tutorials/build-rag-with-milvus.md
  site/en/tutorials/image_similarity_search.md
Labels: size/M

#2722 add a topic describing how to deploy milvus on openshift
  assets/openshift-cert-manager-1.png
  assets/openshift-cert-manager-2.png
  site/en/adminGuide/clouds/openshift/openshift.md
  site/en/getstarted/milvus_lite.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker.md
  site/en/getstarted/run-milvus-gpu/install_cluster-helm-gpu.md
  site/en/getstarted/run-milvus-gpu/install_standalone-docker-compose-gpu.md
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
  site/en/menuStructure/en.json
Labels: size/L

#2723 update scripts
  assets/select-deployment-option.png
  site/en/adminGuide/allocate.md
  site/en/adminGuide/authenticate.md
  site/en/adminGuide/configure-querynode-localdisk.md
  site/en/adminGuide/scaleout.md
  site/en/adminGuide/upgrade_milvus_cluster-docker.md
  site/en/adminGuide/upgrade_milvus_standalone-docker.md
  site/en/getstarted/install-overview.md
  site/en/getstarted/milvus_lite.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker.md
  site/en/getstarted/run-milvus-gpu/install_cluster-helm-gpu.md
  site/en/getstarted/run-milvus-gpu/install_standalone-docker-compose-gpu.md
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
  site/en/home/home.json
  site/en/home/home.md
  site/en/menuStructure/en.json
Labels: size/L

#2725 remove highlight-related comments from example code
  site/en/reference/array_data_type.md
  site/en/userGuide/enable-dynamic-field.md
  site/en/userGuide/search-query-get/get-and-scalar-query.md
  site/en/userGuide/use-json-fields.md
  site/en/userGuide/use-partition-key.md
Labels: size/M

#2726 add aws s3 and layer7
  site/en/adminGuide/clouds/aws/aws_layer7.md
  site/en/adminGuide/clouds/aws/s3.md
  site/en/adminGuide/clouds/azure/ingress.md
  site/en/adminGuide/clouds/gcp/gcp_layer7.md
  site/en/menuStructure/en.json
Labels: size/L

#2727 fix the menu
  site/en/menuStructure/en.json
Labels: size/S

#2728 remove outdated note
  site/en/reference/boolean.md
Labels: size/XS

#2729 update release notes for v2.3.20
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2730 update milvus operator related configs
  site/en/adminGuide/allocate.md
  site/en/adminGuide/authenticate.md
  site/en/adminGuide/scaleout.md
  site/en/adminGuide/tls.md
Labels: size/M

#2731 update docs
  site/en/adminGuide/scale-dependencies.md
  site/en/adminGuide/scaleout.md
  site/en/reference/sys_config/system_configuration.md
Labels: size/M

#2732 update milvus-operator version, update deprecated doc
  site/en/Variables.json
  site/en/adminGuide/configure_operator.md
  site/en/adminGuide/message_storage_operator.md
  site/en/adminGuide/meta_storage_operator.md
  site/en/adminGuide/operator.md
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
Labels: size/M

#2733 Update the rbac demo when grant and revoke user privilege
  site/en/adminGuide/rbac.md
Labels: size/XS

#2735 add example code to insert-upsert-delete
  site/en/userGuide/insert-update-delete.md
Labels: size/M
