Repository milvus-io/milvus-docs, pull requests merged in 2024-04, with the labels that each got.

#2491 Update install-node.md
  site/en/getstarted/install_SDKs/install-node.md
Labels: size/XS

#2490 update 2.4 doc structure
  assets/datasource.jpg
  assets/milvuslog.jpg
  site/en/adminGuide/dynamic_config.md
  site/en/adminGuide/monitor/configure_grafana_loki.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/embeddings/embeddings.md
  site/en/menuStructure/en.json
  site/en/reference/architecture/data_processing.md
  site/en/reference/boolean.md
  site/en/reference/gpu_index.md
  site/en/reference/index.md
  site/en/reference/schema.md
  site/en/userGuide/manage-indexes/index-with-gpu.md
  site/en/userGuide/manage-partitions.md
  site/en/userGuide/manage_databases.md
  site/en/userGuide/search-query-get/single-vector-search.md
Labels: size/XXL

#2497 update 2.4 docs
  site/en/adminGuide/monitor/configure_grafana_loki.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
Labels: size/XS

#2499 Update use-json-fields.md
  site/en/userGuide/use-json-fields.md
Labels: size/XS

#2500 update sparse vector & admin guide structure
  site/en/menuStructure/en.json
  site/en/reference/index.md
  site/en/reference/sparse_vector.md
Labels: size/L

#2501 Update use-json-fields.md
  site/en/userGuide/use-json-fields.md
Labels: size/XS

#2439 Add Testcontainers section
  site/en/integrations/integrate_with_testcontainers.md
  site/en/menuStructure/en.json
Labels: size/M

#2506 V2.3.13
  site/en/Variables.json
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/release_notes.md
Labels: size/S

#2502 VoyageAI embeddings integration
  site/en/integrations/integrate_with_voyageai.md
Labels: size/L

#2508 update docs
  site/en/integrations/integrate_with_voyageai.md
  site/en/menuStructure/en.json
Labels: size/S

#2511 update 2.4 docs
  assets/multi-vector-rerank.png
  site/en/menuStructure/en.json
  site/en/reference/reranking.md
  site/en/reference/sparse_vector.md
  site/en/userGuide/search-query-get/multi-vector-search.md
Labels: size/L

#2517 update 2.4 release notes
  site/en/Variables.json
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/release_notes.md
Labels: size/M

#2519 add hello_milvus.py
  assets/hello_milvus.py
Labels: size/L

#2520 update quickstart
  site/en/getstarted/quickstart.md
Labels: size/S

#2522 update group-search limits
  site/en/userGuide/search-query-get/single-vector-search.md
Labels: size/XS

#2510 Update monitor.md to fix command error
  site/en/adminGuide/monitor/monitor.md
Labels: size/XS

#2529 add replica_number description
  site/en/reference/replica.md
  site/en/reference/sys_config/configure_querynode.md
  site/en/userGuide/manage-collections.md
Labels: size/S

#2515 fix subjectAltName error and add tlsMode specification in tls.md
  site/en/adminGuide/tls.md
Labels: size/S

#2516 fix subjectAltName error and add tlsMode specification in tls.md
  site/en/adminGuide/tls.md
Labels: size/S

#2523 Update the import path for the latest langchain
  site/en/integrations/integrate_with_langchain.md
Labels: size/S

#2524 Minor update to quickstart.md: get the color while getting entries
  site/en/getstarted/quickstart.md
Labels: size/XS

#2540 Update product_faq.md
  site/en/faq/product_faq.md
Labels: size/XS

#2536 Update metric.md
  site/en/reference/metric.md
Labels: size/XS

#2544 Change version
  site/en/getstarted/standalone/install_standalone-aptyum.md
Labels: size/XS

#2547 update release
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M
