Repository milvus-io/milvus-docs, pull requests merged in 2024-09, with the labels that each got.

#2791 add parameter to create_index
  site/en/userGuide/manage-indexes/index-vector-fields.md
Labels: size/XS

#2792 update tutorials
  assets/7bd73318-7929-4675-8998-c2e9ef091906.png
  assets/ad459431-95ac-4cbd-a931-453d08d5fdef.png
  assets/vllm_1.png
  assets/vllm_2.png
  site/en/integrations/integrations_overview.md
  site/en/integrations/llama_agents_metadata.md
  site/en/integrations/milvus_rag_with_vllm.md
  site/en/integrations/video_search_with_twelvelabs_and_milvus.md
  site/en/menuStructure/en.json
  site/en/tutorials/hybrid_search_with_milvus.md
  site/en/tutorials/tutorials-overview.md
Labels: size/XXL

#2796 Update quickstart.md
  site/en/getstarted/quickstart.md
Labels: size/XS

#2795 Update faq
  site/en/faq/product_faq.md
Labels: size/XS

#2798 update release notes for 2.4.11
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2801 Update default value of maxGeneralCapacity
  site/en/adminGuide/limit_collection_counts.md
Labels: size/XS

#2804 update docs
  assets/graph_rag_with_milvus_1.png
  assets/graph_rag_with_milvus_2.png
  assets/kotaemon_1.png
  assets/kotaemon_2.png
  assets/kotaemon_3.png
  site/en/integrations/kotaemon_with_milvus.md
  site/en/menuStructure/en.json
  site/en/tutorials/graph_rag_with_milvus.md
Labels: size/XL

#2806 update operational faq based on chatbot insights
  site/en/faq/operational_faq.md
Labels: size/M

#2803 feat: update docs for jina embeddings v3
  site/en/embeddings/embed-with-jina.md
  site/en/integrations/integrate_with_jina.md
Labels: size/L

#2807 Format YAML manifest
  site/en/adminGuide/clouds/openshift/openshift.md
Labels: size/S

#2802 Update with-iterators.md to fix the description.
  site/en/userGuide/search-query-get/with-iterators.md
Labels: size/XS

#2799 Update replica.md
  site/en/reference/replica.md
Labels: size/XS

#2793 Fix typo in clustering-compaction.md
  site/en/userGuide/clustering-compaction.md
Labels: size/XS

#2808 update docs
  site/en/integrations/integrations_overview.md
  site/en/integrations/kafka-connect-milvus.md
  site/en/menuStructure/en.json
  site/en/tutorials/tutorials-overview.md
Labels: size/L

#2790 update docs
  site/en/userGuide/manage-collections.md
  site/en/userGuide/manage-partitions.md
Labels: size/M

#2811 add embedding models
  site/en/embeddings/embed-with-instructor.md
  site/en/embeddings/embed-with-mgte.md
  site/en/embeddings/embed-with-mistral-ai.md
  site/en/embeddings/embed-with-nomic.md
  site/en/embeddings/embed-with-voyage.md
  site/en/embeddings/embeddings.md
  site/en/menuStructure/en.json
Labels: size/L

#2817 update rn for 2.4.12
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2818 update docs
  site/en/integrations/apify_milvus_rag.md
  site/en/integrations/dify_with_milvus.md
  site/en/integrations/evaluation_with_deepeval.md
  site/en/integrations/evaluation_with_phoenix.md
  site/en/integrations/integrations_overview.md
  site/en/menuStructure/en.json
Labels: size/XXL

#2819 update docs
  assets/phoenix01.png
  site/en/integrations/evaluation_with_phoenix.md
Labels: size/XS

#2812 enhance: refine doc for iterator and groupby
  site/en/userGuide/search-query-get/single-vector-search.md
  site/en/userGuide/search-query-get/with-iterators.md
Labels: size/M
