Repository milvus-io/milvus-docs, pull requests merged in 2024-10, with the labels that each got.

#2827 update docs
  site/en/menuStructure/en.json
Labels: size/XS

#2828 tls.md: fix typo, add guide for restful
  site/en/adminGuide/tls.md
Labels: size/S

#2637 add interface category description for architecture overview
  site/en/reference/architecture/architecture_overview.md
Labels: size/XS

#2669 update milvus backup version
  site/en/Variables.json
Labels: size/XS

#2673 Update cli_commands.md fix typo
  site/en/userGuide/tools/cli_commands.md
Labels: size/XS

#2753 Update install_standalone-docker-compose.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
Labels: size/XS

#2779 Update the default of The maximum number of partitions in each collection in manage-partitions.md
  site/en/userGuide/manage-partitions.md
Labels: size/XS

#2781 fix : default num_partitions value from 16->64 in use-partition-key.md
  site/en/userGuide/use-partition-key.md
Labels: size/XS

#2782 fix: Update hybrid_search_with_milvus.md, 'csr_array' object does not support slice yet
  site/en/tutorials/hybrid_search_with_milvus.md
Labels: size/XS

#2810 resolve issue-2809 with correct IAM Policy
  site/en/adminGuide/clouds/aws/s3.md
Labels: size/S

#2814 Update architecture_overview.md
  site/en/reference/architecture/architecture_overview.md
Labels: size/XS

#2815 Update performance_faq.md
  site/en/faq/performance_faq.md
Labels: size/XS

#2820 Update rbac.md
  site/en/adminGuide/rbac.md
Labels: size/XS

#2826 Update install_standalone-docker-compose.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
Labels: size/XS

#2831 update release notes for 2.4.13
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2832 update docs
  assets/langflow_dashboard_new_project.png
  assets/langflow_dashboard_start.png
  assets/langflow_default_structure.png
  assets/langflow_milvus_sidebar.png
  assets/langflow_milvus_structure.png
  assets/langflow_why_milvus.png
  site/en/getstarted/quickstart.md
  site/en/integrations/build_rag_on_arm.md
  site/en/integrations/evaluation_with_deepeval.md
  site/en/integrations/evaluation_with_phoenix.md
  site/en/integrations/integrate_with_bentoml.md
  site/en/integrations/integrate_with_camel.md
  site/en/integrations/integrate_with_dspy.md
  site/en/integrations/integrate_with_haystack.md
  site/en/integrations/integrate_with_hugging-face.md
  site/en/integrations/integrate_with_jina.md
  site/en/integrations/integrate_with_llamaindex.md
  site/en/integrations/integrate_with_openai.md
  site/en/integrations/integrate_with_ragas.md
  site/en/integrations/integrate_with_vanna.md
  site/en/integrations/integrate_with_voyageai.md
  site/en/integrations/integrations_overview.md
  site/en/integrations/langchain/integrate_with_langchain.md
  site/en/integrations/rag_with_langflow.md
  site/en/menuStructure/en.json
  site/en/tutorials/build-rag-with-milvus.md
  site/en/tutorials/contextual_retrieval_with_milvus.md
  site/en/tutorials/graph_rag_with_milvus.md
  site/en/tutorials/hybrid_search_with_milvus.md
  site/en/tutorials/image_similarity_search.md
  site/en/tutorials/multimodal_rag_with_milvus.md
  site/en/tutorials/tutorials-overview.md
Labels: size/XXL

#2836 update release notes for 2.4.13-hotfix
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/S

#2837 udpate docs
  assets/jaeger-trace-load.png
  assets/jaeger-trace-search.PNG
  site/en/adminGuide/config_jaeger_tracing.md
  site/en/adminGuide/connect_kafka_ssl.md
  site/en/menuStructure/en.json
Labels: size/XL

#2834 enhance: improve scripts standalone_embed,add upgrade describe
  site/en/getstarted/run-milvus-docker/install_standalone-docker.md
Labels: size/XS

#2839 update docs
  assets/hdbscan_clustering_with_milvus.png
  assets/vector_visualization_33_0.png
  site/en/integrations/build_RAG_with_milvus_and_fireworks.md
  site/en/integrations/build_RAG_with_milvus_and_lepton.md
  site/en/integrations/build_RAG_with_milvus_and_siliconflow.md
  site/en/integrations/integrations_overview.md
  site/en/menuStructure/en.json
  site/en/tutorials/hdbscan_clustering_with_milvus.md
  site/en/tutorials/tutorials-overview.md
  site/en/tutorials/use_ColPALI_with_milvus.md
  site/en/tutorials/vector_visualization.md
Labels: size/XXL

#2840 Update integrate_with_sentencetransformers.md
  site/en/integrations/integrate_with_sentencetransformers.md
Labels: size/L

#2841 update docs
  assets/colpali_formula.png
  site/en/menuStructure/en.json
  site/en/tutorials/tutorials-overview.md
  site/en/tutorials/use_ColPali_with_milvus.md
Labels: size/M

#2835 Doc: add seperated mmap fields per 2.4.10 release note
  site/en/reference/mmap.md
Labels: size/M

#2833 Update prerequisite-docker.md (Requirements for Milvus Standalone)
  site/en/getstarted/run-milvus-docker/prerequisite-docker.md
Labels: size/XS
