Repository milvus-io/milvus-docs, pull requests merged in 2024-12, with the labels that each got.

#2899 add analyzer details to release notes
  site/en/release_notes.md
  site/en/userGuide/schema/analyzer/analyzer-overview.md
  site/en/userGuide/search-query-get/full-text-search.md
  site/en/userGuide/search-query-get/metric.md
Labels: size/S

#2904 Update use-json-fields.md for Java
  site/en/userGuide/use-json-fields.md
Labels: size/XL

#2903 Update use-partition-key.md for Java
  site/en/userGuide/use-partition-key.md
Labels: size/L

#2902 Update enable-dynamic-field.md
  site/en/userGuide/enable-dynamic-field.md
Labels: size/L

#2900 Update insert-update-delete.md
  site/en/userGuide/insert-update-delete.md
Labels: size/L

#2901 Update schema.md
  site/en/reference/schema.md
Labels: size/XS

#2898 Update with-iterators.md for Java
  site/en/userGuide/search-query-get/with-iterators.md
Labels: size/L

#2897 Update get-and-scalar-query.md for Java
  site/en/userGuide/search-query-get/get-and-scalar-query.md
Labels: size/L

#2896 Update single-vector-search.md for Java SDK search
  site/en/userGuide/search-query-get/single-vector-search.md
Labels: size/L

#2905 update docs
  site/en/faq/operational_faq.md
  site/en/faq/performance_faq.md
  site/en/faq/product_faq.md
  site/en/reference/scalar_index.md
Labels: size/M

#2906 update docs
  site/en/reference/scalar_index.md
Labels: size/XS

#2907 update upgrade-pulsar-v3.md
  site/en/adminGuide/upgrade-pulsar-v3.md
Labels: size/XS

#2908 add multilingual code examples to analyzer-overview.md
  site/en/userGuide/schema/analyzer/analyzer-overview.md
Labels: size/L

#2909 update docs
  site/en/userGuide/search-query-get/full-text-search.md
Labels: size/S

#2910 Update array_data_type.md for Java
  site/en/reference/array_data_type.md
Labels: size/L

#2912 update docs
  site/en/adminGuide/connect_kafka_ssl.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
  site/en/getstarted/run-milvus-docker/install_standalone-windows.md
  site/en/integrations/dify_with_milvus.md
  site/en/integrations/integrate_with_fastgpt.md
  site/en/integrations/knowledge_table_with_milvus.md
  site/en/integrations/use_milvus_in_docsgpt.md
  site/en/userGuide/tools/milvus-cdc/deploy-cdc-server.md
Labels: size/M

#2915 update docs
  site/en/reference/gpu_index.md
Labels: size/S

#2916 update docs
  site/en/reference/gpu_index.md
Labels: size/S

#2914 Update full-text-search.md
  site/en/userGuide/search-query-get/full-text-search.md
Labels: size/XS

#2919 update docs
  site/en/userGuide/search-query-get/boolean.md
Labels: size/S

#2918 update tls doc
  site/en/adminGuide/tls.md
Labels: size/XL

#2913 update docs
  site/en/adminGuide/connect_kafka_ssl.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
  site/en/getstarted/run-milvus-docker/install_standalone-windows.md
  site/en/integrations/dify_with_milvus.md
  site/en/integrations/integrate_with_fastgpt.md
  site/en/integrations/knowledge_table_with_milvus.md
  site/en/integrations/use_milvus_in_docsgpt.md
  site/en/userGuide/tools/milvus-cdc/deploy-cdc-server.md
Labels: size/M

#2922 fix format
  site/en/adminGuide/tls.md
Labels: size/XS

#2921 update docs
  site/en/integrations/build_RAG_with_milvus_and_cognee.md
  site/en/integrations/build_RAG_with_milvus_and_gemini.md
  site/en/integrations/build_RAG_with_milvus_and_ollama.md
  site/en/integrations/integrations_overview.md
  site/en/integrations/milvus_rag_with_dynamiq.md
  site/en/menuStructure/en.json
  site/en/tutorials/full_text_search_with_milvus.md
  site/en/tutorials/tutorials-overview.md
  site/en/tutorials/use_ColPali_with_milvus.md
Labels: size/XXL

#2920 update docs
  site/en/integrations/build_RAG_with_milvus_and_cognee.md
  site/en/integrations/build_RAG_with_milvus_and_gemini.md
  site/en/integrations/build_RAG_with_milvus_and_ollama.md
  site/en/integrations/integrations_overview.md
  site/en/integrations/milvus_rag_with_dynamiq.md
  site/en/menuStructure/en.json
  site/en/tutorials/tutorials-overview.md
  site/en/tutorials/use_ColPali_with_milvus.md
  site/en/userGuide/use-json-fields.md
Labels: size/XXL

#2923 deprecate bm25 embedding model
  site/en/about/overview.md
  site/en/embeddings/embeddings.md
  site/en/menuStructure/en.json
Labels: size/M

#2930 add pulsar docs
  site/en/adminGuide/upgrade-pulsar-v3.md
  site/en/adminGuide/use-pulsar-v2.md
  site/en/menuStructure/en.json
Labels: size/L

#2933 update docs
  site/en/adminGuide/use-pulsar-v2.md
Labels: size/S

#2934 Update gpu_index.md
  site/en/reference/gpu_index.md
Labels: size/XS

#2935 update visualize.md
  site/en/adminGuide/monitor/visualize.md
Labels: size/XS

#2936 update: milvus cli 1.0.1 docs
  site/en/userGuide/tools/cli_commands.md
  site/en/userGuide/tools/cli_overview.md
Labels: size/L

#2937 update: milvus cli 1.0.1 docs
  site/en/userGuide/tools/cli_commands.md
  site/en/userGuide/tools/cli_overview.md
Labels: size/L

#2941 update 2.4.18 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2942 update example code for text match - use of 'not' keyword
  site/en/userGuide/search-query-get/keyword-match.md
Labels: size/M

#2943 add escape rules in expr to text-match
  site/en/userGuide/search-query-get/keyword-match.md
Labels: size/XS

#2944 update 2.5.0 rn
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/S

#2939 refactor rbac docs
  assets/privilege_group_illustrated.png
  assets/users_roles_privileges.png
  site/en/adminGuide/drop_users_roles.md
  site/en/adminGuide/grant_privileges.md
  site/en/adminGuide/grant_roles.md
  site/en/adminGuide/privilege_group.md
  site/en/adminGuide/rbac.md
  site/en/adminGuide/users_and_roles.md
  site/en/menuStructure/en.json
  site/en/reference/users_and_roles.md
Labels: size/XXL

#2938 refactor filtering docs
  site/en/menuStructure/en.json
  site/en/userGuide/search-query-get/boolean.md
  site/en/userGuide/search-query-get/boolean/array-operators.md
  site/en/userGuide/search-query-get/boolean/basic-operators.md
  site/en/userGuide/search-query-get/boolean/boolean.md
  site/en/userGuide/search-query-get/boolean/filtering-templating.md
  site/en/userGuide/search-query-get/boolean/json-operators.md
Labels: size/XXL

#2931 update docs
  assets/milvus-webui-overview.png
  assets/webui-collections.png
  assets/webui-configurations.png
  assets/webui-data.png
  assets/webui-home.png
  assets/webui-query.png
  assets/webui-slow-requests.png
  assets/webui-tasks.png
  site/en/menuStructure/en.json
  site/en/userGuide/tools/milvus-webui.md
Labels: size/L

#2928 Update config_jaeger_tracing.md for a typo
  site/en/adminGuide/config_jaeger_tracing.md
Labels: size/XS

#2927 Update config_jaeger_tracing.md for a typo
  site/en/adminGuide/config_jaeger_tracing.md
Labels: size/XS

#2945 update variables
  site/en/Variables.json
Labels: size/XS

#2946 update doc links
  site/en/release_notes.md
Labels: size/XS

#2949 add index types - hnsw_sq, hnsw_pq, hnsw_prq
  site/en/reference/index.md
Labels: size/L

#2952 Update home zilliz banner copy.md
  site/en/home/home.md
Labels: size/XS

#2950 update 2.5.1 rn & variables
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2951 update 2.4.19 rn
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2953 update docs
  assets/advanced_rag/adjust_order.png
  assets/advanced_rag/compress_prompt.png
  assets/advanced_rag/hierarchical_index.png
  assets/advanced_rag/hybrid_and_rerank.png
  assets/advanced_rag/hyde.png
  assets/advanced_rag/hypothetical_question.png
  assets/advanced_rag/merge_chunks.png
  assets/advanced_rag/metadata_filtering.png
  assets/advanced_rag/query_routing.png
  assets/advanced_rag/query_routing_with_sub_query.png
  assets/advanced_rag/self_reflection.png
  assets/advanced_rag/sentence_window.png
  assets/advanced_rag/stepback.png
  assets/advanced_rag/sub_query.png
  assets/advanced_rag/vanilla_rag.png
  assets/webui-collection-details.png
  assets/webui-collections.png
  assets/webui-configurations.png
  assets/webui-data.png
  assets/webui-home.png
  assets/webui-query.png
  assets/webui-slow-requests.png
  assets/webui-tasks.png
  site/en/menuStructure/en.json
  site/en/tutorials/how_to_enhance_your_rag.md
  site/en/tutorials/tutorials-overview.md
  site/en/userGuide/tools/milvus-webui.md
Labels: size/L

#2954 update docs
  assets/advanced_rag/adjust_order.png
  assets/advanced_rag/compress_prompt.png
  assets/advanced_rag/hierarchical_index.png
  assets/advanced_rag/hybrid_and_rerank.png
  assets/advanced_rag/hyde.png
  assets/advanced_rag/hypothetical_question.png
  assets/advanced_rag/merge_chunks.png
  assets/advanced_rag/metadata_filtering.png
  assets/advanced_rag/query_routing.png
  assets/advanced_rag/query_routing_with_sub_query.png
  assets/advanced_rag/self_reflection.png
  assets/advanced_rag/sentence_window.png
  assets/advanced_rag/stepback.png
  assets/advanced_rag/sub_query.png
  assets/advanced_rag/vanilla_rag.png
  site/en/menuStructure/en.json
  site/en/tutorials/full_text_search_with_milvus.md
  site/en/tutorials/how_to_enhance_your_rag.md
  site/en/tutorials/tutorials-overview.md
Labels: size/XL

#2924 Update sparse_vector.md to mention `BM_25`
  site/en/userGuide/schema/sparse_vector.md
Labels: size/XS

#2940 Update authenticate.md
  site/en/adminGuide/authenticate.md
Labels: size/XS

#2947 Update time_sync.md
  site/en/reference/time_sync.md
Labels: size/XS

#2948 Update multi_tenancy.md
  site/en/reference/multi_tenancy.md
Labels: size/S

#2925 Update index.md to mention BM25 metric
  site/en/reference/index.md
Labels: size/XS

#2955 update menuStructure
  site/en/menuStructure/en.json
Labels: size/XS

#2957 update docs
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker.md
  site/en/getstarted/run-milvus-docker/install_standalone-windows.md
  site/en/getstarted/run-milvus-gpu/install_cluster-helm-gpu.md
  site/en/getstarted/run-milvus-gpu/install_standalone-docker-compose-gpu.md
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
  site/en/menuStructure/en.json
  site/en/userGuide/tools/milvus-webui.md
Labels: size/L
