Repository milvus-io/milvus-docs, pull requests merged in 2024-08, with the labels that each got.

#2737 update docs
  assets/cir_with_milvus_20_1.png
  assets/cir_with_milvus_20_3.png
  assets/multimodal_rag_with_milvus_22_0.png
  assets/multimodal_rag_with_milvus_28_1.png
  site/en/integrations/integrate_with_camel.md
  site/en/menuStructure/en.json
  site/en/tutorials/cir_with_milvus.md
  site/en/tutorials/hybrid_search_with_milvus.md
  site/en/tutorials/multimodal_rag_with_milvus.md
Labels: size/XXL

#2738 Update tutorials
  assets/cir_with_milvus_20_1.png
  assets/cir_with_milvus_20_3.png
  assets/multimodal_rag_with_milvus_22_0.png
  assets/multimodal_rag_with_milvus_28_1.png
  site/en/menuStructure/en.json
  site/en/tutorials/build-rag-with-milvus.md
  site/en/tutorials/cir_with_milvus.md
  site/en/tutorials/hybrid_search_with_milvus.md
  site/en/tutorials/image_similarity_search.md
  site/en/tutorials/multimodal_rag_with_milvus.md
Labels: size/L

#2739 Fix typo
  site/en/tutorials/multimodal_rag_with_milvus.md
Labels: size/XS

#2740 Fix multimodal rag
  site/en/tutorials/multimodal_rag_with_milvus.md
Labels: size/XS

#2748 update docs based on chatbot insights
  site/en/faq/product_faq.md
  site/en/getstarted/install-overview.md
  site/en/userGuide/manage-collections.md
Labels: size/S

#2747 Update disk_index.md
  site/en/reference/disk_index.md
Labels: size/XS

#2734 Update scale-dependencies.md
  site/en/adminGuide/scale-dependencies.md
Labels: size/S

#2749 change the `object name` to the `object type` in the privilege table
  site/en/reference/users_and_roles.md
Labels: size/XS

#2750 add comments for object_type and obect_name
  site/en/adminGuide/rbac.md
Labels: size/XS

#2751 Update with-iterators.md
  site/en/userGuide/search-query-get/with-iterators.md
Labels: size/XS

#2755 Update rbac.md
  site/en/adminGuide/rbac.md
Labels: size/S

#2756 Update comparison.md
  site/en/about/comparison.md
Labels: size/XS

#2757 update users_and_roles
  site/en/reference/users_and_roles.md
Labels: size/M

#2759 Update milvus_lite.md to improve description, limitation and add migr…
  site/en/getstarted/milvus_lite.md
Labels: size/L

#2761 update docs
  assets/airbyte_with_milvus_1.png
  assets/airbyte_with_milvus_2.png
  assets/airbyte_with_milvus_3.png
  assets/airbyte_with_milvus_4.png
  assets/airbyte_with_milvus_5.png
  assets/airbyte_with_milvus_6.png
  site/en/integrations/integrate_with_airbyte.md
  site/en/integrations/langchain/basic_usage_langchain.md
  site/en/integrations/langchain/integrate_with_langchain.md
  site/en/integrations/langchain/milvus_hybrid_search_retriever.md
  site/en/menuStructure/en.json
  site/en/tutorials/build-rag-with-milvus.md
  site/en/tutorials/hybrid_search_with_milvus.md
  site/en/tutorials/image_similarity_search.md
  site/en/tutorials/multimodal_rag_with_milvus.md
Labels: size/XL

#2763 Update docs
  site/en/menuStructure/en.json
Labels: size/XS

#2764 Update index-scalar-fields.md
  site/en/userGuide/manage-indexes/index-scalar-fields.md
Labels: size/XS

#2768 update docs
  site/en/userGuide/manage-partitions.md
Labels: size/XS

#2765 update release notes for 2.4.8
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/L

#2754 update array_data_type
  site/en/reference/array_data_type.md
  site/en/userGuide/manage-indexes/index-scalar-fields.md
Labels: size/XL

#2769 update release notes for v2.3.21
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2736 feat: update configuration from milvus.yaml
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/en/adminGuide/configure_operator.md
  site/en/adminGuide/deploy_pulsar.md
  site/en/reference/sys_config/configure_common.md
  site/en/reference/sys_config/configure_datacoord.md
  site/en/reference/sys_config/configure_datanode.md
  site/en/reference/sys_config/configure_etcd.md
  site/en/reference/sys_config/configure_gpu.md
  site/en/reference/sys_config/configure_grpc.md
  site/en/reference/sys_config/configure_indexcoord.md
  site/en/reference/sys_config/configure_indexnode.md
  site/en/reference/sys_config/configure_kafka.md
  site/en/reference/sys_config/configure_knowhere.md
  site/en/reference/sys_config/configure_localstorage.md
  site/en/reference/sys_config/configure_log.md
  site/en/reference/sys_config/configure_messagechannel.md
  site/en/reference/sys_config/configure_metastore.md
  site/en/reference/sys_config/configure_minio.md
  site/en/reference/sys_config/configure_mq.md
  site/en/reference/sys_config/configure_msgchannel.md
  site/en/reference/sys_config/configure_nats.md
  site/en/reference/sys_config/configure_natsmq.md
  site/en/reference/sys_config/configure_proxy.md
  site/en/reference/sys_config/configure_pulsar.md
  site/en/reference/sys_config/configure_querycoord.md
  site/en/reference/sys_config/configure_querynode.md
  site/en/reference/sys_config/configure_quota_limits.md
  site/en/reference/sys_config/configure_quotaandlimits.md
  site/en/reference/sys_config/configure_rocksmq.md
  site/en/reference/sys_config/configure_rootcoord.md
  site/en/reference/sys_config/configure_tikv.md
  site/en/reference/sys_config/configure_tls.md
  site/en/reference/sys_config/configure_trace.md
  site/en/reference/sys_config/system_configuration.md
  site/en/userGuide/tools/milvus-cdc/deploy-cdc-server.md
Labels: size/XXL

#2772 update release notes for v2.4.9
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2773 add default value for reorder_k
  site/en/reference/index.md
Labels: size/XS

#2774 update show session description for birdwatcher
  site/en/getstarted/milvus_lite.md
  site/en/userGuide/tools/birdwatcher_usage_guides.md
Labels: size/S

#2780 feat: update docs
  site/en/about/comparison.md
  site/en/about/roadmap.md
  site/en/adminGuide/deploy_etcd.md
  site/en/adminGuide/deploy_pulsar.md
  site/en/adminGuide/deploy_s3.md
  site/en/adminGuide/rbac.md
  site/en/faq/operational_faq.md
  site/en/faq/performance_faq.md
  site/en/faq/product_faq.md
  site/en/getstarted/quickstart.md
  site/en/getstarted/run-milvus-gpu/install_cluster-helm-gpu.md
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
  site/en/home/home.md
  site/en/migrate/es2m.md
  site/en/migrate/f2m.md
  site/en/migrate/m2m.md
  site/en/reference/benchmark.md
  site/en/reference/disk_index.md
  site/en/userGuide/manage-collections.md
  site/en/userGuide/manage_databases.md
  site/en/userGuide/search-query-get/single-vector-search.md
  site/en/userGuide/search-query-get/with-iterators.md
Labels: size/XL

#2783 update docs
  assets/highly-decoupled-architecture.png
  assets/unstructured-data-embedding-and-milvus.png
  site/en/about/overview.md
  site/en/menuStructure/en.json
  site/en/userGuide/clustering-compaction.md
Labels: size/L

#2784 update docs
  assets/clustering-compaction-2.png
  assets/clustering-compaction.png
  site/en/userGuide/clustering-compaction.md
Labels: size/XS

#2788 Update the cdc doc
  site/en/userGuide/tools/milvus-cdc/deploy-cdc-server.md
  site/en/userGuide/tools/milvus-cdc/manage-cdc-tasks.md
Labels: size/S

#2776 Small typo in quickstart
  site/en/getstarted/quickstart.md
Labels: size/XS

#2789 update 2.4.10 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M
