Repository milvus-io/milvus-docs, pull requests merged in 2024-02, with the labels that each got.

#2422 fix docker doc
  site/en/getstarted/standalone/install_standalone-docker.md
Labels: size/L

#2425 update docs
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-docker-compose.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/getstarted/standalone/install_standalone-operator.md
  site/en/getstarted/with_gpu/install_cluster-helm-gpu.md
  site/en/getstarted/with_gpu/install_standalone-docker-compose-gpu.md
  site/en/getstarted/with_gpu/install_standalone-helm-gpu.md
Labels: size/L

#2426 Update install_standalone-docker-compose.md
  site/en/getstarted/standalone/install_standalone-docker-compose.md
Labels: size/XS

#2424 [doc typo] Update integrate_with_llamaindex.md
  site/en/integrations/integrate_with_llamaindex.md
Labels: size/XS

#2428 update docs
  assets/install-databricks-library.png
  site/en/integrations/integrate_with_spark.md
Labels: size/L

#2427 Update query.md
  site/en/userGuide/search/query.md
Labels: size/XS

#2429 add rpm
  site/en/getstarted/standalone/install_standalone-aptyum.md
Labels: size/M

#2430 update release notes
  site/en/Variables.json
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/release_notes.md
Labels: size/M

#2433 V2.3.9
  site/en/Variables.json
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/release_notes.md
Labels: size/M

#2432 add 2.3.8 binary
  site/en/getstarted/standalone/install_standalone-aptyum.md
Labels: size/XS

#2441 update docs
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2443 Update scale dependencies guide for operator
  site/en/adminGuide/scale-dependencies.md
Labels: size/XS

#2448 Update integrate_with_spark.md fix mistake
  site/en/integrations/integrate_with_spark.md
Labels: size/XS

#2446 Update load_collection.md
  site/en/userGuide/load_collection.md
Labels: size/XS

#2445 Update json_data_type.md
  site/en/reference/json_data_type.md
Labels: size/XS

#2444 change package version to 2.3.10
  site/en/getstarted/standalone/install_standalone-aptyum.md
Labels: size/XS

#2434 Adding missing package Milvus
  site/en/integrations/integrate_with_langchain.md
Labels: size/XS
