Repository milvus-io/milvus-docs, pull requests merged in 2024-03, with the labels that each got.

#2451 update docs
  site/en/Variables.json
  site/en/adminGuide/clouds/aws/eks.md
  site/en/release_notes.md
Labels: size/M

#2453 Add recommended scenarios in multi_tenancy.md
  site/en/reference/multi_tenancy.md
Labels: size/S

#2460 Update integrate_with_haystack.md
  site/en/integrations/integrate_with_haystack.md
Labels: size/L

#2457 Update scalar_index.md
  site/en/reference/scalar_index.md
Labels: size/XS

#2458 Update scalar_index.md
  site/en/reference/scalar_index.md
Labels: size/XS

#2456 Update import path for the latest llama index
  site/en/integrations/integrate_with_llamaindex.md
Labels: size/XS

#2454 Update integrate_with_llamaindex.md
  site/en/integrations/integrate_with_llamaindex.md
Labels: size/XS

#2459 update docs
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2461 Update question and datasource
  site/en/integrations/integrate_with_haystack.md
Labels: size/XS

#2462 Add guide to attach policy in eks.md
  site/en/adminGuide/clouds/aws/eks.md
Labels: size/XS

#2463 update docs
  site/en/getstarted/with_gpu/install_cluster-helm-gpu.md
  site/en/getstarted/with_gpu/install_standalone-docker-compose-gpu.md
  site/en/getstarted/with_gpu/install_standalone-helm-gpu.md
  site/en/reference/index.md
Labels: size/L

#2465 merge latest updates from v2.3.x
  site/en/Variables.json
  site/en/adminGuide/clouds/aws/eks.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/getstarted/with_gpu/install_cluster-helm-gpu.md
  site/en/getstarted/with_gpu/install_standalone-docker-compose-gpu.md
  site/en/getstarted/with_gpu/install_standalone-helm-gpu.md
  site/en/integrations/integrate_with_haystack.md
  site/en/integrations/integrate_with_llamaindex.md
  site/en/reference/index.md
  site/en/reference/multi_tenancy.md
  site/en/reference/scalar_index.md
  site/en/release_notes.md
Labels: size/L

#2468 Update install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-helm.md
Labels: size/XS

#2466 update docs
  site/en/about/overview.md
  site/en/adminGuide/configure_operator.md
  site/en/adminGuide/monitor/metrics_dashboard.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/cluster/install_cluster-milvusoperator.md
  site/en/getstarted/install_SDKs/install-go.md
  site/en/getstarted/install_SDKs/install-java.md
  site/en/getstarted/install_SDKs/install-node.md
  site/en/getstarted/install_SDKs/install-pymilvus.md
  site/en/getstarted/offline/install_offline-helm.md
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-docker-compose.md
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/getstarted/standalone/install_standalone-operator.md
  site/en/getstarted/with_gpu/install_cluster-helm-gpu.md
  site/en/getstarted/with_gpu/install_standalone-docker-compose-gpu.md
  site/en/getstarted/with_gpu/install_standalone-helm-gpu.md
  site/en/home/home.json
  site/en/home/home.md
  site/en/menuStructure/en.json
  site/en/reference/architecture/four_layers.md
  site/en/reference/array_data_type.md
  site/en/reference/boolean.md
  site/en/reference/consistency.md
  site/en/reference/coordinator_ha.md
  site/en/reference/disk_index.md
  site/en/reference/index.md
  site/en/reference/replica.md
  site/en/reference/scalar_index.md
  site/en/reference/schema.md
  site/en/reference/sys_config/configure_indexcoord.md
  site/en/reference/sys_config/system_configuration.md
  site/en/release_notes.md
  site/en/userGuide/import_data.md
  site/en/userGuide/load_balance.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/search-query-get/multi-vector-search.md
Labels: size/XXL

#2467 Update limitations.md
  site/en/about/limitations.md
Labels: size/XS

#2470 Update embeddings.md
  site/en/embeddings/embeddings.md
Labels: size/XS

#2469 change package version to 2.3.12
  site/en/getstarted/standalone/install_standalone-aptyum.md
Labels: size/XS

#2473 update 2.3 docs
  site/en/userGuide/build_index.md
  site/en/userGuide/build_scalar_index.md
  site/en/userGuide/bulk_insert.md
  site/en/userGuide/check_collection.md
  site/en/userGuide/check_partition.md
  site/en/userGuide/collection_alias.md
  site/en/userGuide/compact_data.md
  site/en/userGuide/create_collection.md
  site/en/userGuide/create_partition.md
  site/en/userGuide/delete_data.md
  site/en/userGuide/drop_collection.md
  site/en/userGuide/drop_index.md
  site/en/userGuide/drop_partition.md
  site/en/userGuide/import_data.md
  site/en/userGuide/insert_data.md
  site/en/userGuide/load_balance.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/load_partition.md
  site/en/userGuide/manage_connection.md
  site/en/userGuide/manage_databases.md
  site/en/userGuide/modify_collection.md
  site/en/userGuide/release_collection.md
  site/en/userGuide/release_partition.md
  site/en/userGuide/rename_collection.md
  site/en/userGuide/tune_consistency.md
  site/en/userGuide/upsert_entities.md
Labels: size/L

#2474 Fine tune some syntax of the doc
  site/en/integrations/integrate_with_pytorch.md
Labels: size/XS

#2476 udpate docs
  site/en/Variables.json
  site/en/home/home.md
Labels: size/S

#2479 V2.4.x
  site/en/userGuide/search-query-get/multi-vector-search.md
Labels: size/XS

#2480 update docs for the min go version
  site/en/getstarted/install_SDKs/install-go.md
Labels: size/XS

#2483 update 2.4 docs
  site/en/reference/gpu_index.md
  site/en/reference/sparse_vector.md
  site/en/userGuide/enable-dynamic-field.md
  site/en/userGuide/import_data.md
  site/en/userGuide/insert-update-delete.md
  site/en/userGuide/manage-collections.md
  site/en/userGuide/manage-indexes/index-scalar-fields.md
  site/en/userGuide/manage-indexes/index-vector-fields.md
  site/en/userGuide/manage-partitions.md
  site/en/userGuide/search-query-get/get-and-scalar-query.md
  site/en/userGuide/search-query-get/single-vector-search.md
  site/en/userGuide/search-query-get/with-iterators.md
  site/en/userGuide/use-json-fields.md
  site/en/userGuide/use-partition-key.md
Labels: size/M

#2482 Update gpu_index.md
  site/en/reference/gpu_index.md
Labels: size/XS

#2485 update 2.4 docs
  site/en/faq/product_faq.md
  site/en/reference/gpu_index.md
  site/en/userGuide/enable-dynamic-field.md
  site/en/userGuide/insert-update-delete.md
  site/en/userGuide/manage-partitions.md
  site/en/userGuide/search-query-get/get-and-scalar-query.md
  site/en/userGuide/search-query-get/single-vector-search.md
  site/en/userGuide/use-json-fields.md
Labels: size/M

#2487 update 2.4 docs
  assets/milvus_architecture.jpeg
  assets/milvus_architecture.png
  site/en/about/overview.md
  site/en/getstarted/quickstart.md
  site/en/integrations/integrate_with_langchain.md
  site/en/reference/architecture/architecture_overview.md
  site/en/reference/schema.md
  site/en/userGuide/enable-dynamic-field.md
  site/en/userGuide/insert-update-delete.md
  site/en/userGuide/manage-collections.md
  site/en/userGuide/manage-indexes/index-vector-fields.md
  site/en/userGuide/manage-partitions.md
  site/en/userGuide/search-query-get/get-and-scalar-query.md
  site/en/userGuide/search-query-get/single-vector-search.md
  site/en/userGuide/search-query-get/with-iterators.md
  site/en/userGuide/use-json-fields.md
  site/en/userGuide/use-partition-key.md
Labels: size/L
