Repository milvus-io/milvus-docs, pull requests merged in 2024-06, with the labels that each got.

#2624 docs: update milvus_lite.md - Fix minor typo
  site/en/getstarted/milvus_lite.md
Labels: size/XS

#2625 update 2.4 docs
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
Labels: size/XS

#2627 update menu structure
  site/en/menuStructure/en.json
Labels: size/M

#2628 update milvus operator version
  site/en/Variables.json
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
Labels: size/XS

#2629 update docs
  site/en/getstarted/quickstart.md
  site/en/integrations/integrate_with_bentoml.md
  site/en/integrations/integrate_with_dspy.md
  site/en/integrations/integrate_with_jina.md
  site/en/integrations/integrate_with_langchain.md
  site/en/integrations/integrate_with_openai.md
  site/en/integrations/integrate_with_voyageai.md
  site/en/tutorials/image_similarity_search.md
Labels: size/XL

#2630 update index docs
  site/en/menuStructure/en.json
  site/en/reference/index.md
  site/en/reference/metric.md
  site/en/userGuide/insert-update-delete.md
  site/en/userGuide/manage-collections.md
  site/en/userGuide/manage-indexes/index-scalar-fields.md
  site/en/userGuide/manage-indexes/index-vector-fields.md
  site/en/userGuide/manage-partitions.md
  site/en/userGuide/search-query-get/get-and-scalar-query.md
  site/en/userGuide/search-query-get/single-vector-search.md
  site/en/userGuide/search-query-get/with-iterators.md
Labels: size/L

#2633 Update index.md
  site/en/reference/index.md
Labels: size/S

#2632 Update install_standalone-docker-compose.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
Labels: size/XS

#2631 Update image_similarity_search.md
  site/en/tutorials/image_similarity_search.md
Labels: size/XS

#2634 add milvus lite limits
  site/en/getstarted/milvus_lite.md
Labels: size/L

#2638 Update use-partition-key.md
  site/en/userGuide/use-partition-key.md
Labels: size/XS

#2635 update docs
  .github/workflows/check.yml
  check-link.js
  package-lock.json
  package.json
  site/en/adminGuide/configure-docker.md
  site/en/adminGuide/configure-helm.md
  site/en/adminGuide/configure_operator.md
  site/en/userGuide/manage-collections.md
  site/en/userGuide/manage_databases.md
Labels: size/XXL

#2653 format v2.0.x memu
  .github/workflows/ci.yml
  site/en/menuStructure/en.json
Labels: size/XXL

#2652 format v2.1.x menu
  .github/workflows/ci.yml
  site/en/menuStructure/en.json
Labels: size/XXL

#2650 format v2.3.x menu
  .github/workflows/ci.yml
  site/en/menuStructure/en.json
Labels: size/XXL

#2649 format v2.4.x menu
  .github/workflows/ci.yml
  site/en/menuStructure/en.json
Labels: size/XXL

#2648 docs: fixed typo in multi-vector-search.md
  site/en/userGuide/search-query-get/multi-vector-search.md
Labels: size/XS

#2654 add param description & fix doc bugs
  site/en/migrate/es2m.md
  site/en/migrate/f2m.md
  site/en/migrate/m2m.md
  site/en/reference/benchmark.md
  site/en/reference/boolean.md
  site/en/reference/scalar_index.md
  site/en/userGuide/enable-dynamic-field.md
  site/en/userGuide/insert-update-delete.md
  site/en/userGuide/manage-collections.md
  site/en/userGuide/manage-indexes/index-vector-fields.md
  site/en/userGuide/search-query-get/get-and-scalar-query.md
  site/en/userGuide/search-query-get/single-vector-search.md
  site/en/userGuide/search-query-get/with-iterators.md
  site/en/userGuide/use-partition-key.md
Labels: size/XXL

#2657 update action
  .github/workflows/check.yml
Labels: size/XS

#2659 fix doc bug
  site/en/userGuide/manage-collections.md
Labels: size/XS

#2660 add set_properties to manage-collections and update scalar index
  site/en/reference/scalar_index.md
  site/en/userGuide/manage-collections.md
Labels: size/M

#2661 Update manage-collections.md
  site/en/userGuide/manage-collections.md
Labels: size/XS

#2662 update embedding and reranker models
  site/en/embeddings/embed-with-cohere.md
  site/en/embeddings/embed-with-jina.md
  site/en/embeddings/embeddings.md
  site/en/menuStructure/en.json
  site/en/rerankers/rerankers-jina.md
  site/en/rerankers/rerankers-overview.md
Labels: size/L

#2663 update install milvus with gpu support
  site/en/getstarted/run-milvus-gpu/install_standalone-docker-compose-gpu.md
Labels: size/M

#2647 Update resource group document
  site/en/adminGuide/resource_group.md
Labels: size/L

#2666 update docs
  site/en/getstarted/quickstart.md
  site/en/integrations/integrate_with_bentoml.md
  site/en/integrations/integrate_with_dspy.md
  site/en/integrations/integrate_with_hugging-face.md
  site/en/integrations/integrate_with_jina.md
  site/en/integrations/integrate_with_langchain.md
  site/en/integrations/integrate_with_llamaindex.md
  site/en/integrations/integrate_with_openai.md
  site/en/integrations/integrate_with_voyageai.md
  site/en/tutorials/build-rag-with-milvus.md
  site/en/tutorials/image_similarity_search.md
Labels: size/M

#2667 update 2.3.18 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2668 Update glossary.md
  site/en/reference/glossary.md
Labels: size/XS

#2670 Update Milvus_cli 1.0.0 doc
  site/en/userGuide/tools/cli_commands.md
  site/en/userGuide/tools/cli_overview.md
Labels: size/S

#2671 update run-milvus-docker
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker.md
Labels: size/S

#2665 update release notes for v2.4.5
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2676 update deploy cdc server
  site/en/userGuide/tools/milvus-cdc/deploy-cdc-server.md
Labels: size/S

#2675 update gpu index, after update raft 24.04
  site/en/reference/gpu_index.md
  site/en/userGuide/manage-indexes/index-with-gpu.md
Labels: size/M

#2677 fix doc bug in install_cluster-helm
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
Labels: size/XS

#2678 update hybrid search & reranking
  assets/arctan.png
  assets/rrf-ranker.png
  assets/weighted-reranker.png
  site/en/about/comparison.md
  site/en/getstarted/install_SDKs/install-go.md
  site/en/getstarted/install_SDKs/install-java.md
  site/en/getstarted/install_SDKs/install-node.md
  site/en/getstarted/install_SDKs/install-pymilvus.md
  site/en/getstarted/milvus_lite.md
  site/en/getstarted/offline/install_offline-helm.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker.md
  site/en/getstarted/run-milvus-gpu/install_cluster-helm-gpu.md
  site/en/getstarted/run-milvus-gpu/install_standalone-docker-compose-gpu.md
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/getstarted/standalone/install_standalone-operator.md
  site/en/getstarted/with_gpu/install_standalone-helm-gpu.md
  site/en/home/home.md
  site/en/reference/boolean.md
  site/en/reference/consistency.md
  site/en/reference/glossary.md
  site/en/reference/reranking.md
  site/en/reference/scalar_index.md
  site/en/reference/schema.md
  site/en/release_notes.md
  site/en/userGuide/import_data.md
  site/en/userGuide/load_balance.md
  site/en/userGuide/search-query-get/multi-vector-search.md
  site/en/userGuide/search-query-get/single-vector-search.md
Labels: size/L

#2680 Update aws.md
  site/en/adminGuide/clouds/aws/aws.md
Labels: size/XS

#2682 fix eks doc
  site/en/adminGuide/clouds/aws/eks.md
Labels: size/S

#2684 fix eks install
  site/en/adminGuide/clouds/aws/eks.md
Labels: size/S

#2683 fix arn
  site/en/adminGuide/clouds/aws/eks.md
Labels: size/XS
