Repository milvus-io/milvus-docs, pull requests merged in 2024-05, with the labels that each got.

#2554 update 2.4 docs
  assets/coordinator_ha.png
  assets/distributed_architecture.jpg
  assets/handoff.jpg
  assets/standalone_architecture.jpg
  site/en/Variables.json
  site/en/adminGuide/authenticate.md
  site/en/adminGuide/rbac.md
  site/en/adminGuide/tls.md
  site/en/embeddings/embed-with-voyage.md
  site/en/getstarted/quickstart.md
  site/en/menuStructure/en.json
  site/en/release_notes.md
  site/en/rerankers/rerankers-bge.md
  site/en/rerankers/rerankers-cohere.md
  site/en/rerankers/rerankers-cross-encoder.md
  site/en/rerankers/rerankers-overview.md
  site/en/rerankers/rerankers-voyage.md
Labels: size/XXL

#2549 Update index.md
  site/en/reference/index.md
Labels: size/XS

#2545 Update schema.md
  site/en/reference/schema.md
Labels: size/XS

#2543 Update upgrade_milvus_standalone-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-operator.md
Labels: size/XS

#2548 Update overview.md
  site/en/about/overview.md
Labels: size/S

#2538 Update hello_milvus.py
  assets/hello_milvus.py
Labels: size/XS

#2532 Update main_components.md
  site/en/reference/architecture/main_components.md
Labels: size/S

#2533 Update four_layers.md
  site/en/reference/architecture/four_layers.md
Labels: size/XS

#2534 Update architecture_overview.md
  site/en/reference/architecture/architecture_overview.md
Labels: size/XS

#2539 Update index-vector-fields.md
  site/en/userGuide/manage-indexes/index-vector-fields.md
Labels: size/XS

#2555 add num_partitions description
  site/en/userGuide/use-partition-key.md
Labels: size/S

#2556 update roadmap, comparison, and glossary
  site/en/about/comparison.md
  site/en/about/roadmap.md
  site/en/menuStructure/en.json
  site/en/reference/glossary.md
Labels: size/L

#2557 update milvus adopters
  assets/milvus-adopters.png
  site/en/about/milvus_adopters.md
Labels: size/M

#2558 Update embedding.md
  site/en/embeddings/embeddings.md
Labels: size/XS

#2559 Update create_collection.md
  site/en/userGuide/create_collection.md
Labels: size/XS

#2561 update docs
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2566 add outlink for milvus-migration
  site/en/menuStructure/en.json
Labels: size/S

#2564 Update install_standalone-helm-gpu.md
  site/en/getstarted/with_gpu/install_standalone-helm-gpu.md
Labels: size/XS

#2563 Update reranking.md
  site/en/reference/reranking.md
Labels: size/XS

#2567 update migration doc structure
  site/en/menuStructure/en.json
Labels: size/M

#2573 Update limitations.md Input and Output per RPC
  site/en/about/limitations.md
Labels: size/XS

#2572 Update limitations.md Input and Output per RPC
  site/en/about/limitations.md
Labels: size/XS

#2571 Update limitations.md Input and Output per RPC
  site/en/about/limitations.md
Labels: size/XS

#2568 Update multi_tenancy.md
  site/en/reference/multi_tenancy.md
Labels: size/XS

#2565 Add llama-index parameters to doc
  site/en/integrations/integrate_with_llamaindex.md
Labels: size/S

#2530 Change the model name in the voyage sample
  site/en/integrations/integrate_with_voyageai.md
Labels: size/XS

#2570 Update deploy_s3.md
  site/en/adminGuide/deploy_s3.md
Labels: size/XS

#2575 Update milvus-model related docs.
  site/en/embeddings/embed-with-bgm-m3.md
  site/en/embeddings/embed-with-bm25.md
  site/en/embeddings/embed-with-openai.md
  site/en/embeddings/embed-with-sentence-transform.md
  site/en/embeddings/embed-with-splade.md
  site/en/embeddings/embed-with-voyage.md
  site/en/rerankers/rerankers-bge.md
  site/en/rerankers/rerankers-cohere.md
  site/en/rerankers/rerankers-cross-encoder.md
  site/en/rerankers/rerankers-voyage.md
Labels: size/M

#2574 update docs
  site/en/integrations/integrate_with_voyageai.md
  site/en/menuStructure/en.json
Labels: size/L

#2577 update docs
  assets/map-data-to-schema.png
  site/en/menuStructure/en.json
  site/en/userGuide/data-import/import-data.md
  site/en/userGuide/data-import/prepare-source-data.md
Labels: size/XL

#2576 Fixes typo on monitoring setting
  site/en/adminGuide/monitor/monitor.md
Labels: size/XS

#2578 update docs
  site/en/menuStructure/en.json
  site/en/userGuide/data-import/import-data.md
  site/en/userGuide/data-import/prepare-source-data.md
Labels: size/M

#2582 change package version to 2.3.15
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-docker.md
Labels: size/S

#2580 change package version to 2.4.1
  site/en/getstarted/standalone/install_standalone-aptyum.md
Labels: size/XS

#2586 Update index.md
  site/en/reference/index.md
Labels: size/XS

#2587 Update index.md
  site/en/reference/index.md
Labels: size/XS

#2588 update docs
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2590 Update integrate_with_openai.md
  site/en/integrations/integrate_with_openai.md
Labels: size/L

#2591 update 2.4 docs
  site/en/embeddings/embeddings.md
  site/en/reference/glossary.md
  site/en/reference/sparse_vector.md
Labels: size/M

#2592 update docs
  site/en/reference/array_data_type.md
  site/en/userGuide/enable-dynamic-field.md
  site/en/userGuide/insert-update-delete.md
  site/en/userGuide/manage-collections.md
  site/en/userGuide/manage-indexes/index-scalar-fields.md
  site/en/userGuide/manage-indexes/index-vector-fields.md
  site/en/userGuide/manage-partitions.md
  site/en/userGuide/search-query-get/get-and-scalar-query.md
  site/en/userGuide/search-query-get/single-vector-search.md
  site/en/userGuide/search-query-get/with-iterators.md
  site/en/userGuide/use-json-fields.md
  site/en/userGuide/use-partition-key.md
Labels: size/XXL

#2596 update sparse vector
  site/en/reference/sparse_vector.md
Labels: size/XS

#2594 Update index.md: fix a typo
  site/en/reference/index.md
Labels: size/XS

#2584 chore: fix typos
  site/en/adminGuide/clouds/aws/aws.md
  site/en/adminGuide/operator.md
  site/en/adminGuide/scale-dependencies.md
Labels: size/XS

#2599 update docs
  site/en/userGuide/manage_databases.md
Labels: size/L

#2603 Update index.md
  site/en/reference/index.md
Labels: size/XS

#2602 Update index.md
  site/en/reference/index.md
Labels: size/XS

#2604 add milvus-migration docs
  assets/milvus-migration-architecture.jpeg
  site/en/migrate/es2m.md
  site/en/migrate/f2m.md
  site/en/migrate/m2m.md
  site/en/migrate/migrate_overview.md
  site/en/migrate/milvusdm_install.md
  site/en/release_notes.md
Labels: size/XL

#2606 update release notes
  site/en/release_notes.md
Labels: size/L

#2607 Fix typos in integrate_with_voyageai.md
  site/en/integrations/integrate_with_voyageai.md
Labels: size/S

#2601 Update multi-vector-search.md
  site/en/userGuide/search-query-get/multi-vector-search.md
Labels: size/S

#2595 change package version to 2.3.16
  site/en/getstarted/standalone/install_standalone-aptyum.md
Labels: size/XS

#2585 Fix the grammatical errors in `with-iterators.md`.
  site/en/userGuide/search-query-get/with-iterators.md
Labels: size/S

#2583 Update min go/node.js version to sdk docs
  site/en/getstarted/install_SDKs/install-go.md
  site/en/getstarted/install_SDKs/install-node.md
Labels: size/XS

#2542 Update milvus_lite.md #2541
  site/en/getstarted/milvus_lite.md
Labels: size/XS

#2608 Update release_notes.md
  site/en/release_notes.md
Labels: size/L

#2610 Update release_notes.md
  site/en/release_notes.md
Labels: size/L

#2611 Update Variables.json
  site/en/Variables.json
Labels: size/S

#2613 V2.4.3 anthony
  site/en/getstarted/quickstart.md
  site/en/integrations/integrate_with_bentoml.md
  site/en/integrations/integrate_with_dspy.md
  site/en/integrations/integrate_with_haystack.md
  site/en/integrations/integrate_with_hugging-face.md
  site/en/integrations/integrate_with_jina.md
  site/en/integrations/integrate_with_langchain.md
  site/en/integrations/integrate_with_langfuse.md
  site/en/integrations/integrate_with_openai.md
  site/en/integrations/integrate_with_ragas.md
  site/en/integrations/integrate_with_voyageai.md
  site/en/menuStructure/en.json
  site/en/tutorials/build-rag-with-milvus.md
  site/en/tutorials/image_similarity_search.md
Labels: size/XXL

#2615 update docs
  site/en/getstarted/quickstart.md
  site/en/integrations/integrate_with_haystack.md
  site/en/integrations/integrate_with_hugging-face.md
  site/en/integrations/integrate_with_langchain.md
  site/en/integrations/integrate_with_langfuse.md
  site/en/integrations/integrate_with_llamaindex.md
  site/en/integrations/integrate_with_ragas.md
  site/en/integrations/integrate_with_voyageai.md
  site/en/tutorials/build-rag-with-milvus.md
  site/en/tutorials/image_similarity_search.md
Labels: size/L

#2614 Update integrate_with_jina.md
  site/en/integrations/integrate_with_jina.md
Labels: size/M

#2616 update docs
  site/en/integrations/integrate_with_memgpt.md
  site/en/menuStructure/en.json
Labels: size/L

#2617 V2.4.3 anthony
  site/en/integrations/integrate_with_jina.md
  site/en/menuStructure/en.json
Labels: size/S

#2619 add link to sdk ref
  site/en/reference/array_data_type.md
  site/en/reference/sparse_vector.md
  site/en/userGuide/data-import/import-data.md
  site/en/userGuide/data-import/prepare-source-data.md
  site/en/userGuide/enable-dynamic-field.md
  site/en/userGuide/insert-update-delete.md
  site/en/userGuide/manage-collections.md
  site/en/userGuide/manage-indexes/index-scalar-fields.md
  site/en/userGuide/manage-indexes/index-vector-fields.md
  site/en/userGuide/manage-indexes/index-with-gpu.md
  site/en/userGuide/manage-partitions.md
  site/en/userGuide/manage_databases.md
  site/en/userGuide/search-query-get/get-and-scalar-query.md
  site/en/userGuide/search-query-get/with-iterators.md
  site/en/userGuide/use-json-fields.md
  site/en/userGuide/use-partition-key.md
Labels: size/XXL

#2621 update release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/S

#2622 update release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/S
