Repository milvus-io/milvus-docs, pull requests merged in 2024-01, with the labels that each got.

#2395 refine the meaning of Request Success Rate and Request Failed Rate
  site/en/adminGuide/monitor/metrics_dashboard.md
Labels: size/XS

#2393 add access log configs
  site/en/Variables.json
  site/en/adminGuide/configure_access_logs.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/reference/sys_config/configure_proxy.md
  site/en/release_notes.md
Labels: size/L

#2396 update menu
  site/en/menuStructure/en.json
Labels: size/S

#2398 Fix a typo for _resource_groups parameter of load()
  site/en/adminGuide/resource_group.md
Labels: size/S

#2399 Add minimal standalone mode for docker
  site/en/getstarted/standalone/install_standalone-docker.md
Labels: size/S

#2394 Add Haystack Integration page
  site/en/integrations/integrate_with_haystack.md
Labels: size/L

#2401 update docs
  site/en/Variables.json
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/menuStructure/en.json
  site/en/release_notes.md
Labels: size/M

#2402 update operator versions
  site/en/Variables.json
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-gpu-docker.md
Labels: size/L

#2403 Update cli doc
  site/en/userGuide/tools/cli_commands.md
  site/en/userGuide/tools/cli_overview.md
Labels: size/S

#2404 fix docker install
  site/en/getstarted/standalone/install_standalone-docker.md
  site/en/getstarted/standalone/install_standalone-operator.md
Labels: size/M

#2405 add deb package
  site/en/getstarted/standalone/install_standalone-aptyum.md
Labels: size/M

#2406 update docs
  site/en/getstarted/cluster/install_cluster-gpu-helm.md
  site/en/getstarted/cluster/install_cluster-helm.md
  site/en/getstarted/standalone/install_standalone-gpu-helm.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/userGuide/manage_connection.md
Labels: size/XL

#2409 add integrations with fiftyone
  site/en/integrations/integrate_with_voxel51.md
  site/en/menuStructure/en.json
Labels: size/L

#2410 update menu
  site/en/menuStructure/en.json
Labels: size/XS

#2411 Update disk_index.md
  site/en/reference/disk_index.md
Labels: size/XS

#2412 Release notes for v2.3.6
  site/en/Variables.json
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/integrations/integrate_with_langchain.md
  site/en/integrations/integrate_with_llamaindex.md
  site/en/menuStructure/en.json
  site/en/release_notes.md
Labels: size/L

#2413 update docs
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2414 Update the privilege list for alias and partitions
  site/en/reference/users_and_roles.md
Labels: size/S

#2415 add doc
  site/en/Variables.json
  site/en/adminGuide/chunk_cache.md
  site/en/adminGuide/limit_collection_counts.md
  site/en/faq/product_faq.md
  site/en/menuStructure/en.json
  site/en/reference/index.md
  site/en/release_notes.md
  site/en/userGuide/load_collection.md
  site/en/userGuide/search/search.md
Labels: size/L

#2416 update docs
  site/en/adminGuide/message_storage_operator.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
Labels: size/XS

#2417 update docs
  site/en/Variables.json
  site/en/adminGuide/chunk_cache.md
  site/en/release_notes.md
Labels: size/S

#2419 Update integrate_with_openai.md
  site/en/integrations/integrate_with_openai.md
Labels: size/S

#2418 Update integrate_with_llamaindex.md
  site/en/integrations/integrate_with_llamaindex.md
Labels: size/S
