Repository milvus-io/milvus-docs, pull requests merged in 2024-11, with the labels that each got.

#2847 update docs
  assets/private_gpt_ui.png
  site/en/integrations/RAG_with_pii_and_milvus.md
  site/en/integrations/integrations_overview.md
  site/en/integrations/rag_with_milvus_and_unstructured.md
  site/en/integrations/use_milvus_in_private_gpt.md
  site/en/menuStructure/en.json
  site/en/tutorials/contextual_retrieval_with_milvus.md
  site/en/tutorials/movie_recommendation_with_milvus.md
  site/en/tutorials/tutorials-overview.md
Labels: size/XXL

#2854 Update RAG_with_pii_and_milvus.md
  site/en/integrations/RAG_with_pii_and_milvus.md
Labels: size/XS

#2860 update errors
  site/en/menuStructure/en.json
  site/en/tutorials/movie_recommendation_with_milvus.md
Labels: size/S

#2862 Update product_faq.md to correct the description about load and data …
  site/en/faq/product_faq.md
Labels: size/S

#2867 update docs
  site/en/menuStructure/en.json
  site/en/reference/users_and_roles.md
Labels: size/S

#2858 update index-scalar-fields document
  site/en/userGuide/manage-indexes/index-scalar-fields.md
Labels: size/XS

#2857 update manage-partitions.md
  site/en/userGuide/manage-partitions.md
Labels: size/XS

#2851 Update disk_index.md
  site/en/reference/disk_index.md
Labels: size/XS

#2856 update manage-collections document
  site/en/userGuide/manage-collections.md
Labels: size/XS

#2855 update schema document
  site/en/reference/schema.md
Labels: size/XS

#2848 Update tutorials-overview.md
  site/en/tutorials/tutorials-overview.md
Labels: size/XS

#2850 Fix Typo Milvu instead of Milvus
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
Labels: size/XS

#2825 Update knowhere.md
  site/en/reference/knowhere.md
Labels: size/M

#2869 fix script error in migrating data
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
Labels: size/S

#2870 Add prometheus and grafana to milvus standalone docker compose for monitoring
  assets/standalone-monitoring/docker-compose.yml
  assets/standalone-monitoring/grafana/dashboard.yml
  assets/standalone-monitoring/grafana/dashboards/milvus-standalone-dashboard.json
  assets/standalone-monitoring/grafana/datasource.yml
  assets/standalone-monitoring/milvus.yaml
  assets/standalone-monitoring/prometheus/alert_rules.yml
  assets/standalone-monitoring/prometheus/prometheus.yml
Labels: size/XXL, lgtm

#2872 update docs
  assets/doscgpt_ui.png
  assets/funnel-search.png
  assets/knowlege_table.png
  assets/results-ferris-buellers-day-off.png
  assets/results-raiders-of-the-lost-ark.png
  assets/results-the-shining.png
  assets/sambanava_ui.png
  site/en/integrations/integrations_overview.md
  site/en/integrations/knowledge_table_with_milvus.md
  site/en/integrations/quickstart_mem0_with_milvus.md
  site/en/integrations/use_milvus_in_docsgpt.md
  site/en/integrations/use_milvus_in_private_gpt.md
  site/en/integrations/use_milvus_with_sambanova.md
  site/en/menuStructure/en.json
  site/en/tutorials/funnel_search_with_matryoshka.md
  site/en/tutorials/tutorials-overview.md
Labels: size/XXL

#2873 update doc for upgrade with helm, fix typo in upgrade with operator
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-operator.md
Labels: size/M, lgtm

#2875 Update metric.md
  site/en/reference/metric.md
Labels: size/XS

#2876 Update index.md
  site/en/reference/index.md
Labels: size/XS

#2877 Update index-vector-fields.md
  site/en/userGuide/manage-indexes/index-vector-fields.md
Labels: size/XS

#2874 update rn for 2.4.17 release
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2879 update roadmap & variables
  site/en/Variables.json
  site/en/about/roadmap.md
Labels: size/M

#2880 update 2.5.0-beta release notes
  site/en/menuStructure/en.json
  site/en/release_notes.md
  site/en/userGuide/manage-indexes/bitmap.md
  site/en/userGuide/manage-indexes/index-scalar-fields.md
Labels: size/XXL

#2881 update docs
  site/en/userGuide/collections/load-and-release.md
  site/en/userGuide/collections/manage-collections.md
  site/en/userGuide/collections/manage-partitions.md
  site/en/userGuide/collections/modify-collection.md
  site/en/userGuide/schema/schema.md
  site/en/userGuide/search-query-get/filtered-search.md
  site/en/userGuide/search-query-get/metric.md
  site/en/userGuide/search-query-get/single-vector-search.md
Labels: size/M

#2884 fix doc bugs
  site/en/userGuide/search-query-get/consistency.md
Labels: size/S

#2885 fix doc bugs
  site/en/userGuide/search-query-get/boolean.md
Labels: size/XS

#2887 upgrade-pulsar-v3: fix format
  site/en/adminGuide/upgrade-pulsar-v3.md
Labels: size/M

#2891 add multi-language code for text match & full text search
  assets/keyword-match.png
  site/en/userGuide/search-query-get/full-text-search.md
  site/en/userGuide/search-query-get/keyword-match.md
Labels: size/XL
