Repository milvus-io/milvus-docs, pull requests merged in 2025-02, with the labels that each got.

#3008 Update basic-operators.md
  site/en/userGuide/search-query-get/boolean/basic-operators.md
Labels: size/M

#3007 Update dify_with_milvus.md to fix the MILVUS_URI setting.
  site/en/integrations/dify_with_milvus.md
Labels: size/S

#3009 update rbac
  site/en/adminGuide/grant_privileges.md
  site/en/adminGuide/privilege_group.md
  site/en/adminGuide/rbac.md
  site/en/menuStructure/en.json
Labels: size/L

#3010 Update rbac
  site/en/menuStructure/en.json
Labels: size/S

#3013 update nullable-and-default
  site/en/userGuide/schema/nullable-and-default.md
Labels: size/S

#3014 Update use-partition-key.md
  site/en/userGuide/search-query-get/use-partition-key.md
Labels: size/XS

#3015 update migration
  site/en/about/overview.md
  site/en/adminGuide/backup/h2m.md
  site/en/adminGuide/backup/m2h.md
  site/en/adminGuide/m2m_legacy.md
  site/en/getstarted/offline/install_offline-helm.md
  site/en/menuStructure/en.json
  site/en/migrate/es2m.md
  site/en/migrate/f2m.md
  site/en/migrate/from-m2x.md
  site/en/migrate/m2m.md
  site/en/migrate/migrate_overview.md
  site/en/migrate/milvusdm_install.md
Labels: size/XL

#3016 update docs
  site/en/about/overview.md
  site/en/adminGuide/backup/h2m.md
  site/en/adminGuide/backup/m2h.md
  site/en/adminGuide/m2m_legacy.md
  site/en/getstarted/offline/install_offline-helm.md
  site/en/menuStructure/en.json
  site/en/migrate/es2m.md
  site/en/migrate/f2m.md
  site/en/migrate/from-m2x.md
  site/en/migrate/m2m.md
  site/en/migrate/migrate_overview.md
  site/en/migrate/milvusdm_install.md
Labels: size/XL

#3017 update index types supported for grouping search & remove group_size …
  site/en/userGuide/search-query-get/single-vector-search.md
Labels: size/S

#3018 update index types supported for grouping search
  site/en/userGuide/search-query-get/grouping-search.md
Labels: size/XS

#3019 update milvus limits
  site/en/about/limitations.md
Labels: size/XS

#3021 update 2.4.22 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#3023 fix helm doc
  site/en/getstarted/offline/install_offline-helm.md
  site/en/getstarted/run-milvus-gpu/install_cluster-helm-gpu.md
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/getstarted/with_gpu/install_standalone-helm-gpu.md
Labels: size/S

#3025 update variables
  site/en/Variables.json
Labels: size/XS

#3029 update 2.5.5 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/L

#3031 update Milvus cli docs
  site/en/userGuide/tools/cli_commands.md
  site/en/userGuide/tools/cli_overview.md
  site/en/userGuide/tools/install_cli.md
Labels: size/S

#3024 integrated model2vec embedding
  site/en/embeddings/embed-with-model2vec.md
Labels: size/L

#3033 update index-scalar-fields.md
  site/en/userGuide/manage-indexes/index-scalar-fields.md
Labels: size/XS
