Repository milvus-io/milvus-docs, pull requests merged in 2025-08, with the labels that each got.

#3261 update 2.6.0 upgrade guide
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
Labels: size/XL

#3263 update 2.6.0 upgrade guide
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-operator.md
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
Labels: size/M

#3264 update docs
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker.md
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
Labels: size/M

#3265 update docs
  site/en/getstarted/run-milvus-docker/install_standalone-docker.md
Labels: size/XS

#3268 update 2.6.0 upgrade & installation guide
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-docker.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-operator.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker.md
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
Labels: size/L

#3269 update 2.6.0 upgrade guide
  site/en/Variables.json
  site/en/adminGuide/upgrade_milvus_standalone-docker.md
Labels: size/M

#3270 update 2.6.0 upgrade guide
  site/en/adminGuide/upgrade_milvus_standalone-docker.md
Labels: size/XS

#3273 update 2.5.16 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#3279 Update diskann.md
  site/en/userGuide/indexes/floating-vector/diskann.md
Labels: size/S

#3289 Update Grafana Loki Configuration with Alloy
  assets/monitoring/logging_HostVolume.png
  assets/monitoring/logging_K8sApi.png
  site/en/adminGuide/monitor/configure_grafana_loki.md
Labels: size/L
