Repository milvus-io/milvus-docs, pull requests merged in 2025-06, with the labels that each got.

#3176 update docs
  assets/data-model-anatomy.png
  assets/hybrid-search-workflow.png
  assets/sparse-vector-representation.png
  assets/sparse-vector-workflow.png
  scripts/config.json
  site/en/getstarted/schema-hands-on.md
  site/en/menuStructure/en.json
  site/en/userGuide/schema/schema-hands-on.md
  site/en/userGuide/schema/sparse_vector.md
  site/en/userGuide/search-query-get/multi-vector-search.md
Labels: size/XXL

#3177 update docs
  site/en/menuStructure/en.json
Labels: size/S

#3182 fix: 2.6.x docs
  assets/exp-decay.png
  assets/gaussian-decay.png
  assets/gpu-index-performance.png
  assets/inverted.png
  site/en/userGuide/embeddings-reranking/embedding-function/embedding-function-overview.md
  site/en/userGuide/embeddings-reranking/reranking/decay-ranker-overview.md
  site/en/userGuide/embeddings-reranking/reranking/exponential-decay.md
  site/en/userGuide/embeddings-reranking/reranking/gaussian-decay.md
  site/en/userGuide/embeddings-reranking/reranking/linear-decay.md
  site/en/userGuide/embeddings-reranking/reranking/rrf-ranker.md
  site/en/userGuide/embeddings-reranking/reranking/weighted-ranker.md
  site/en/userGuide/indexes/binary/bin-flat.md
  site/en/userGuide/indexes/floating-vector/diskann.md
  site/en/userGuide/indexes/floating-vector/hnsw-pq.md
  site/en/userGuide/indexes/floating-vector/hnsw-prq.md
  site/en/userGuide/indexes/floating-vector/hnsw.md
  site/en/userGuide/indexes/floating-vector/ivf-rabitq.md
  site/en/userGuide/indexes/gpu/gpu-brute-force.md
  site/en/userGuide/indexes/gpu/gpu-cagra.md
  site/en/userGuide/indexes/gpu/gpu-index-overview.md
  site/en/userGuide/indexes/gpu/gpu-ivf-flat.md
  site/en/userGuide/indexes/gpu/gpu-ivf-pq.md
  site/en/userGuide/indexes/scalar/inverted.md
Labels: size/M

#3184 merge: integrate v2.5.x documentation fixes into v2.6.x
  site/en/userGuide/schema/use-json-fields.md
Labels: size/S

#3187 Add support for configuring RRF and weighted ranker through Function
  site/en/userGuide/embeddings-reranking/reranking/rrf-ranker.md
  site/en/userGuide/embeddings-reranking/reranking/weighted-ranker.md
Labels: size/L

#3188 update menuStructure for woodpecker
  site/en/menuStructure/en.json
Labels: size/XS

#3190 Update reranking documentation and menu structure
  site/en/menuStructure/en.json
  site/en/userGuide/embeddings-reranking/reranking/exponential-decay.md
  site/en/userGuide/embeddings-reranking/reranking/gaussian-decay.md
  site/en/userGuide/embeddings-reranking/reranking/linear-decay.md
Labels: size/M

#3191 feat: streaming arch
  assets/message_order.png
  assets/milvus_architecture_2_6.png
  assets/pvchannel_wal.png
  assets/query_operation.png
  assets/recovery_storage.png
  assets/streaming_distributed_arch.png
  assets/streaming_wait_for_ready.png
  assets/wal_lifetime.png
  assets/written_data_flow.png
  site/en/reference/architecture/architecture_overview.md
  site/en/reference/architecture/data_processing.md
  site/en/reference/architecture/four_layers.md
  site/en/reference/architecture/main_components.md
  site/en/reference/architecture/streaming_service.md
Labels: size/L

#3194 merge: integrate 2.5.x changes to 2.6.x
  site/en/Variables.json
  site/en/getstarted/install-overview.md
Labels: size/XS

#3195 update: replace legacy arch diagrams
  assets/channels_1.jpg
  assets/distributed_architecture.jpg
  assets/handoff.jpg
  assets/index_building.jpg
  assets/standalone_architecture.jpg
Labels: size/XS

#3198 update: home & tei-ranker
  site/en/home/home.md
  site/en/userGuide/embeddings-reranking/reranking/tei-ranker.md
Labels: size/S

#3200 update: arch diagrams & variables
  assets/handoff.jpg
  site/en/Variables.json
Labels: size/XS

#3201 update arch docs
  site/en/menuStructure/en.json
  site/en/reference/architecture/architecture_overview.md
  site/en/reference/architecture/streaming_service.md
  site/en/reference/architecture/woodpecker_architecture.md
  site/en/reference/glossary.md
Labels: size/L

#3203 integrate v2.5.x changes into v2.6.x
  site/en/userGuide/search-query-get/full-text-search.md
Labels: size/M

#3204 update: model ranker params
  site/en/userGuide/embeddings-reranking/reranking/model-ranker-overview.md
  site/en/userGuide/embeddings-reranking/reranking/tei-ranker.md
  site/en/userGuide/embeddings-reranking/reranking/vllm-ranker.md
Labels: size/M

#3206 update: 2.6.x docs
  assets/channels_1.jpg
  assets/channels_1.png
  assets/distributed_architecture.jpg
  assets/distributed_architecture.png
  assets/handoff.jpg
  assets/handoff.png
  assets/index_building.jpg
  assets/index_building.png
  assets/milvus_architecture_2_6.png
  assets/pvchannel_wal.png
  assets/standalone_architecture.jpg
  assets/standalone_architecture.png
  assets/written_data_flow.png
  site/en/reference/architecture/data_processing.md
  site/en/reference/architecture/main_components.md
  site/en/userGuide/embeddings-reranking/embedding-function/embedding-function-overview.md
  site/en/userGuide/embeddings-reranking/embedding-function/vertex-ai.md
Labels: size/L

#3207 update: 2.6.x docs
  site/en/userGuide/embeddings-reranking/embedding-function/embedding-function-overview.md
  site/en/userGuide/embeddings-reranking/embedding-function/vertex-ai.md
  site/en/userGuide/embeddings-reranking/reranking/decay-ranker-overview.md
Labels: size/M

#3208 add: 2.6.0-rc1 release notes
  site/en/Variables.json
  site/en/release_notes.md
  site/en/userGuide/schema/dense-vector.md
Labels: size/L

#3210 update: 2.6.x docs
  site/en/reference/schema.md
  site/en/userGuide/indexes/index-explained.md
Labels: size/XS

#3212 chore: update v2.6.x workflows
  .github/workflows/ci.yml
  .github/workflows/preview.yml
Labels: size/XS

#3169 Update configure-helm.md
  site/en/adminGuide/configure-helm.md
Labels: size/XS

#3215 Update doc
  site/en/about/overview.md
  site/en/reference/architecture/main_components.md
  site/en/userGuide/collections/set-collection-ttl.md
Labels: size/M

#3216 improve woodpecker architecture description
  site/en/reference/architecture/woodpecker_architecture.md
Labels: size/XS

#3217 update docs
  site/en/about/overview.md
Labels: size/XS

#3218 update docs
  site/en/about/overview.md
Labels: size/XS

#3222 update full-text-search.md
  site/en/userGuide/search-query-get/full-text-search.md
Labels: size/S

#3223 Update quickstart_with_attu.md
  site/en/tutorials/quickstart_with_attu.md
Labels: size/XS

#3179 fix milvus > 2.5 go sdk path
  site/en/getstarted/install_SDKs/install-go.md
Labels: size/XS

#3205 enhance: update v2.5.x configurations documents
  site/en/reference/sys_config/configure_common.md
  site/en/reference/sys_config/configure_datacoord.md
  site/en/reference/sys_config/configure_grpc.md
  site/en/reference/sys_config/configure_indexnode.md
  site/en/reference/sys_config/configure_mq.md
  site/en/reference/sys_config/configure_querycoord.md
  site/en/reference/sys_config/configure_querynode.md
  site/en/reference/sys_config/configure_quotaandlimits.md
Labels: size/XL

#3143 Fix typos
  assets/standalone-monitoring/grafana/dashboards/milvus-standalone-dashboard.json
  site/en/integrations/integrate_with_camel.md
  site/en/reference/architecture/architecture.md
  site/en/reference/schema.md
  site/en/tutorials/text_image_search.md
  site/en/userGuide/collections/create-collection.md
  site/en/userGuide/schema/schema.md
  site/en/userGuide/using_milvusclient.md
Labels: size/S

#3224 update docs
  site/en/userGuide/indexes/index-explained.md
  site/en/userGuide/schema/binary-vector.md
Labels: size/M
