Repository milvus-io/milvus-docs, pull requests merged in 2025-09, with the labels that each got.

#3294 add connection guide
  site/en/getstarted/connect-to-milvus-server.md
  site/en/menuStructure/en.json
Labels: size/L

#3295 add time unit notes to decay ranker docs
  site/en/userGuide/embeddings-reranking/reranking/decay-ranker-overview.md
  site/en/userGuide/embeddings-reranking/reranking/exponential-decay.md
  site/en/userGuide/embeddings-reranking/reranking/linear-decay.md
Labels: size/M

#3296 update docs for 2.6.1 release
  site/en/menuStructure/en.json
  site/en/release_notes.md
  site/en/userGuide/embeddings-reranking/reranking/cohere-ranker.md
  site/en/userGuide/embeddings-reranking/reranking/model-ranker-overview.md
  site/en/userGuide/embeddings-reranking/reranking/siliconflow-ranker.md
  site/en/userGuide/embeddings-reranking/reranking/tei-ranker.md
  site/en/userGuide/embeddings-reranking/reranking/vllm-ranker.md
  site/en/userGuide/embeddings-reranking/reranking/voyage-ai-ranker.md
Labels: size/XXL

#3297 update json field docs
  site/en/userGuide/schema/use-json-fields.md
Labels: size/L

#3298 update docs
  scripts/lib/larkDocWriter.js
  scripts/lib/milvusDocsGen.js
  site/en/userGuide/schema/analyzer/analyzer/standard-analyzer.md
  site/en/userGuide/schema/analyzer/tokenizer/standard-tokenizer.md
Labels: size/XL

#3303 merge v2.6.x changes to preview
  .github/workflows/preview.yml
  assets/standalone-monitoring/docker-compose.yml
  scripts/lib/larkDocWriter.js
  scripts/lib/milvusDocsGen.js
  site/en/Variables.json
  site/en/adminGuide/deploy_pulsar.md
  site/en/adminGuide/monitor/alert.md
  site/en/adminGuide/monitor/configure_grafana_loki.md
  site/en/adminGuide/upgrade_milvus_cluster-helm.md
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-docker.md
  site/en/adminGuide/upgrade_milvus_standalone-helm.md
  site/en/adminGuide/upgrade_milvus_standalone-operator.md
  site/en/adminGuide/use-woodpecker.md
  site/en/faq/operational_faq.md
  site/en/faq/performance_faq.md
  site/en/faq/product_faq.md
  site/en/faq/troubleshooting.md
  site/en/getstarted/connect-to-milvus-server.md
  site/en/getstarted/run-milvus-docker/install_standalone-binary.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker.md
  site/en/getstarted/run-milvus-docker/prerequisite-docker.md
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
  site/en/getstarted/run-milvus-k8s/prerequisite-helm.md
  site/en/menuStructure/en.json
  site/en/release_notes.md
  site/en/tutorials/build-rag-with-milvus.md
  site/en/userGuide/data-import/prepare-source-data.md
  site/en/userGuide/embeddings-reranking/reranking/cohere-ranker.md
  site/en/userGuide/embeddings-reranking/reranking/decay-ranker-overview.md
  site/en/userGuide/embeddings-reranking/reranking/exponential-decay.md
  site/en/userGuide/embeddings-reranking/reranking/linear-decay.md
  site/en/userGuide/embeddings-reranking/reranking/model-ranker-overview.md
  site/en/userGuide/embeddings-reranking/reranking/siliconflow-ranker.md
  site/en/userGuide/embeddings-reranking/reranking/tei-ranker.md
  site/en/userGuide/embeddings-reranking/reranking/vllm-ranker.md
  site/en/userGuide/embeddings-reranking/reranking/voyage-ai-ranker.md
  site/en/userGuide/indexes/floating-vector/diskann.md
  site/en/userGuide/indexes/gpu/gpu-cagra.md
  site/en/userGuide/manage_databases.md
  site/en/userGuide/schema/analyzer/analyzer/standard-analyzer.md
  site/en/userGuide/schema/analyzer/tokenizer/standard-tokenizer.md
  site/en/userGuide/schema/array_data_type.md
  site/en/userGuide/schema/nullable-and-default.md
  site/en/userGuide/schema/sparse_vector.md
  site/en/userGuide/schema/use-json-fields.md
  site/en/userGuide/search-query-get/boolean/basic-operators.md
  site/en/userGuide/search-query-get/full-text-search.md
  site/en/userGuide/tools/milvus-backup/milvus_backup_overview.md
Labels: size/XXL

#3304 update docs for 2.6.2 release
  assets/accelerate-queries.png
  assets/analyzer-workflow.png
  assets/birdwatcher-output.png
  assets/boost-ranker-mechanism.png
  assets/build-ngram-index-2.png
  assets/build-ngram-index.png
  assets/json-shredding-flow.png
  assets/language-detection-workflow.png
  assets/upsert-in-merge-mode.png
  assets/upsert-in-override-mode.png
  scripts/config.json
  site/en/menuStructure/en.json
  site/en/userGuide/embeddings-reranking/reranking/boost-ranker.md
  site/en/userGuide/indexes/scalar/ngram.md
  site/en/userGuide/insert-and-delete/upsert-entities.md
  site/en/userGuide/schema/analyzer/choose-the-right-analyzer-for-your-use-case.md
  site/en/userGuide/schema/analyzer/tokenizer/language-identifier.md
  site/en/userGuide/schema/json-field-overview.md
  site/en/userGuide/schema/json-indexing.md
  site/en/userGuide/schema/json-shredding.md
  site/en/userGuide/schema/string.md
  site/en/userGuide/search-query-get/boolean/basic-operators.md
Labels: size/XXL

#3305 change phrase match compatibility version to 2.5.17+
  site/en/userGuide/search-query-get/phrase-match.md
Labels: size/XS

#3307 add phrase match
  assets/phrase-match-workflow.png
  scripts/config.json
  site/en/menuStructure/en.json
  site/en/userGuide/search-query-get/phrase-match.md
Labels: size/L

#3309 update docs
  site/en/userGuide/embeddings-reranking/embedding-function/cohere.md
  site/en/userGuide/embeddings-reranking/embedding-function/dashscope.md
  site/en/userGuide/embeddings-reranking/embedding-function/embedding-function-overview.md
  site/en/userGuide/embeddings-reranking/embedding-function/openai.md
  site/en/userGuide/embeddings-reranking/embedding-function/siliconflow.md
  site/en/userGuide/embeddings-reranking/embedding-function/voyage-ai.md
Labels: size/S

#3310 update inverted index
  assets/how-inverted-index-works.png
  scripts/config.json
  site/en/userGuide/indexes/scalar/inverted.md
Labels: size/S

#3311 sync v2.6.x changes to preview
  assets/how-inverted-index-works.png
  scripts/config.json
  site/en/integrations/integrate_with_llamaindex.md
  site/en/userGuide/embeddings-reranking/embedding-function/cohere.md
  site/en/userGuide/embeddings-reranking/embedding-function/dashscope.md
  site/en/userGuide/embeddings-reranking/embedding-function/embedding-function-overview.md
  site/en/userGuide/embeddings-reranking/embedding-function/openai.md
  site/en/userGuide/embeddings-reranking/embedding-function/siliconflow.md
  site/en/userGuide/embeddings-reranking/embedding-function/voyage-ai.md
  site/en/userGuide/indexes/scalar/inverted.md
  site/en/userGuide/search-query-get/phrase-match.md
Labels: size/M

#3312 update docs for 2.6.2 release
  assets/accelerate-queries.png
  assets/analyzer-workflow.png
  assets/birdwatcher-output.png
  assets/boost-ranker-mechanism.png
  assets/build-ngram-index-2.png
  assets/build-ngram-index.png
  assets/json-shredding-flow.png
  assets/language-detection-workflow.png
  assets/upsert-in-merge-mode.png
  assets/upsert-in-override-mode.png
  scripts/config.json
  site/en/Variables.json
  site/en/getstarted/schema-hands-on.md
  site/en/menuStructure/en.json
  site/en/release_notes.md
  site/en/userGuide/embeddings-reranking/reranking/boost-ranker.md
  site/en/userGuide/indexes/scalar/ngram.md
  site/en/userGuide/insert-and-delete/upsert-entities.md
  site/en/userGuide/schema/analyzer/choose-the-right-analyzer-for-your-use-case.md
  site/en/userGuide/schema/analyzer/tokenizer/language-identifier.md
  site/en/userGuide/schema/json-field-overview.md
  site/en/userGuide/schema/json-indexing.md
  site/en/userGuide/schema/json-shredding.md
  site/en/userGuide/schema/string.md
  site/en/userGuide/search-query-get/boolean/basic-operators.md
Labels: size/XXL

#3313 update 2.5.18 rn
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#3316 update docs
  site/en/integrations/integrations_overview.md
  site/en/integrations/langextract_milvus_demo.md
  site/en/menuStructure/en.json
  site/en/tutorials/generating_milvus_query_filter_expressions.md
  site/en/tutorials/multimodal_rag_with_milvus.md
  site/en/tutorials/tutorials-overview.md
Labels: size/XL

#3317 update docs
  site/en/adminGuide/upgrade_milvus_standalone-docker.md
Labels: size/XS
