Repository milvus-io/milvus-docs, pull requests merged in 2025-03, with the labels that each got.

#3035 update 2.4.23 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#3037 update docs
  .gitignore
  assets/partition-vs-partition-key.png
  site/en/adminGuide/grant_privileges.md
  site/en/integrations/ETL_using_vectorETL.md
  site/en/integrations/build_RAG_from_s3_with_milvus.md
  site/en/integrations/langchain/integrate_with_langchain.md
  site/en/menuStructure/en.json
  site/en/userGuide/search-query-get/use-partition-key.md
Labels: size/L

#3038 Update build_RAG_from_s3_with_milvus.md
  site/en/integrations/build_RAG_from_s3_with_milvus.md
Labels: size/XS

#3039 Update integrate_with_langchain.md
  site/en/integrations/langchain/integrate_with_langchain.md
Labels: size/XS

#3040 update roadmap
  site/en/about/roadmap.md
Labels: size/M

#3044 update 2.5.6 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#3045 Update full_text_search_with_milvus.md intro
  site/en/tutorials/full_text_search_with_milvus.md
Labels: size/XS

#3046 update docs
  site/en/integrations/integrate_with_phidata.md
  site/en/integrations/integrations_overview.md
  site/en/integrations/llama_stack_with_milvus.md
  site/en/integrations/llamaindex_milvus_async.md
  site/en/menuStructure/en.json
  site/en/tutorials/hybrid_search_with_milvus.md
  site/en/tutorials/multimodal_rag_with_milvus.md
Labels: size/XL

#3047 add github actions doc.yml
  .github/workflows/doc.yml
  .gitignore
  assets/analyzer-process-workflow.png
  scripts/config.json
  scripts/index.js
  scripts/lib/larkDocScraper.js
  scripts/lib/larkDocWriter.js
  scripts/lib/larkDriveWriter.js
  scripts/lib/larkImageDownloader.js
  scripts/lib/larkTokenFetcher.js
  scripts/lib/larkUtils.js
  scripts/lib/milvusDocsGen.js
  scripts/package-lock.json
  scripts/package.json
  scripts/report.js
  scripts/yarn.lock
  site/en/userGuide/schema/analyzer/analyzer-overview.md
  site/en/userGuide/schema/analyzer/tokenizer/jieba-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/standard-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/whitespace-tokenizer.md
Labels: size/XXL

#3057 Update integrate_with_phidata.md
  site/en/integrations/integrate_with_phidata.md
Labels: size/XS

#3058 update docs
  site/en/integrations/integration_with_mindsdb.md
  site/en/integrations/integrations_overview.md
  site/en/integrations/milvus_and_mcp.md
  site/en/integrations/openai_agents_milvus.md
  site/en/menuStructure/en.json
Labels: size/XL

#3060 update docs
  site/en/integrations/integrate_with_agno.md
  site/en/menuStructure/en.json
Labels: size/XS

#3062 add consistency level comment
  site/en/integrations/RAG_with_pii_and_milvus.md
  site/en/integrations/build_RAG_with_milvus_and_crawl4ai.md
  site/en/integrations/build_RAG_with_milvus_and_deepseek.md
  site/en/integrations/build_RAG_with_milvus_and_firecrawl.md
  site/en/integrations/build_RAG_with_milvus_and_fireworks.md
  site/en/integrations/build_RAG_with_milvus_and_gemini.md
  site/en/integrations/build_RAG_with_milvus_and_lepton.md
  site/en/integrations/build_RAG_with_milvus_and_ollama.md
  site/en/integrations/build_RAG_with_milvus_and_siliconflow.md
  site/en/integrations/build_rag_on_arm.md
  site/en/integrations/integrate_with_ragas.md
  site/en/tutorials/build-rag-with-milvus.md
  site/en/tutorials/graph_rag_with_milvus.md
  site/en/tutorials/quickstart_with_attu.md
  site/en/tutorials/vector_visualization.md
Labels: size/M

#3064 add more consistency level comment
  site/en/integrations/evaluation_with_deepeval.md
  site/en/integrations/evaluation_with_phoenix.md
  site/en/integrations/integrate_with_hugging-face.md
  site/en/integrations/integrate_with_voxel51.md
  site/en/integrations/langchain/milvus_hybrid_search_retriever.md
  site/en/integrations/llamaindex_milvus_async.md
  site/en/integrations/rag_with_milvus_and_unstructured.md
Labels: size/S

#3066 Update hybrid_search_with_milvus.md
  site/en/tutorials/hybrid_search_with_milvus.md
Labels: size/XS

#3067 update docs for 2.5.7 release
  site/en/release_notes.md
  site/en/userGuide/schema/enable-dynamic-field.md
  site/en/userGuide/schema/use-json-fields.md
Labels: size/XXL

#3068 Update users_and_roles.md
  site/en/adminGuide/users_and_roles.md
Labels: size/XS

#3069 update bm25 index params
  site/en/userGuide/search-query-get/full-text-search.md
Labels: size/M

#3071 update sparse vector docs
  site/en/reference/index.md
  site/en/userGuide/manage-indexes/index-vector-fields.md
Labels: size/XS

#3065 Add HPA Configuration Documentation for Milvus
  site/en/adminGuide/hpa.md
  site/en/adminGuide/scaleout.md
Labels: size/L

#3042 added url to model2vec
  site/en/embeddings/embed-with-model2vec.md
Labels: size/XS

#3036 fix code example issue
  site/en/userGuide/search-query-get/full-text-search.md
Labels: size/XS

#3072 update manage_databases.md
  scripts/config.json
  site/en/userGuide/manage_databases.md
Labels: size/XL

#3073 update menu structure
  site/en/menuStructure/en.json
Labels: size/XS

#3074 Update docs
  scripts/index.js
  scripts/lib/milvusDocsGen.js
  site/en/userGuide/collections/create-collection.md
Labels: size/XXL

#3075 update create-collection-instantly.md
  site/en/userGuide/collections/create-collection-instantly.md
Labels: size/XL

#3076 update docs
  site/en/userGuide/collections/view-collections.md
Labels: size/L

#3077 update modify-collection
  site/en/userGuide/collections/modify-collection.md
Labels: size/L

#3079 update docs
  site/en/userGuide/collections/set-collection-ttl.md
Labels: size/XS

#3080 update docs
  site/en/userGuide/collections/manage-partitions.md
Labels: size/XXL

#3084 Update multimodal_rag_with_milvus.md
  site/en/tutorials/multimodal_rag_with_milvus.md
Labels: size/XS

#3082 add the gemini's tutorial md file
  site/en/embeddings/embed-with-gemini.md
Labels: size/L

#3085 update docs
  site/en/menuStructure/en.json
Labels: size/XS

#3086 update docs
  assets/image_search_with_milvus_14_1.png
  site/en/embeddings/embeddings.md
  site/en/menuStructure/en.json
  site/en/tutorials/image_similarity_search.md
Labels: size/M
