Repository milvus-io/milvus-docs, pull requests merged in 2025-07, with the labels that each got.

#3225 update 2.6 docs
  assets/message_order.png
  assets/milvus_architecture_2_6.png
  assets/recovery_storage.png
  assets/streaming_wait_for_ready.png
  assets/wal_lifetime.png
  assets/woodpecker_layers.png
  assets/woodpecker_memorybuffer_mode_deployment.png
  assets/woodpecker_quorumbuffer_mode_deployment.png
  site/en/menuStructure/en.json
  site/en/reference/architecture/woodpecker_architecture.md
  site/en/reference/tune_consistency.md
  site/en/userGuide/collections/create-collection.md
  site/en/userGuide/collections/manage-aliases.md
  site/en/userGuide/indexes/floating-vector/diskann.md
  site/en/userGuide/insert-and-delete/insert-update-delete.md
  site/en/userGuide/insert-and-delete/upsert-entities.md
  site/en/userGuide/manage_databases.md
  site/en/userGuide/schema/primary-field.md
Labels: size/L

#3227 update docs
  scripts/yarn.lock
  site/en/adminGuide/scale-standalone.md
  site/en/integrations/build_RAG_with_milvus_and_lepton.md
  site/en/integrations/dify_with_milvus.md
  site/en/integrations/langchain/basic_usage_langchain.md
  site/en/integrations/langchain/langchain_milvus_async.md
  site/en/menuStructure/en.json
Labels: size/XL

#3226 update analyzer-overview & standard-analyzer
  site/en/userGuide/schema/analyzer/analyzer-overview.md
  site/en/userGuide/schema/analyzer/analyzer/standard-analyzer.md
Labels: size/XS

#3230 update: pymilvus version
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/XS

#3232 update: java & go code for random-sampling
  site/en/userGuide/search-query-get/boolean/random-sampling.md
Labels: size/L

#3233 update: json index docs
  assets/inverted-index.png
  scripts/config.json
  site/en/userGuide/indexes/scalar/inverted.md
  site/en/userGuide/schema/enable-dynamic-field.md
  site/en/userGuide/schema/use-json-fields.md
Labels: size/XXL

#3234 fix: syntax error in python examples
  site/en/userGuide/manage_databases.md
Labels: size/XS

#3236 add: minhash lsh
  assets/lsh-workflow-1.png
  assets/lsh-workflow-2.png
  assets/lsh-workflow-3.png
  assets/minhash-workflow.png
  scripts/config.json
  site/en/menuStructure/en.json
  site/en/userGuide/indexes/binary/minhash-lsh.md
  site/en/userGuide/schema/enable-dynamic-field.md
  site/en/userGuide/schema/use-json-fields.md
  site/en/userGuide/search-query-get/boolean/boolean.md
  site/en/userGuide/search-query-get/metric.md
Labels: size/XXL

#3237 update docs
  scripts/yarn.lock
  site/en/integrations/RAG_with_pii_and_milvus.md
  site/en/integrations/build_RAG_with_milvus_and_crawl4ai.md
  site/en/integrations/build_RAG_with_milvus_and_deepseek.md
  site/en/integrations/build_RAG_with_milvus_and_docling.md
  site/en/integrations/build_RAG_with_milvus_and_firecrawl.md
  site/en/integrations/build_RAG_with_milvus_and_fireworks.md
  site/en/integrations/build_RAG_with_milvus_and_gemini.md
  site/en/integrations/build_RAG_with_milvus_and_lepton.md
  site/en/integrations/build_RAG_with_milvus_and_ollama.md
  site/en/integrations/build_RAG_with_milvus_and_siliconflow.md
  site/en/integrations/build_rag_on_arm.md
  site/en/integrations/evaluation_with_deepeval.md
  site/en/integrations/evaluation_with_phoenix.md
  site/en/integrations/full_text_search_with_milvus_and_haystack.md
  site/en/integrations/integrate_with_hugging-face.md
  site/en/integrations/integrate_with_ragas.md
  site/en/integrations/integrate_with_voxel51.md
  site/en/integrations/langchain/milvus_hybrid_search_retriever.md
  site/en/integrations/llamaindex_milvus_async.md
  site/en/integrations/rag_with_milvus_and_unstructured.md
  site/en/reference/tune_consistency.md
  site/en/tutorials/build-rag-with-milvus.md
  site/en/tutorials/graph_rag_with_milvus.md
  site/en/tutorials/hybrid_search_with_milvus.md
  site/en/tutorials/quickstart_with_attu.md
  site/en/tutorials/vector_visualization.md
  site/en/userGuide/embeddings-reranking/reranking/decay-ranker-overview.md
  site/en/userGuide/embeddings-reranking/reranking/exponential-decay.md
  site/en/userGuide/embeddings-reranking/reranking/gaussian-decay.md
  site/en/userGuide/embeddings-reranking/reranking/linear-decay.md
  site/en/userGuide/embeddings-reranking/reranking/model-ranker-overview.md
  site/en/userGuide/embeddings-reranking/reranking/tei-ranker.md
  site/en/userGuide/embeddings-reranking/reranking/tutorial-implement-a-time-based-ranking-in-milvus.md
  site/en/userGuide/embeddings-reranking/reranking/vllm-ranker.md
  site/en/userGuide/indexes/binary/minhash-lsh.md
  site/en/userGuide/schema/analyzer/multi-language-analyzers.md
Labels: size/L

#3238 update docs
  site/en/integrations/langchain/langchain_milvus_async.md
  site/en/tutorials/graph_rag_with_milvus.md
Labels: size/S

#3240 rollback: standalone-docker-compose due to woodpecker arch change
  site/en/getstarted/run-milvus-docker/install_standalone-docker-compose.md
Labels: size/XS

#3239 fix: syntax error in python examples
  site/en/userGuide/schema/alter-collection-field.md
  site/en/userGuide/schema/analyzer/tokenizer/jieba-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/lindera-tokenizer.md
Labels: size/S

#3243 update docs
  assets/cherry-studio-mcp-settings.png
  assets/code-helper-disabled.png
  assets/code-helper-enabled.png
  assets/cursor-mcp-settings.png
  scripts/config.json
  site/en/menuStructure/en.json
  site/en/userGuide/tools/milvus-sdk-helper-mcp.md
Labels: size/L

#3247 add: scann index
  assets/scann.png
  scripts/config.json
  site/en/menuStructure/en.json
  site/en/userGuide/indexes/floating-vector/scann.md
Labels: size/L

#3252 update product faq
  site/en/faq/product_faq.md
  site/en/tutorials/vector_visualization.md
Labels: size/XS
