Repository milvus-io/milvus-docs, pull requests merged in 2025-01, with the labels that each got.

#2960 update 2.4.20 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/S

#2961 add use cases to milvus-backup
  assets/cross-bucket-backup-and-restore.png
  assets/multi-storage-backup-and-restore.png
  assets/shared-bucket-backup-and-restore.png
  assets/single-instance-backup-and-restore.png
  site/en/menuStructure/en.json
  site/en/userGuide/tools/milvus-backup/common-cases/cross-bucket-backup-and-restore.md
  site/en/userGuide/tools/milvus-backup/common-cases/multi-storage-backup-and-restore.md
  site/en/userGuide/tools/milvus-backup/common-cases/shared-bucket-backup-and-restore.md
  site/en/userGuide/tools/milvus-backup/common-cases/single-instance-backup-and-restore.md
  site/en/userGuide/tools/milvus-backup/milvus_backup_api.md
  site/en/userGuide/tools/milvus-backup/milvus_backup_cli.md
  site/en/userGuide/tools/milvus-backup/milvus_backup_overview.md
Labels: size/XL

#2962 update 2.5.2 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2964 fix doc bugs in milvus-backup
  site/en/userGuide/tools/milvus-backup/milvus_backup_api.md
  site/en/userGuide/tools/milvus-backup/milvus_backup_cli.md
Labels: size/S

#2965 update index.md
  site/en/reference/index.md
Labels: size/S

#2966 update menuStructure
  site/en/menuStructure/en.json
Labels: size/M

#2967 update docs
  site/en/menuStructure/en.json
  site/en/userGuide/search-query-get/boolean/boolean.md
Labels: size/M

#2968 update limitations.md
  site/en/about/limitations.md
Labels: size/XS

#2969 update limit_collection_counts.md
  site/en/adminGuide/limit_collection_counts.md
Labels: size/XS

#2959 Update integrate_with_pytorch.md
  site/en/integrations/integrate_with_pytorch.md
Labels: size/S

#2963 Update install_standalone-windows.md
  site/en/getstarted/run-milvus-docker/install_standalone-windows.md
Labels: size/XS

#2958 Update integrate_with_langfuse.md
  site/en/integrations/integrate_with_langfuse.md
Labels: size/S

#2892 Fine tune the syntax of full text search document
  site/en/userGuide/search-query-get/full-text-search.md
Labels: size/XS

#2868 Add Go code snippets
  site/en/userGuide/manage-collections.md
Labels: size/L

#2865 Change Slack channel invites to Discord invites
  README.md
  site/en/adminGuide/monitor/alert.md
  site/en/faq/operational_faq.md
  site/en/faq/performance_faq.md
  site/en/faq/product_faq.md
  site/en/faq/troubleshooting.md
Labels: size/S

#2824 Update data_processing.md
  site/en/reference/architecture/data_processing.md
Labels: size/S

#2823 Update four_layers.md
  site/en/reference/architecture/four_layers.md
Labels: size/S

#2972 update docs
  assets/attu_after_data_insertion_1.png
  assets/attu_after_data_insertion_2.png
  assets/attu_expanded_searched_graph.png
  assets/attu_login_page.png
  assets/attu_searched_graph.png
  assets/attu_searched_table.png
  site/en/integrations/build_RAG_with_milvus_and_deepseek.md
  site/en/integrations/integrate_with_camel.md
  site/en/integrations/integrations_overview.md
  site/en/menuStructure/en.json
  site/en/tutorials/quickstart_with_attu.md
  site/en/tutorials/tutorials-overview.md
  site/en/tutorials/use-async-milvus-client-with-asyncio.md
Labels: size/XL

#2973 update 2.5.3 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2976 fix doc bug
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
Labels: size/S

#2975 Adding example to use VoyageAI's multimodal embeddings model with Milvus
  site/en/integrations/integrate_with_voyageai.md
Labels: size/L

#2979 fix invalid ref
  site/en/userGuide/collections/manage-partitions.md
Labels: size/S

#2980 update menuStructure
  site/en/menuStructure/en.json
Labels: size/S

#2981 update load-and-release
  site/en/userGuide/collections/load-and-release.md
Labels: size/XS

#2982 update faq
  site/en/faq/product_faq.md
  site/en/userGuide/schema/use-json-fields.md
Labels: size/M

#2974 update docs
  site/en/tutorials/use-async-milvus-client-with-asyncio.md
Labels: size/M

#2983 feat: updating configuration related docs
  site/en/reference/sys_config/configure_common.md
  site/en/reference/sys_config/configure_datacoord.md
  site/en/reference/sys_config/configure_datanode.md
  site/en/reference/sys_config/configure_gpu.md
  site/en/reference/sys_config/configure_internaltls.md
  site/en/reference/sys_config/configure_knowhere.md
  site/en/reference/sys_config/configure_metastore.md
  site/en/reference/sys_config/configure_minio.md
  site/en/reference/sys_config/configure_mq.md
  site/en/reference/sys_config/configure_proxy.md
  site/en/reference/sys_config/configure_pulsar.md
  site/en/reference/sys_config/configure_querycoord.md
  site/en/reference/sys_config/configure_querynode.md
  site/en/reference/sys_config/configure_quotaandlimits.md
  site/en/reference/sys_config/configure_rocksmq.md
  site/en/reference/sys_config/configure_streaming.md
  site/en/reference/sys_config/configure_streamingnode.md
  site/en/reference/sys_config/configure_tls.md
  site/en/reference/sys_config/system_configuration.md
Labels: size/XXL

#2978 Typo fix in delete-entities.md
  site/en/userGuide/insert-and-delete/delete-entities.md
Labels: size/XS

#2985 enhance: use milvus client api replace resource group demo code
  site/en/adminGuide/resource_group.md
Labels: size/M

#2988 Update kafka-connect-milvus.md
  site/en/integrations/kafka-connect-milvus.md
Labels: size/S

#2989 Update integrate_with_spark.md
  site/en/integrations/integrate_with_spark.md
Labels: size/S

#2991 Update vector_visualization.md
  site/en/tutorials/vector_visualization.md
Labels: size/XS

#2992 Update integrate_with_cohere.md
  site/en/integrations/integrate_with_cohere.md
Labels: size/XS

#2990 Improve documentation for RocksMQ
  site/en/adminGuide/message_storage_operator.md
Labels: size/S

#2995 update docs for 2.4.21 release
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#2996 update operator docs
  site/en/Variables.json
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-operator.md
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
Labels: size/M

#2997 update operator docs
  site/en/Variables.json
  site/en/adminGuide/upgrade_milvus_cluster-operator.md
  site/en/adminGuide/upgrade_milvus_standalone-operator.md
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
Labels: size/M

#2994 update docs
  assets/hybrid_and_rerank.png
  site/en/integrations/build_RAG_with_milvus_and_crawl4ai.md
  site/en/integrations/build_RAG_with_milvus_and_firecrawl.md
  site/en/integrations/integrate_with_phidata.md
  site/en/integrations/integrations_overview.md
  site/en/integrations/langchain/basic_usage_langchain.md
  site/en/integrations/langchain/full_text_search_with_langchain.md
  site/en/integrations/langchain/integrate_with_langchain.md
  site/en/integrations/langchain/milvus_hybrid_search_retriever.md
  site/en/menuStructure/en.json
Labels: size/XXL

#2987 update docs for 2.5.4 release
  site/en/Variables.json
  site/en/release_notes.md
  site/en/userGuide/schema/sparse_vector.md
Labels: size/L

#2999 Update operational_faq.md
  site/en/faq/operational_faq.md
Labels: size/XS

#3001 add index types: hnsw, flat, ivf, ivf-pq
  assets/hnsw.png
  assets/ivf-1.png
  assets/ivf-2.png
  assets/ivf-pq-1.png
  assets/ivf-pq-2.png
  site/en/menuStructure/en.json
  site/en/userGuide/manage-indexes/floating-vector/flat.md
  site/en/userGuide/manage-indexes/floating-vector/hnsw.md
  site/en/userGuide/manage-indexes/floating-vector/ivf-flat.md
  site/en/userGuide/manage-indexes/floating-vector/ivf-pq.md
Labels: size/L

#3002 deprecate SPARSE_WAND and drop_ratio_build params for sparse embeddings
  site/en/about/limitations.md
  site/en/reference/index.md
  site/en/userGuide/manage-indexes/index-vector-fields.md
  site/en/userGuide/schema/sparse_vector.md
  site/en/userGuide/search-query-get/multi-vector-search.md
  site/en/userGuide/tools/cli_commands.md
Labels: size/L

#2993 update docs
  assets/iterative-filtering.png
  assets/partition-key-isolation.png
  site/en/userGuide/search-query-get/filtered-search.md
  site/en/userGuide/search-query-get/use-partition-key.md
Labels: size/L

#2986 Update multi_tenancy.md
  site/en/reference/multi_tenancy.md
Labels: size/XS
