Repository milvus-io/milvus-docs, pull requests merged in 2025-05, with the labels that each got.

#3130 Update cli_commands.md
  site/en/userGuide/tools/cli_commands.md
Labels: size/L

#3134 update docs
  site/en/userGuide/data-import/prepare-source-data.md
Labels: size/XS

#3137 sync 2.5.x changes to 2.6.x preview
  scripts/lib/larkDocWriter.js
  scripts/yarn.lock
  site/en/adminGuide/grant_privileges.md
  site/en/menuStructure/en.json
  site/en/reference/disk_index.md
  site/en/release_notes.md
  site/en/tutorials/text_image_search.md
  site/en/userGuide/collections/create-collection-instantly.md
  site/en/userGuide/collections/create-collection.md
  site/en/userGuide/data-import/prepare-source-data.md
  site/en/userGuide/insert-and-delete/insert-update-delete.md
  site/en/userGuide/insert-and-delete/upsert-entities.md
  site/en/userGuide/schema/enable-dynamic-field.md
  site/en/userGuide/schema/use-json-fields.md
  site/en/userGuide/search-query-get/consistency.md
  site/en/userGuide/search-query-get/single-vector-search.md
  site/en/userGuide/tools/cli_commands.md
Labels: size/XL

#3147 Update quickstart.md
  site/en/getstarted/quickstart.md
Labels: size/S

#3154 update docs
  site/en/menuStructure/en.json
  site/en/tutorials/use_ColPali_with_milvus.md
Labels: size/S

#3155 update docs
  site/en/userGuide/schema/analyzer/analyzer-overview.md
  site/en/userGuide/schema/analyzer/analyzer/chinese-analyzer.md
  site/en/userGuide/schema/analyzer/analyzer/english-analyzer.md
  site/en/userGuide/schema/analyzer/analyzer/standard-analyzer.md
  site/en/userGuide/schema/analyzer/filter/ascii-folding-filter.md
  site/en/userGuide/schema/analyzer/filter/lowercase-filter.md
  site/en/userGuide/schema/analyzer/tokenizer/icu-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/jieba-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/lindera-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/standard-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/whitespace-tokenizer.md
Labels: size/L

#3157 add multi-language-analyzers
  assets/multi-language-analyzers-workflow.png
  scripts/config.json
  site/en/menuStructure/en.json
  site/en/userGuide/schema/analyzer/multi-language-analyzers.md
Labels: size/XXL

#3159 Revert "Merge branch 'v2.6.x' into v2.5.x"
  assets/phrase-match-workflow.png
  site/en/menuStructure/en.json
  site/en/userGuide/search-query-get/boolean/boolean.md
  site/en/userGuide/search-query-get/phrase-match.md
  version.json
Labels: size/L

#3160 add NLWeb with Milvus
  site/en/integrations/NLWeb_with_milvus.md
  site/en/integrations/integrations_overview.md
  site/en/menuStructure/en.json
Labels: size/M

#3161 update menuStructure
  site/en/menuStructure/en.json
Labels: size/XS

#3164 Fix pic links
  site/en/tutorials/build-rag-with-milvus.md
  site/en/tutorials/contextual_retrieval_with_milvus.md
  site/en/tutorials/hdbscan_clustering_with_milvus.md
  site/en/tutorials/hybrid_search_with_milvus.md
  site/en/tutorials/image_similarity_search.md
  site/en/tutorials/multimodal_rag_with_milvus.md
Labels: size/S

#3166 Update import-data.md
  site/en/userGuide/data-import/import-data.md
Labels: size/XS

#3171 add minor version tags
  site/en/userGuide/schema/analyzer/filter/regex-filter.md
  site/en/userGuide/schema/analyzer/filter/removepunct-filter.md
  site/en/userGuide/schema/use-json-fields.md
Labels: size/XS

#3172 add minor version tags
  site/en/userGuide/schema/analyzer/filter/alphanumonly-filter.md
  site/en/userGuide/schema/analyzer/filter/ascii-folding-filter.md
  site/en/userGuide/schema/analyzer/filter/cnalphanumonly-filter.md
  site/en/userGuide/schema/analyzer/filter/cncharonly-filter.md
  site/en/userGuide/schema/analyzer/filter/decompounder-filter.md
  site/en/userGuide/schema/analyzer/filter/length-filter.md
  site/en/userGuide/schema/analyzer/filter/lowercase-filter.md
  site/en/userGuide/schema/analyzer/filter/regex-filter.md
  site/en/userGuide/schema/analyzer/filter/removepunct-filter.md
  site/en/userGuide/schema/analyzer/filter/stemmer-filter.md
  site/en/userGuide/schema/analyzer/filter/stop-filter.md
  site/en/userGuide/schema/analyzer/multi-language-analyzers.md
  site/en/userGuide/schema/analyzer/tokenizer/icu-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/jieba-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/lindera-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/standard-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/whitespace-tokenizer.md
Labels: size/M

#3174 sync 2.5.x changes to 2.6.x preview
  site/en/userGuide/schema/analyzer/analyzer/chinese-analyzer.md
  site/en/userGuide/schema/analyzer/analyzer/english-analyzer.md
  site/en/userGuide/schema/analyzer/analyzer/standard-analyzer.md
  site/en/userGuide/schema/analyzer/filter/regex-filter.md
  site/en/userGuide/schema/analyzer/filter/removepunct-filter.md
  site/en/userGuide/schema/analyzer/tokenizer/icu-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/lindera-tokenizer.md
Labels: size/S
