Repository milvus-io/milvus-docs, pull requests merged in 2025-04, with the labels that each got.

#3088 update 2.5.8 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#3091 update docs
  assets/binary-vector.png
  assets/dense-vector.png
  assets/schema-explained.PNG
  assets/schema-hands-on.png
  assets/sparse-vector.png
  assets/use-binary-vector.png
  assets/use-dense-vector.png
  assets/use-sparse-vector.png
  assets/vector-index-anatomy.png
  scripts/config.json
  scripts/lib/milvusDocsGen.js
  site/en/menuStructure/en.json
  site/en/reference/schema.md
  site/en/userGuide/manage-indexes/index-explained.md
  site/en/userGuide/schema/alter-collection-field.md
  site/en/userGuide/schema/analyzer/analyzer-overview.md
  site/en/userGuide/schema/analyzer/analyzer/chinese-analyzer.md
  site/en/userGuide/schema/analyzer/analyzer/english-analyzer.md
  site/en/userGuide/schema/analyzer/analyzer/standard-analyzer.md
  site/en/userGuide/schema/analyzer/filter/alphanumonly-filter.md
  site/en/userGuide/schema/analyzer/filter/ascii-folding-filter.md
  site/en/userGuide/schema/analyzer/filter/cnalphanumonly-filter.md
  site/en/userGuide/schema/analyzer/filter/cncharonly-filter.md
  site/en/userGuide/schema/analyzer/filter/decompounder-filter.md
  site/en/userGuide/schema/analyzer/filter/length-filter.md
  site/en/userGuide/schema/analyzer/filter/lowercase-filter.md
  site/en/userGuide/schema/analyzer/filter/stemmer-filter.md
  site/en/userGuide/schema/analyzer/filter/stop-filter.md
  site/en/userGuide/schema/analyzer/tokenizer/jieba-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/standard-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/whitespace-tokenizer.md
  site/en/userGuide/schema/array_data_type.md
  site/en/userGuide/schema/binary-vector.md
  site/en/userGuide/schema/dense-vector.md
  site/en/userGuide/schema/enable-dynamic-field.md
  site/en/userGuide/schema/nullable-and-default.md
  site/en/userGuide/schema/number.md
  site/en/userGuide/schema/primary-field.md
  site/en/userGuide/schema/schema-hands-on.md
  site/en/userGuide/schema/sparse_vector.md
  site/en/userGuide/schema/string.md
  site/en/userGuide/schema/use-json-fields.md
Labels: size/XXL

#3092 update-docs
  scripts/lib/milvusDocsGen.js
  site/en/userGuide/schema/analyzer/filter/lowercase-filter.md
Labels: size/XS

#3093 update docs
  assets/hearing.png
  site/en/about/overview.md
  site/en/userGuide/schema/schema.md
Labels: size/M

#3095 update docs
  assets/dense-vector.png
  scripts/config.json
  site/en/userGuide/schema/dense-vector.md
Labels: size/S

#3096 update docs
  scripts/lib/milvusDocsGen.js
  site/en/reference/schema.md
Labels: size/S

#3097 integration docs
  assets/openai-agent.png
  assets/text_image_search_with_milvus_20_1.png
  site/en/integrations/build_RAG_with_milvus_and_docling.md
  site/en/integrations/build_RAG_with_milvus_and_feast.md
  site/en/integrations/full_text_search_with_milvus_and_haystack.md
  site/en/integrations/integrate_with_haystack.md
  site/en/integrations/integrate_with_llamaindex.md
  site/en/integrations/integrations_overview.md
  site/en/integrations/langchain/full_text_search_with_langchain.md
  site/en/integrations/langchain/milvus_hybrid_search_retriever.md
  site/en/integrations/llamaindex_milvus_full_text_search.md
  site/en/integrations/mistral_ocr_with_milvus.md
  site/en/integrations/openai_agents_milvus.md
  site/en/menuStructure/en.json
  site/en/tutorials/text_image_search.md
  site/en/tutorials/tutorials-overview.md
  site/en/userGuide/schema/array_data_type.md
Labels: size/XXL

#3099 update docs
  .gitignore
  site/en/integrations/mistral_ocr_with_milvus.md
Labels: size/XS

#3100 update docs
  site/en/userGuide/collections/create-collection.md
Labels: size/S

#3102 Update mistral_ocr_with_milvus.md
  site/en/integrations/mistral_ocr_with_milvus.md
Labels: size/M

#3104 update 2.5.9 release notes
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#3105 update docs
  site/en/userGuide/schema/analyzer/analyzer-overview.md
  site/en/userGuide/schema/analyzer/analyzer/chinese-analyzer.md
  site/en/userGuide/schema/analyzer/analyzer/english-analyzer.md
  site/en/userGuide/schema/analyzer/analyzer/standard-analyzer.md
  site/en/userGuide/schema/analyzer/filter/alphanumonly-filter.md
  site/en/userGuide/schema/analyzer/filter/ascii-folding-filter.md
  site/en/userGuide/schema/analyzer/filter/cnalphanumonly-filter.md
  site/en/userGuide/schema/analyzer/filter/cncharonly-filter.md
  site/en/userGuide/schema/analyzer/filter/decompounder-filter.md
  site/en/userGuide/schema/analyzer/filter/length-filter.md
  site/en/userGuide/schema/analyzer/filter/lowercase-filter.md
  site/en/userGuide/schema/analyzer/filter/stemmer-filter.md
  site/en/userGuide/schema/analyzer/filter/stop-filter.md
  site/en/userGuide/schema/analyzer/tokenizer/jieba-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/standard-tokenizer.md
  site/en/userGuide/schema/analyzer/tokenizer/whitespace-tokenizer.md
Labels: size/L

#3109 fix link error
  site/en/adminGuide/tls.md
Labels: size/XS

#3111 update quickstart.md
  site/en/getstarted/quickstart.md
Labels: size/XS

#3103 Update text_image_search.md
  site/en/tutorials/text_image_search.md
Labels: size/XS

#3114 Update milvus_and_mcp.md
  site/en/integrations/milvus_and_mcp.md
Labels: size/XS

#3112 Update privilege_group.md
  site/en/adminGuide/privilege_group.md
Labels: size/XS

#3113 Update grant_privileges.md
  site/en/adminGuide/grant_privileges.md
Labels: size/S

#3115 update 2.5.10 rn
  site/en/Variables.json
  site/en/release_notes.md
Labels: size/M

#3101 update docs
  scripts/lib/milvusDocsGen.js
  site/en/getstarted/milvus_lite.md
  site/en/getstarted/run-milvus-docker/install_standalone-docker.md
  site/en/getstarted/run-milvus-docker/install_standalone-windows.md
  site/en/getstarted/run-milvus-gpu/install_cluster-helm-gpu.md
  site/en/getstarted/run-milvus-gpu/install_standalone-docker-compose-gpu.md
  site/en/getstarted/run-milvus-k8s/install_cluster-helm.md
  site/en/getstarted/run-milvus-k8s/install_cluster-milvusoperator.md
  site/en/getstarted/standalone/install_standalone-aptyum.md
  site/en/getstarted/standalone/install_standalone-helm.md
  site/en/getstarted/standalone/install_standalone-operator.md
  site/en/getstarted/with_gpu/install_standalone-helm-gpu.md
Labels: size/S

#3117 update docs
  site/en/integrations/AIMon_milvus_integration.md
  site/en/integrations/integrate_with_ragas.md
  site/en/integrations/llamaindex_milvus_hybrid_search.md
  site/en/integrations/llamaindex_milvus_metadata_filter.md
  site/en/integrations/rag_with_milvus_and_unstructured.md
  site/en/menuStructure/en.json
Labels: size/XXL

#3118 update docs
  assets/aimon-workflow.png
  site/en/integrations/AIMon_milvus_integration.md
Labels: size/L

#3119 update docs
  scripts/lib/larkDocWriter.js
  site/en/userGuide/collections/create-collection-instantly.md
  site/en/userGuide/collections/create-collection.md
  site/en/userGuide/collections/load-and-release.md
  site/en/userGuide/data-import/prepare-source-data.md
  site/en/userGuide/insert-and-delete/insert-update-delete.md
  site/en/userGuide/manage-indexes/floating-vector/ivf-pq.md
  site/en/userGuide/schema/enable-dynamic-field.md
Labels: size/M

#3121 Update docs
  scripts/lib/larkDocWriter.js
  site/en/userGuide/search-query-get/metric.md
Labels: size/M

#3123 update string.md
  scripts/yarn.lock
  site/en/userGuide/schema/string.md
Labels: size/M

#3124 merge prod into dev
  assets/collection-level-multi-tenancy.png
  assets/database-level-multi-tenancy.png
  assets/partition-key-level-multi-tenancy.png
  assets/partition-level-multi-tenancy.png
  scripts/config.json
  scripts/lib/larkDocWriter.js
  scripts/yarn.lock
  site/en/about/comparison.md
  site/en/reference/multi_tenancy.md
  site/en/userGuide/collections/create-collection-instantly.md
  site/en/userGuide/collections/create-collection.md
  site/en/userGuide/collections/load-and-release.md
  site/en/userGuide/data-import/prepare-source-data.md
  site/en/userGuide/insert-and-delete/insert-update-delete.md
  site/en/userGuide/schema/analyzer/analyzer-overview.md
  site/en/userGuide/schema/enable-dynamic-field.md
  site/en/userGuide/schema/string.md
  site/en/userGuide/search-query-get/metric.md
Labels: size/L

#3125 add phrase match & random sampling
  assets/phrase-match-workflow.png
  scripts/config.json
  site/en/menuStructure/en.json
  site/en/userGuide/search-query-get/boolean/boolean.md
  site/en/userGuide/search-query-get/phrase-match.md
Labels: size/L

#3120 modify the order of the integrations
  site/en/integrations/integrations_overview.md
Labels: size/M
